decred/dcrdata

cmd/rebuilddb/rebuilddb.go, cmd/scanblocks/scanblocks.go, dcrsqlite/apisource.go, dcrsqlite/sqlite.go, dcrsqlite/sync.go, log.go, main.go, sample-dcrdata.conf, txhelpers/staketree.go
Addresses https://github.com/dcrdata/dcrdata/issues/12
This adds automatic resync of DB on startup.  Note that pool value (and avg val) are NOT computed in this resync as it is very involved and slow.  Only rebuilddb will compute the pool value at every block.
Note that new blocks collected by the new block notifier will still have pool value computed.
=> Add DB resync on startup of dcrdata

.gitignore, cmd/rebuilddb/.gitignore, cmd/rebuilddb/rebuilddb.go, dcrsqlite/apisource.go, dcrsqlite/sync.go, glide.lock, glide.yaml, main.go, version.go
Addresses https://github.com/dcrdata/dcrdata/issues/17
This addresses the insane memory usage of rebuilddb.  Maybe also resync from arbitrary height instead of 0.
=> Resync rewrite

apimiddleware.go, apirouter.go, apiroutes.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, dcrsqlite/sqlite.go
Separate /stake into /stake/pool and /stake/diff for ticket pool info and sdiff, resp.  Each have ./b/:ind and ./r/:ind0/:ind endpoints for values at a given block and on a range, resp.
TODO: log warning when sql result is shorter (or longer) than expected for range queries.
Begins to address https://github.com/dcrdata/dcrdata/issues/34, items 1 - 3.  The results need caching, but now there is are at least array returns for sdiff and ticket pool info.
Also continues to address https://github.com/dcrdata/dcrdata/issues/20, which is an open ended issue to add new endpoints for 0.1.0.
=> Add dedicated ticket pool value and sdiff endpoints.

dcrsqlite/sync.go
When a node is disconnected, the on-disk database needs to be updated to reflect the change.  Fixes rewind.
=> Fix rewind - Stake node disconnect needs to be followed by DB update

.gitignore, apiroutes.go, blockdata/blockdata.go, blockdata/chainmonitor.go, blockdata/datasaver.go, cmd/rebuilddb/config.go, cmd/rebuilddb/rebuilddb.go, config.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, dcrsqlite/chainmonitor.go, dcrsqlite/sqlite.go, dcrsqlite/sync.go, glide.lock, glide.yaml, log.go, main.go, mempool/mempool.go, mempool/mempoolcache.go, ntfnchans.go, ntfnhandlers.go, rpcutils/rpcclient.go, stakedb/chainmonitor.go, stakedb/log.go, stakedb/stakedb.go, txhelpers/txhelpers.go, version.go, web.go
Addresses https://github.com/dcrdata/dcrdata/issues/26
This adds `package stakedb` to manage the `dcrd/database.DB` used to track the live ticket pool.  It simplifies startup sync and it has a notification handler to stay updated as blocks come in after the sync.
The dependencies are also updated to Decred 1.0.1 versions.
=> Keep stake DB updated and avoid rewind on startup

blockdata/blockdata.go, blockdata/chainmonitor.go, config.go, dcrsqlite/sync.go, main.go, sample-dcrdata.conf, stakedb/stakedb.go
- Add `CollectBlockInfo` to get by hash most data.
- Remove (no)poolinfo option.  Delete it from dcrdata.conf or dcrdata will not start.
- Give `stakedb.PoolInfo()` a second output, the height of the stake node.
- Bump version to 0.3.3.
=> Make blockdata Collect use block hash-specific functions where possible

apimiddleware.go, apirouter.go, glide.lock, glide.yaml, main.go, web.go
chi has moved from github.com/pressly/chi to github.com/go-chi/chi.  Change this in source and in glide.
Also update to using v3.0 of chi, which changes for dcrdata:
1. FileServer removed so we add our own implementation.
2. url parameters are now specified with `/{param}` instead of `/:param`
=> Switch chi import path, update to chi 3.0

dcrsqlite/sqlite.go, dcrsqlite/sync.go, mempool/mempool.go
This puts a band-aid on the issue of a mempool data collection being initiated before the new block data collection,  which is a problem when mempool collection is retarded by numerous sstx.  There needs to be proper synchronization to prevent mempool collection before block data collection can run.
Also remove some useless code, and optimize `logDBResult` when log level is above trace.
=> Delay call to mempool collection so block data can go first

blockdata/blockdata.go, blockdata/chainmonitor.go, dcrsqlite/chainmonitor.go, dcrsqlite/sync.go, main.go, version.go
In `(*ChainMonitor).BlockConnectedHandler`, call `switchToSideChain`.
Implement `switchToSideChain()`: collect data for side chain blocks and store in sqlite.
Rename `blockdata.blockDataCollector` to `blockdata.Collector`.
Add a `blockdata.Collector` member to the `dcrsqlite.ChainMonitor`.
Create `(*Collector).CollectAPITypes` to get the `apitypes.BlockDataBasic` and `apitypes.StakeInfoExtended` needed to update blocks in sqlite during reorg.
=> Reorg handling for dcrsqlite

apirouter.go, apiroutes.go
This has been running for a while with no trouble.
Reports from @gozart1 are that it dramatically increases the speed of the block range API endpoint.
=> stream and compress block range response

apimiddleware.go, apirouter.go, apiroutes.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, dcrsqlite/sqlite.go, rpcutils/rpcclient.go
This PR primarily adds two new features:
1. Query for a "verbose" block data type, which includes arrays of transactions in the block, but not the expanded transaction details.  This corresponds to the output of `getrawtransaction [hash] verbose=true verbosetx=false`.
2. API endpoints to lookup data by block hash.  Previously it was just height, which made sense for querying ranges.
There are many other incidental changes to dcrsqlite and rpcutils.  In particular, dcrsqlite now has queries for hash by height, and height by hash.
=> Block verbose and block-by-hash

apirouter.go, apiroutes.go, dcrsqlite/apisource.go, dcrsqlite/sqlite.go
This includes range, where an array of integers is returned.
A new SQLite query is added to make this fast.  Only the size column is returned.
TODO: add transaction count somewhere, somehow.
=> Add block size endpoints, like /block/.../size.

config.go
In reference to issue #62, log.warnf seems to always have give a run time error but removing it should exit the app cleanly and still show the error
=> Removed log warning

mempool/mempool.go, ntfnchans.go, ntfnhandlers.go
Send the new `mempool.NewTx` type, which includes a time stamp, instead of just a `chainhash.Hash`.  If age of NewTx is greater than time since last mempool collection, that tx has already been included in a collection and it should not trigger a new collection.
Clean up `(*mempoolMonitor).TxHandler`
This also sneaks in a fix for the sqlite reorg handler not running.  It will run now, but it's not yet clear if it will work as intended.
=> Mempool TxHandler efficiency

views/root.tmpl
The layout is all different now.  This is not quite how I wanted it, but I don't know what I'm doing in HTML/CSS world.
When the websocket updates fields, it does it with fixed precision.
A footer is added, which I actually quite like.  Here it is on a mobile device:
=> Tweak web ui

apiroutes.go, sample-nginx.conf, sample-rate_limiting.html
The sample nginx.conf demonstrates several important settings when using nginx as a reverse proxy:
- websocket upgrade
- RealIP module
- rate limiting
- auto-HTTPS redirect
- SSL cert setup
- gzip settings
The sample rate_limiting.html demonstrates a possible response to the client when requests are being refused due to rate limiting.
=> Add sample nginx.conf and rate_limiting.html

apiroutes.go, dcrsqlite/apisource.go
For bad input address:
- return 422 Unprocessable Entity, not null
- log at level Info. For failed searchrawtransactions, warn
=> Address error handling

README.md, blockdata/blockdata.go, blockdata/chainmonitor.go, dcrsqlite/apisource.go, dcrsqlite/chainmonitor.go, dcrsqlite/sqlite.go, dcrsqlite/sync.go, log.go, main.go, mempool/mempool.go, ntfnchans.go, ntfnhandlers.go, stakedb/chainmonitor.go, stakedb/stakedb.go
This still allows the `OnBlockConnected` handler to return quickly and not block the RPC client, but it band-aids some issues with execution order.
Create the `collectionQueue` in `make`/`getNodeNtfnHandlers` and return it to main so that the synchronous collection functions can be set once they are available.
No longer send directly to the block connected channels for  stakedb, wiredDB, or blockdata.  Instead call the new synchronous function `BlockConnectedSync` of each package's chain monitor.  The individual block connected channels are still used in `BlockConnectedSync`, but signals are used to wait until handling of the signaled block has completed in the old handler loops.
Create `blockdata.(*Collector).CollectHash(*chainhash.Hash)` to be used in the event that the chain node best …
=> collectionQueue to run certain collection functions synchronously and in order

dcrsqlite/sqlite.go
we were RUnlocking after a Lock, oops.  This led to a fatal error
=> Change mutex Lock to RLock

public/css/main.css, views/address.tmpl, views/block.tmpl, views/explorer.tmpl, views/extras.tmpl, views/root.tmpl, views/tx.tmpl
- Makes footer present on all pages.
- Moves the top nav links that lead off the site into the footer nav.
- Hides WebSocket activity indicator render unless connection script is running.
This reorg frees up space to make more room for search on small screens https://github.com/dcrdata/dcrdata/issues/115
=> move github/api/status links into footer, render #connection conditionally

explorer.go, main.go, views/address.tmpl, views/block.tmpl, views/error.tmpl, views/explorer.tmpl, views/extras.tmpl, views/root.tmpl, views/tx.tmpl, web.go
This should address issues:
#116, #117, #118, #119, #120, #122, #123, #124 and #126
=> Bug Fixes and Enhancements

explorer.go, public/css/main.css, views/address.tmpl, views/block.tmpl, views/error.tmpl, views/explorer.tmpl, views/root.tmpl, views/tx.tmpl
This change addresses items in https://github.com/dcrdata/dcrdata/issues/118
- reduces the padding of table cells
- replaces row borders with subtle striped background to help delineate rows
- adds subtle background to table headers
- moves explorer navigation older/newer links onto same line on top of table
- updates explore min to 20 rows since more space is now available
- green links ( improve readability )
- font antialiasing ( improve readability )
=> Template roundup

apiroutes.go, dcrsqlite/apisource.go, explorer.go, public/css/main.css, txhelpers/txhelpers.go, views/tx.tmpl
Modify the tx.tmpl for the Transaction page so that it shows the Previous Outpoints, their first Address (could be multisig), Block, and Value. Tree is dropped.
Add txhelpers.OutPointAddresses, which gets the addresses payed to by a transaction output.
The outpoint CSS class is added to be a bit wider than the hash type.
This probably needs tweaking, but here it is:
=> Previous OutPoint Addresses in Tx view

apirouter.go, apiroutes.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, txhelpers/txhelpers.go
This adds the plumbing needed to inspect the vote bits of a ssgen (vote) transaction and determine the vote version, last block validity and block voted on, and choices made on any agendas for the vote version.
The partially addresses Issue https://github.com/dcrdata/dcrdata/issues/141.  Some UI design is needed to complete it.
Functions added:
- SSGenVoteBlockValid
- VoteBitsInBlock
- SSGenVoteBits
- SSGenVoteChoices
structs added:
- BlockValidation
- VoteChoice
=> Add SSGen/vote inspection helpers

dcrsqlite/apisource.go, glide.lock
Addresses Issue https://github.com/dcrdata/dcrdata/issues/143
Dependencies are updated to get current revision of dcrrpcclient, which contains the fix for the `SearchRawTransactions` bug described in https://github.com/decred/dcrrpcclient/pull/89
Please verify that this is the intended operation.
=> Reverse address tx list

explorer.go, glide.lock, glide.yaml, views/address.tmpl, views/block.tmpl, views/explorer.tmpl, views/tx.tmpl
This change imports the go-humanize lib to:
- format various kinds of numbers with commas in the explorer.
- formats bytes so that it shows in "kB" or "B" depending on size.
- Instead of printing out 'DCR' in every cell, use the column header to label the unit
What is the preferred way to share these functions so they can also be used in root.tmpl?
=> format explorer numbers with commas (WIP)

dcrsqlite/apisource.go, dcrsqlite/chainmonitor.go, rpcutils/rpcclient.go, txhelpers/txhelpers_test.go, web.go
In general, the string in error types should be lowercase.  But when there is printf-style formatting going on, particularly with sentence structure, I think it's OK to have some capitalization as it's probably just going to a log message.
=> Tweak logging levels and error messages

dcrdataapi/apicache.go, dcrdataapi/apicache_test.go
This is broken out of PR https://github.com/dcrdata/dcrdata/pull/63.
`APICache` implements `BlockSummarySaver`, which takes a `*BlockDataBasic`
and caches it. A block priority queue, `BlockPriorityQueue`, is maintained
by `APICache` to decide which blocks to evict if needed. The "LessFn" can
be set to an arbitrary comparator of two `CachedBlock` values. There are
methods to remove and retrieve blocks from the cache.
=> Add a block data cache, APICache.

public/css/main.css, views/explorer.tmpl, views/root.tmpl, views/tx.tmpl
- Explorer
Align styling and column order of explorer table with that of 6 blocks table in root.tmpl.
Fix prev/next links ( current logic is thrown off by commas in block heights )
- Transaction
Add Links to "In" addresses 
Splits address onto 2 lines on small screens
- Sticky Top Nav
Made the top nav sticky. The main reason for this to allow for a more flexible layout on small screens where the tables often overflow. Instead of making all the tables scroll within themselves when they don't fit. We can just let them expand the width of the page as needed this way.
=> Layout tweaks

apiroutes.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, explorer.go, public/css/main.css, txhelpers/txhelpers.go, views/tx.tmpl
- Create Vote Info table that displays on `/explorer/tx/...` for a ssgen.
- Call `APIDataSource.GetVoteInfo` from `explorerUI.txPage` and execute the template with the vote info included in the existing template data struct.
- Add vote bits to `dcrdataapi.VoteInfo`.
- `txhelpers.SSGenVoteChoices` now returns vote bits too.
- `GetRawTransactionWithPrevOutAddresses` returns `*wire.MsgTx` as new 4th output argument.
Addresses Issue https://github.com/dcrdata/dcrdata/issues/141, but we should consider improved styling.
=> Show vote info and choices on Tx explorer page

public/js/humanize.js, views/extras.tmpl, views/root.tmpl
Ended up hand-rolling the humanize.bytes in javascript since https://github.com/HubSpot/humanize makes different choices than https://github.com/dustin/go-humanize with regard to bytes formatting
@RogueElement do I have your blessings to move `timeSince` into humanize.js as well?
=> add custom humanize.js, humanize time & bytes when block is added via js

.gitignore, Gopkg.lock, LICENSE, apimiddleware.go, apiroutes.go, dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorermiddleware.go, explorer/explorertypes.go, explorer/log.go, explorer/reloadsig.go, explorer/reloadsig_windows.go, log.go, main.go, reloadsig.go, reloadsig_windows.go, views/address.tmpl, views/block.tmpl, views/explorer.tmpl, views/tx.tmpl
For issue #198 and #138
Current issues being addressed in V2:
Improvements over V1:
=> Explorer V2

dcrsqlite/apisource.go, explorer/explorer.go
GetExplorerBlock/GetExplorerBlocks could crash dcrdata if dcrd goes away suddenly
Also rename GetExploreBlock to GetExplorerBlock
=> nil pointer checks with GetExplorerBlock(s)

dcrsqlite/apisource.go, explorer/explorertypes.go, views/tx.tmpl
Addresses issue https://github.com/dcrdata/dcrdata/issues/217
As usual, this is just terrible get-it-done web programming.  Sorry.
=> Show block validity for ssgen, reintroduce BlockValidation type

public/css/main.css, views/tx.tmpl
This fixes firefox layout issue by moving `break-word` class to the block level element, apparently Firefox calculates table cell widths a bit differently.
It PR also set a max-width on addresses in output table, so that in full screen width instead of only a few characters overflowing to next line, half of the address is on new line.
=> improve address formatting in tx.tmpl (fixes firefox issue as well)

views/explorer.tmpl
This fixes https://github.com/dcrdata/dcrdata/issues/214
I accidentally added an extra timestamp class here
https://github.com/dcrdata/dcrdata/commit/0dfee4fce0bd80275bac025a3ddd3d42d918ca2c#diff-8da9f57161fc081f8fd8fed05b5ed3f1R18
which was causing the timeSince fn to get bogus input.
=> fix bogus timestamp in 1st row of explorer.tmpl

dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorertypes.go, views/address.tmpl, views/block.tmpl, views/extras.tmpl, views/tx.tmpl
This moves formatting of trailing zeroes in DCR values to the server.
There should be no difference in terms of presentation, other than removed the flash of un-styled content on page load.
This simply uses Sprintf to round to 8 decimals, so this doesn't fully address rounding issues in mentioned in https://github.com/dcrdata/dcrdata/issues/195
I haven't tried optimizing the formatting function, still getting familiar with Go so if you see any obvious optimizations or issues feel free to push a commit/comment.
=> format trailing DCR zeroes on server instead of client

dcrsqlite/apisource.go, txhelpers/txhelpers.go, views/root.tmpl
This fixes floating point precision issues with amount sums.
- Add `txhelpers.TotalVout `to sum each Value for a slice of `Vout`s in `dcrutil.Amount `instead of `float64`.
- Fix `Total` sent precision by summing in `dcrutil.Amount`.
<s>Related, fix coin coin supply display, which was sent to template exec as a string.
- `BlockExplorerExtraInfo.CoinSupply` is now a `int64 `instead of a string.  Previously the string had the `" DCR"` prefix baked in, which messed up the trailing zero styling.
- Add js function `styleAmountAsDCRVal `to handle trailing zero styling similar to `styleDCRVal `but taking an `int64 `with decred atom semantics instead of a `float64 `(coin).  This applies automatically to elements of class `"dcr-amount"`.</s> coin supply fix later
=> Float amount precision and coin supply formatting

dcrsqlite/apisource.go, explorer/explorertypes.go, views/tx.tmpl
Should address #110. For an unconfirmed tx, all outputs should show false in the spent column. @gozart you probably have a better idea on how to display this.
=> Show if tx ouput is spent or unspent

blockdata/blockdata.go, dcrdataapi/apitypes.go, explorer/explorer.go, views/address.tmpl, views/block.tmpl, views/extras.tmpl, views/root.tmpl, views/tx.tmpl, web.go
NOTE:  Coin supply is not updated by websocket yet, so this number never changes unless the page reloads
This PR removes `" DCR"` suffix from value passed from go to browser.  Now a JS function expecting just a number that operates on it will not fail.
Add `amountAsFloatParts` function to web and explorer template maps.  It takes an amount as `int64` and returns a `[]string` of: part left of decimal place, right with trailing zeros removed, and trailing zeros.
Add `fancyFloatParts` html template definition that takes the `[]string` from `amountAsFloatParts` and creates a stylized floating point coin value.
Adjust title of root page.
=> Change coin supply to int64 and format nicely.

public/js/humanize.js, views/address.tmpl, views/block.tmpl, views/explorer.tmpl, views/extras.tmpl, views/root.tmpl, views/tx.tmpl
- Corrects a bug were the wrong type was being passed to timeSince ( requires unixTime, was getting native Date object )
- Simplifies handling of timestamp values by using data attribute, instead of coordinating index of 2 separate arrays of elements.
=> handle age formatting via data attributes

dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorertypes.go, views/tx.tmpl
As described in #247
Some sample scenarios:
=> add maturity progress bar to tx.tmpl

public/css/main.css, views/tx.tmpl
This addresses #244 by tweaking the layout of table cells in tx.tmpl so that the input and output rows are the same height as much as possible over a wide range of screen sizes. Text balancing is tricky business and it's not really possibly to have maintainable/efficient code AND have it look perfect for ALL screen widths. This is an effort to improve over the current state while keeping the CSS simple.
As the old woodcutters saying goes:
"Hew to the line and let the chips fall where they may"
Here's a bunch of screen grabs at various screen widths:
=> balance cell dimensions of Input/Output tables in tx.tmpl

db/dcrpg/postgresql-tuning.conf, main.go
The threshold of blocks behind tip to rebuild indexes is way to low.
Also recommend `synchronous_commit` for general use.
=> Do not rebuild indexes so easiliy.

explorer/explorer.go, explorer/explorertypes.go, public/css/main.css, views/address.tmpl, views/extras.tmpl
This adds some basic pagination UI to address.tmpl 
issue #262
=> add simple transactions pagination to address.tmpl

db/dcrpg/pgblockchain.go, version.go
Do not error on dev subsidy address that cannot be decoded (e.g. testnet).
Drop "pre" from version string.
=> Testnet dev subsidy fix

public/css/main.css, public/js/jquery.js, version.go, views/extras.tmpl, views/tx.tmpl
If an output has an address, always display it, and if there is also OP_RETURN data, show a "toggle OP_RETURN" txt to display the data on click.
If an output has no decoded address, but OP_RETURN, show it like before.
Unspendable 0 value outputs marked as n/a in Spent column.
Addresses issues https://github.com/dcrdata/dcrdata/issues/272 and https://github.com/dcrdata/dcrdata/issues/248
A vote's outputs:
A ticket's outputs:
Then, after clicking the "toggle OP_RETURN" text:
=> tx page: Always show any decoded addresses, toggle OP_RETURN display.

apirouter.go, apiroutes.go, db/dcrsqlite/apisource.go, dcrdataapi/apitypes.go, explorer/explorer.go, explorer/websocket.go, public/css/main.css, views/block.tmpl, views/extras.tmpl, views/rawtx.tmpl, views/tx.tmpl
For issues #190 and #136 . The rpc api has no "getrawblock" function so that can't be added, but the view raw link works as intended now, showing the txid and hex while the view decoded link shows the json output. The decode tx pages works as intended as well but doesn't look so good for now.
=> Added decode tx page and view raw link

explorer/explorer.go, explorer/websocket.go, public/js/messagesocket.js, version.go, views/extras.tmpl, views/rawtx.tmpl
Addresses issue https://github.com/dcrdata/dcrdata/issues/285.
- Set server's response event IDs to the incoming message's event ID + "Resp".
- Client side ping (in JS) was not sending a JSON response, which the server's websocket handler did not appreciate.  Fix this by using the same send function (i.e. `function(eventID, message)`) as the other messages.
- Recognize the "ping" event ID in server's websocket read loop.
- Change client side ping from every 1 sec to 7 seconds.
- Create websocket read timeout, set to 12 seconds. Write is 10 seconds.
- Set both read and write deadlines where appropriate.
- Docs.
- Fix reloading of explorer templates with SIGUSR1.
- Add pulse effect to rawtx result box to ack click/keypress.
=> explorer websocket: check error on websocket.JSON.Receive, fix client ping

public/css/main.css, views/address.tmpl, views/block.tmpl, views/tx.tmpl
This makes is so that the DCR sum value is consistently located in the top right across the tx, block and address views.
=> move address TOTAL UNSPENT to top right

explorer/explorer.go, views/address.tmpl, views/block.tmpl
Change the template function `int64Comma(v int64)` into `intComma(v interface{})` using a type switch to accept all integer types.
Use `intComma` to give the block size text a hover text for the comma-formatted bytes, as show below:
(the mouse pointer isn't shown, but it's hovering over the size text)
=> explorer: make int64Comma generic

Gopkg.lock
`dep ensure -update github.com/decred/dcrd github.com/decred/dcrwallet`
github.com/decred/dcrd/rpcclient was updated for go1.10 support.
=> dep update dcrd and dcrwallet for rpcclient fix for go1.10

views/extras.tmpl
The javascript for PoW diff update was configured for a DCR amount with no commas.  Do not divide by 1e8, and use commas.
=> Fix websocket update of PoW diff

apiroutes.go
The stepped endpoint could insert a comma in the Json array, making it invalid for parsers.
Also, the result of GetSummary was not checked so a bad request could continue to execute queries for many non existing blocks
=> block range fixes

explorer/websocket.go
keep calls to register/unregister synchronous and in the main run loop since it's not thread safe
=> websocket: do not run unregister client asynchronously

db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/address.tmpl
sstx transactions appear in address without a credit or debit into the address, to show this types of transactions we are displaying 'sstxcommitment' in the credit column of these transactions for visibility. Also if the transactions exceed the maximum number of transactions the totals at the top become very inaccurate, to fixed this it is replaced with unavailable.
=> Amendments to the address page summary

db/dbtypes/extraction.go, db/dcrpg/pgblockchain.go, explorer/explorer.go
The testnet2 dev address cannot be decoded from the org pkscript because a bogus public key script is hard coded by dcrd
=> fix failure to decode testnet2 dev address

explorer/explorer.go
the crash fix for testnet2 merged in PR https://github.com/dcrdata/dcrdata/pull/332/files broke the display of the dev address balance
=> unbreak dev address balance after previous crash fix 

db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, db/dcrsqlite/sync.go, stakedb/stakedb.go
Special handling for error message that should not be shown on fresh sync.
Add error return to several functions, including `dcrsqlite.NewDB`.
Fix returned height from `GetBlockSummaryHeight` when db is empty.
Do not log scanning progress for block 1 when just did genesis.
=> improve fresh start error handling and logging

explorer/explorer.go, explorer/explorerroutes.go
`GetExplorerAddress` ran w/o a nil pointer check in the AddressPage handler.
Also add a `Gosched()` in `updateDevFundBalance` since it's low priority and CPU intense.
=> Nil ptr check getexploreraddress

stakedb/stakedb.go
Address startup errors like this, which often happen after an unclean shutdown and would require a rebuild:
[ERR] SQLT: Unable to create stake DB: StakeDB height (238105) and TicketPool (238106) height not equal.Delete both and try again
Now it backs up the "TicketPool" to match the height of the StakeDB.
=> try to recover from crash where ticket DB can get ahead of stake DB

config.go, main.go
This adds a new config option `--httpprofprefix` to specify the URL path prefix for the HTTP profiler.  For example, given `-p --httpprofprefix  "/pp"`, the http hander will be available at:
/pp/debug/pprof/
Note that the "`/debug/pprof/` part is not changeable, and the trailing slash is required.  But this path may be hidden via the prefix.
=> http profiling: fix mount of default http mux as a subroute

cmd/rebuilddb/rebuilddb.go, cmd/rebuilddb2/rebuilddb2.go, config.go, db/dcrsqlite/apisource.go, explorer/explorer.go, main.go, stakedb/stakedb.go
Add `appdata` and `datadir` options to config, and reorganize database folders.  The config file may be:
1. missing
2. default location (in appdata)
3. specified on command line with `-C`
Templates folder (views folder with tmpl files) must be in same folder as the executable.
Addresses issue #363.
appdata layout looks like this now:
```
.
├── data
│   └── mainnet
│       ├── dcrdata.sqlt.db
│       ├── stakenodes
│       │   └── metadata
│       │       ├── 000006.log
│       │       ├── 000008.ldb
│       │       ├── 000009.ldb
│       │       ├── 000010.ldb
│       │       ├── 000011.ldb
│       │       ├── CURRENT
│       │       ├── LOCK
│       │       ├── LOG
│       │       └── MANIFEST-000007
│       ├── ticket_pool.db
│       └── ticket_pool.db.lock
├── dcrdata.conf
└── logs
└── …
```
=> config: add appdata/datadir options

views/address.tmpl
Showing only the applicable page sizes on the address page
If 20rows are being returned, then the page size selector should not be shown.
If 95 rows were being returned, page size options should be 20, 95.
If 522 rows were being returned, page size options should be 20, 100, 522.
resolving https://github.com/decred/dcrdata/issues/360
=> Address page: Only show the applicable page sizes

explorer/websocket.go, explorer/websockethandlers.go, views/extras.tmpl
Follow up to #343:
This add a buffer `WebsocketHub.newTxBuffer` of size `newTxBufferSize`
for the websocket new tx sends. The websocket clients are now of type
`client` (`[]*MempoolTx` and `sync.RwMutex`) to accommodate the bulk sends.
A ticker function, `WebsocketHub.periodicBufferSend()`, is sent on a
goroutine at the start of `WebsocketHub.run()` that sends the buffer every
`bufferTickerInterval` seconds. The buffer is cleared on every send.
=> Add websocket tx send buffer

explorer/websockethandlers.go
The send and receive loops in `RootWebsocket` were both running
`(*WebsocketHub).UnregisterClient`.  In addition, `RootWebsocket` had a
`defer` running `UnregisterClient`. Only the deferred call is needed. 
Remove the other two.
In the receive loop, a warning was always issued when `JSON.Receive`
returned a non-nil error.  However, when a client is lost, `"EOF"` is
expected, so do not log in this case.
=> explorer/websocket: avoid repeatedly unregistering a websocket client

db/dcrsqlite/apisource.go, explorer/explorertypes.go, explorer/mempool.go, views/extras.tmpl, views/mempool.tmpl
Another follow up to #343. Still [WIP] because I have no idea how identify votes spending the same ticket so I can combine them. Currently reduces vote count to around 5-7.
=> explorer/mempool: Ignore mempool votes not for the tip block

README.md, cmd/rebuilddb2/README.md
There is no longer a `-u` flag for rebuilddb2.
- dcrdata.conf lives in `appdata` now.
- Remind developers to update the dep binary prior to committing changes
to Gopkg.lock
- Cleanup and wrapping
=> README.md: syntax and appdata changes

.gitignore, cmd/rebuilddb2/config.go, cmd/rebuilddb2/rebuilddb2.go, cmd/rebuilddb2/version.go, db/dcrpg/pgblockchain.go
Modify rebuilddb2 to load the `StakeDatabase` (and ticket pool db) *after*
creating the `ChainDB` so that it is not necessary to load the ticket pool
db when only using `ChainDB` to drop tables.
Add "rebuild_data/" to .gitignore.
=> ChainDB/rebuilddb2: add to ChainDB the ability to set a StakeDatabase

db/dcrsqlite/apisource.go, explorer/mempool.go
Some linters are confused by the go-humanize import when it is missing
an explicit name of the package, humanize. Fix this by naming it
humanize in the source where it's not already done like that.
=> name the go-humanize import

main.go
This prevents dcrdata from using a network node for a network (mainnet, testnet, simnet) that does not match the network specified with dcrdata's flags (e.g. --mainnet).
Previously, one could use `--testnet`, while the config file specifed `dcrdserv=host:19109` (i.e. likely a testnet node) and dcrdata would do it's best, eventually throwing hard to diagnose errors.
Now, dcrdata refuses to operate:
```
[CRT] DATD: Network of connected node, TestNet2, does not match expected network, MainNet.
[INF] DATD: Closing connection to dcrd.
[INF] DATD: Bye!
[ERR] DATD: expected network TestNet2, got MainNet
```
This resolves issue #387 .
=> main: check network is the expected one

views/extras.tmpl
To enable desktop notifications, the user must click the connection
indicator at the bottom right.
This resolves issue #374
=> html templates: Do not automatically request to enable desktop ntfns

main.go
Instead of using the default `http.ListenAndServe`, configure the `http.Server` with sensible (not infinite) read and write deadlines, and use `(*http.Server).ListenAndServe` (similarly for `ListenAndServeTLS`).
Thanks @raedah 
https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
=> main: configure http.Server with ReadTimeout and WriteTimeout

README.md
Refer to new `appdata` setting.
Describe `--pg` instead of `--lite`, which was removed.
Formatting.
=> README.md updates for 2.0

explorer/websocket.go, explorer/websockethandlers.go
Remove the ping loop from each websocket connection handler, and create
(wsh *WebsocketHub).pingClients() that is started from run().
It returns a channel that stops the loop when closed.
=> explorer/websocket: fix insane ping loop that was in websocket handler

api/apirouter.go, api/apiroutes.go, db/dcrsqlite/apisource.go, middleware/apimiddleware.go
Alexandre de Sousa created a spreadsheet to keep track of voted tickets (collecting stats, etc), using the dcrdata API. Some users were complaining that they have too many tickets and that the spreadsheet was unable to load them all. I proposed changing dcrdata do accommodate for "pagination". This involved using the "skip" parameter in "GetAddressTransactionsRawWithSkip" calls, so i had to change the whole call stack to add this new parameter.
Also, i removed duplicated code from GetAddressTransactionsWithSkip and GetAddressTransactions.
=> Adds pagination to /address API

explorer/websocket.go, explorer/websockethandlers.go
Each connection's `(exp *explorerUI).RootWebsocket` now stores a pointer
to it's own client data.  Previously each connection had to look up
this object in the `WebSockethub` client map, which was not thread-safe.
Add type `clientHubSpoke`, which wraps the `*client` and the corresponding `*hubSpoke`.
Change `WebsocketHub.Register` from `chan *hubSpoke` to `chan *clientHubSpoke`
Update `(wsh *WebsocketHub).RegisterClient` to return the `*client` created for the input `*hubSpoke`, and
send a `*clientHubSpoke` to the event loop, where `registerClient` will
actually insert the client into the `WebSockethub`'s client map.
=> explorer: avoid concurrent map access

explorer/websocket.go, explorer/websockethandlers.go
- do not log error when ws is just closed
- create explorer.ErrWsClosed string, and check in deferred closeWS, and in both send and receive loops
- include number of websocket clients in registering message
=> explorer: close websocket

README.md, api/apiroutes.go, api/types/apitypes.go
README: begin adding types to API endpoint tables
api/types: apitypes.BlockTransactionCounts
api: use apitypes.BlockTransactionCountsin getBlockTransactionsCount
=> add corresponding type names to API docs

db/dbtypes/types.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, txhelpers/txhelpers.go, views/address.tmpl
This provides a major overhaul to the full-mode address page.   The main introduced change is, a new drop-down listbox on the address page with the following options: "All", "Credit", and "Debit".
Other related changes:
The page size logic in the address html template is also simplified.
The problem of URL query params disappearing was related to the solution we used for handling redirects from the search page.  Instead of:
```go
w.Header().Set("Turbolinks-Location", "/address/"+address)
```
we should use:
```go
w.Header().Set("Turbolinks-Location", r.URL.RequestURI())
```
This will include the path, as before, but also include the URL queries (e.g. `?txntype=credit&n=20&start=0`).
Resolves issue #377 .
=> address page: credit/debit txn filter

public/css/main.css, views/home.tmpl, views/tx.tmpl
Updates progress bar appearance so to be more like the design comps. The gray background is a bit darker than the comp and a slight drop shadow has been added to the white text to improve readability when it overflows the green bar.
design comp:
PR:
=> restyle progress bars

db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, txhelpers/txhelpers.go
This is extracted from the swelling address-filter PR.
Add func UnconfirmedTxnsForAddress.
Updated AddressInfo type.
Modify explorer.AddressPage to get unconfirmed txns and store them.  They are not displayed at all.  Treat this as an example.
=> Unconfirmed transaction helpers, reworked CountUnconfirmedTransactions

db/dcrpg/pgblockchain.go, explorer/explorerroutes.go, views/address.tmpl
Use `r.URL.RequestURI` to set the `Turbolinks-Location` html header correctly on the Block and Transaction page.  This was already addressed on the Address page.
=> do not drop URL query params

api/apirouter.go, api/apiroutes.go, api/types/apitypes.go, api/version.go, config.go, main.go, version/version.go
This is a step toward addressing PR #399 .  It adds the `db_block_time` key to the `/api/status` response:
```json
{
"ready": true,
"db_height": 231821,
"db_block_time": 1524286912,
"node_height": 231821,
"node_connections": 1,
"api_version": 1,
"dcrdata_version": "2.0.0"
}
```
This is UNIX epoch time, so it is easy to compute the age of the block.  In addition, the user may check:
1.  `db_height` and `node_height`
2. `ready`, which should now be fixed, such that it only reports true when `db_height == node_height`
This PR also creates a `version` package for dcrdata, uses the proper app version in the status response, and bumps `APIVersion` to 1.
=> Add db_block_time to API JSON status response

public/css/main.css, views/extras.tmpl, views/home.tmpl
This change makes it so the mempool table on home page takes up a bit less space.
The transaction column now takes up as much space as is available, while the rest of the columns have fixed widths set to accommodate their widest possible values. 
Couple notes:
- Added title attribute so full hash is shown in hover state
- The full value of the tx hash is always there in the html, so users can still copy/paste a full tx hash into their browser Find function <img width="660" alt="screen shot 2018-04-26 at 12 14 35 am" src="https://user-images.githubusercontent.com/25571523/39291180-fd4b6394-48e6-11e8-86be-2982e683773a.png">
- moved "more mempool" & "more blocks" links up to their respective headings and re-worded to "see more", to further conserve space
Old:
New:
=> use flexbox & truncate tx hash to compact mempool table on home page

db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/tx.tmpl
Proposed fixes for #281 
the ROI calculation for the main page was adjusted to take into consideration 50% likelihood days based on the following Poisson calculation of probabilities:
> Chance for a ticket to be voted in a given time frame:
> 1 - (1 - P)^N
> 
> Where:
> P is the probability of a vote in one block.
> N is the number of blocks before ticket expiry.
**Main Page**
ROI_DAYS= [[ ln(50%) / ln(1-(5/ACTUAL_TICKET_POOL)) ] + TICKET_MATURITY +COINBASE_MATURITY ] / BLOCKS_PER_DAY
**Transaction Page**
Added probability bar chart for this ticket based on time to expiry.  I'm not sure if this is what @raedah was referring to in https://github.com/decred/dcrdata/issues/281#issuecomment-374038922 or not but I felt it would be useful on this page.
Please let me know if you have any …
=> Ticket Probability Fixes 

README.md, api/apirouter.go, api/apiroutes.go, api/types/apitypes.go, db/dcrsqlite/apisource.go, txhelpers/subsidy.go, txhelpers/subsidy_test.go
This adds the `/supply` API endpoint and `apitypes.CoinSupply`.
txhelpers/subsidy.go is added with the function `UltimateSubsidy`.
=> api: add coin supply

public/css/main.css
=> add missing night mode styling for flex table header bg & row borders

explorer/explorer.go
This should address #373 .  Per the dialog there it looks like we have a race condition causing this problem.  There are two potential solutions as discussed in the bug.
The problem is difficult to replicate on my system - likely because my server architecture behaves differently than the server.  However, I was able to quite easily replicate the issue locally by inserting a small delay in the async call as shown here:
```go
func (exp *explorerUI) updateDevFundBalance() {
time.Sleep(10000) //sleep for 10,000 ns
// yield processor to other goroutines
runtime.Gosched()
exp.NewBlockDataMtx.Lock()
defer exp.NewBlockDataMtx.Unlock()
devBalance, err := exp.explorerSource.DevBalance()
if err == nil && devBalance != nil {
exp.ExtraInfo.DevFund = devBalance.TotalUnspent
} else { …
```
=> dev funds zero

blockdata/chainmonitor.go, db/dcrsqlite/chainmonitor.go, notification/ntfnchans.go, notification/ntfnhandlers.go, stakedb/chainmonitor.go, stakedb/stakedb.go
Do not leave OnReorganization before each handler sets the reorg flag.
Make reorg channels unbuffered.
This is intended to address a possible panic if `OnReorganization` before each handler that connected to `OnBlockConnected` has gone into reorg mode.
=> notification: make each reorg handler indicate when it is finished

Gopkg.lock, config.go, main.go, stakedb/stakedb.go
This PR adds the ability to start the gops agent running (see https://github.com/google/gops).  The gops agent is used in conjunction with the `gops` command line tool to report information including: the current stack trace, Go version, memory stats, etc.  Profiling and traces can also be collected for 30 and 5 second intervals, respectively.
=> main: add optional gops agent and instrumentation

public/images/favicon/manifest.json, views/extras.tmpl
The name of the currency is Decred and the logo stylization does not
change that.
=> Replace "deCRED" occurences with "Decred".

db/dcrsqlite/apisource.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/tx.tmpl
Block reward transactions are slightly confusing at present because the total value of inputs does not match the total value of outputs.  An example is as follows:
**18.43873754 != 2.63410536 + 62.79779869**
To make these transactions less confusing the block fees are displayed in coinbase transactions as follows:
I will continue to look for alternatives to the two step function call GetBlockHash(tx.BlockHeight) -> GetExplorerBlock(blkHash) to get block fees.  Recommendations welcome.
=> explorer: show miner fees in coinbase transaction

api/insight/apimiddleware.go, api/insight/apirouter.go, api/insight/apiroutes.go, main.go, middleware/apimiddleware.go
This PR is ready for testing on the broadcast Tx endpoint
[17] send_tx
Also a new standard API failure packet was included as described in PR #479. 
**Valid Successful Response**
```
{
"rawtx": "18a4eeed058c2266512863d03f79651cd38d94d6d682ae3f1e4aad0178c6998f"
}
```
**Failure Response**
```
{
"status": 404,
"url": "/insight-api/tx/send",
"error": "SendRawTransaction failed: -1: Rejected transaction 18a4eeed058c2266512863d03f79651cd38d94d6d682ae3f1e4aad0178c6998f: orphan transaction 18a4eeed058c2266512863d03f79651cd38d94d6d682ae3f1e4aad0178c6998f references outputs of unknown or fully-spent transaction 1d3fe2879c60c040fc5b3426aa305b29565aa27035726eaccbb4970b6971de84"
}
```
**Creating a raw transaction for testing**
Below is a powershell script for creating a new raw transaction using …
=> Insight API broadcast_tx [17]

.travis.yml, Gopkg.lock, run_tests.sh
This change modifies the tests to use the same Docker image as other Go projects use.
I did modify the process slightly by adding an 'include' for rsync, so that it includes any files that are tracked by git but would normally be ignored by the .gitignore.
As per other projects, should be able to use ./run_tests.sh to run tests locally inside docker image, giving a more consistent environment for tests.
=> Docker tests

api/insight/apimiddleware.go, api/insight/apirouter.go, api/insight/apiroutes.go, api/insight/converter.go, api/types/apitypes.go, api/types/insightapitypes.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/queries.go, main.go, middleware/apimiddleware.go
This PR replaces PR #450 and was developed by both @rmukhamet and I.  This PR addresses issues #260 and #400 but does not yet close them. 
The following Insight API endpoints are completed with exceptions as noted below.
[6]  tx/{txid}
[6.1] tx/{unknown txid}
[15] addrs/{addr1},{addr2}/txs
[15.1] addrs/{addr1},{addr2}/txs?from=X&to=Y
[16]  addrs/txs (POST)
[16.1] addrs/txs (POST with from/to)
[16.2] addrs/txs (POST with noAsm)
[16.3] addrs/txs (POST with noScriptSig)
[16.4] addrs/txs (POST with noSpent)
All endpoint comparisons are visible here:  https://docs.google.com/spreadsheets/d/1WGHezqRG5VY-t4O6cGpZGwsq69IKJ3deEnERaVvQOb4/edit?usp=sharing
**JSON output comparison for [6]**
**JSON output comparison for [15],[16]**
Notable issues
1.  Vin addresses for transactions that are spending …
=> Insight API [6], [6.1], [15], [15.1], [16], [16.1], [16.2], [16.3], [16.4]

api/insight/apimiddleware.go, api/insight/apirouter.go, api/insight/apiroutes.go, api/types/insightapitypes.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, txhelpers/txhelpers.go
This PR is ready for testing on the UTXO endpoints:
[10] addr_utxo
[11] multi_addr_utxo
[12] POST_multi_addr_utxo; 
In addition the following changes were implemented:
1.  New standard API failure packet.  Return values for failure modes is highly inconsistent across mainnet and bitpay api.  We used the return error format from bitpay for a blank hash on a block call as our model.  Specifically:
```
{
"status": 404,
"url": "/api/block/",
"error": "Not found"
}
```
I hope to align all Insight API failure responses to use this method.
2.  rawblock endpoint was fixed.  so [3] and [4] are also ready for test.
**Valid UTXO Response**
The target UTXO schema is shown below:
(latest version can always be found here:  https://docs.google.com/spreadsheets/d/1WGHezqRG5VY-t4O6cGpZGwsq69IKJ3deEnERaVvQO …
=> Insight API UTXO+ [10] [11] [12] [3] [4]

explorer/explorerroutes.go
This is a fix for PR #456.
Blockhash is not set in a ` GetRawTransactionVerbose` until after the first confirmation.  Therefore the existing code will fail for transactions with only one confirmation.  A call to `GetBlockHash` however does work on 1 confirmation.
There are three solutions:
1.  Get DCRD to return a blockhash in any `GetRawTransactionVerbose` if the transaction has been mined (1 confirmation)
2.  Switch back to a two step process to get the hash with `GetBlockHash` and then the block for that hash as was implemented in the first version of PR #456.
3.  Error check the blockhash and display the Tx without the fees if the blockhash was not valid instead of the white screen of death.
This PR implements the third option since its likely the right solution to have DCRD report a …
=> Fresh coinbase miner fee tx fix

explorer/explorer.go
This is a small fix for #455 to avoid calculations on anything but mainnet.
=> Only run ASR routine on mainnet

Gopkg.lock, stakedb/stakedb.go, stakedb/ticketpool.go, stakedb/ticketpool_test.go, txhelpers/txhelpers.go, txhelpers/txhelpers_test.go
This changes how StakeDatabase gets the live ticket pool and the diffs (in/out) for each block in ConnectBlock.
The `liveTicketCache` in `StakeDatabase` is now a faithful representation of the live ticket pool at the current best block.  So when the live ticket list is needed, it is no longer necessary to use the `stake.Node` (`BestNode.LiveTickets()`).
Add `poolValue int64` to `StakeDatabase`, updating it on connect/disconnect via += / -+ for the pool in/out tickets.
A major optimization in `ConnectBlock` is using the new `ExpiredByBlock` function in dcrd/stake instead of the much more costly `ExistsExpiredTicket` and `ExistsRevokedTicket`.  This requires dcrd PR https://github.com/decred/dcrd/pull/1221.
Improve the process of "Pre-populating live ticket cache..." by prefetching the …
=> accelerate StakeDatabase.ConnectBlock

api/insight/apimiddleware.go, api/insight/apirouter.go, api/insight/apiroutes.go, api/insight/converter.go, api/types/insightapitypes.go, db/dcrpg/insightapi.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/queries.go, middleware/apimiddleware.go
These endpoints are ready for test and merge:
Full comparison list is here:  https://docs.google.com/spreadsheets/d/1WGHezqRG5VY-t4O6cGpZGwsq69IKJ3deEnERaVvQOb4
**[1] Block**
*Comparison*
*Example Output*
```
[
{
"hash": "000000000000000663a4ea037091a5ce844051f0c6d5fd0d0389103b993fc977",
"confirmations": 11083,
"size": 4154,
"height": 235615,
"version": 5,
"merkleroot": "6c360aa257d7485326c1b5e9cad32d9d0f0a28dfa1654cbec3bff04a37bf033a",
"tx": [
"d1414ca25a008dfd6502b64ec77fa625b1f95f73828c975453920993ba4bf044",
"24e3367c225234bda3b4fbe2279e446c39febbf5311bbfbef68a581bf168c6f0",
"d2c249b66b73ed7942f476fb5d5977aadb0ff7c0da59ffc4529f6887a7845b3d",
"1bef2b097b3d81dba57fee9e852df13f7f0fc729fcb772cfabc67c6ce3777413",
"15be0712c0344db0e838f3f098125c0c11d67b6f6ca604995998a48f9dd6a67f", …
```
=> Insight API - Misc cleanup [1], [2], [5], [5.1], [8], [8.1], [8.2], [9.1], [9.2], [9.3], [9.4]

README.md, api/apirouter.go, api/apiroutes.go, api/types/apitypes.go, db/dcrsqlite/apisource.go, middleware/apimiddleware.go, version/version.go
This adds the /txs and /txs/trimmed routes for batch requesting transaction details.  The transaction hashes are transmitted in the http request body as JSON.  The structure is `api/types.Txns`. The request
Content-Type must be "application/json".
The return type for /txs is `[]*types.Tx`.
The return type for /txs/trimmed is `[]*types.TrimmedTx`.
version: bump to 2.0.1
=> api: add /txs route for batch request

db/dcrsqlite/apisource.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/tx.tmpl
This PR will change ticket ETAs to use hours.
Examples:
"Immature, spendable in 28 blocks (2.2 hours remaining)"
"Immature, eligible to vote in 145 blocks (12.0 hours remaining)"
Not "0.37 days remaining"
=> multi: show maturity ETA in hours

cmd/rebuilddb2/rebuilddb2.go, db/dcrpg/pgblockchain.go, db/dcrpg/sync.go
This prevents each connected block from updating the dev fund balance.  The dcrdata app already does this, but rebuilddb2 was not updated.
=> rebuilddb2 batch sync flag

db/dcrsqlite/apisource.go, views/tx.tmpl
(db *wiredDB) GetExplorerTx: set Mature="false" when confirmations==0
tx.tmpl: Unconfirmed tickets and votes read "N/A"  for MATURITY, must be
confirmed to show progress meter.
=> html/tx: unconfirmed tickets/votes have no maturity status

db/dcrsqlite/apisource.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/tx.tmpl
Resolving issue https://github.com/decred/dcrdata/issues/511
Intoduces `(*TxInfo).IsTicket/IsVote`
=> explorer: compute ticket matruity times in lite mode

db/dcrpg/internal/blockstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go
In `StoreBlock`, if `pgb.lastBlock` does not contain the previous block row
ID, look it up in the block_chain table. Add `RetrieveBlockChainDbID` to
get the row id in the block_chain table for the block with a given hash.
=> dcrpg: fix empty prev_hash in block_chain

db/dcrsqlite/sqlite.go
Ensures `tpi.Winners` is an empty array.
Fixes #532
=> dcrsqlite: fix RetrievePoolInfo empty result

cmd/rebuilddb2/rebuilddb2.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sync.go, stakedb/stakedb.go, stakedb/ticketpool.go, stakedb/ticketpool_test.go
This adds some automatic recovery functions.
- Add `stakedb.LoadAndRecover`, which attempts recovery of the `StakeDatabase` and its `TicketPool`.
- `NewStakeDatabase` returns the height where it stopped loading. If there is an error, the height may be passed to `LoadAndRecover`.
- `InsertVin[s]` now has an upsert option (dupcheck=true) to avoid failures requiring recovery procedures.
- Also have dupcheck option with `SetSpendingForFundingOP` / `insertSpendingTxByPrptStmt` and `SetSpendingByVinID`.
- Add `MakeAddressRowInsertStatement` to create the upsert statement if checkup=true;
- `InsertVotes` and `MakeVoteInsertStatement` similarly take checkdups option.
- Fix incorrect parameter numbers in `upsertVoteRow` and `insertVoteRowReturnId`.
- `AdvanceToTip` now returns the last valid diff …
=> stakedb: recovery and robustness with upserts

cmd/rebuilddb2/rebuilddb2.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sync.go, stakedb/stakedb.go, stakedb/ticketpool.go, stakedb/ticketpool_test.go
This adds some automatic recovery functions.
- Add `stakedb.LoadAndRecover`, which attempts recovery of the `StakeDatabase` and its `TicketPool`.
- `NewStakeDatabase` returns the height where it stopped loading. If there is an error, the height may be passed to `LoadAndRecover`.
- `InsertVin[s]` now has an upsert option (dupcheck=true) to avoid failures requiring recovery procedures.
- Also have dupcheck option with `SetSpendingForFundingOP` / `insertSpendingTxByPrptStmt` and `SetSpendingByVinID`.
- Add `MakeAddressRowInsertStatement` to create the upsert statement if checkup=true;
- `InsertVotes` and `MakeVoteInsertStatement` similarly take checkdups option.
- Fix incorrect parameter numbers in `upsertVoteRow` and `insertVoteRowReturnId`.
- `AdvanceToTip` now returns the last valid diff …
=> [2.1] DB recovery and robustness.

db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, version.go
Two fixes and enhancements:
dcrpg: fix empty prev_hash in block_chain
In StoreBlock, if pgb.lastBlock does not contain the previous block row
ID, look it up in the block_chain table. Add RetrieveBlockChainDbID to
get the row id in the block_chain table for the block with a given hash.
dcrpg: improve robustness.
InsertVin[s] now has upsert option (dupcheck=true) to avoid failures
requiring recovery procedures.
Add MakeAddressRowInsertStatement to greate the upsert statement if
checkdups=true;
InsertVotes and MakeVoteInsertStatement similarly take dupCheck option.
Fix incorrect parameter numbers in upsertVoteRow and insertVoteRowReturnId.
=> [2.0] dcrpg: backport block_chain fix and upsert additions

config.go, explorer/explorer.go, main.go
The `no-dev-prefetch` flag does the following:  Disable automatic dev/project fund balance query on new blocks. When true, the query will still be run on-demand (e.g. explorer address page for dev fund), but not automatically after new blocks are connected.
=> [2.0] explorer/main: add no-dev-prefetch option

Gopkg.lock
The Gopkg.lock format has changed slightly again in the latest version of dep.
IMPORTANT: Update `dep` after merging or rebasing on this:
go get -u -v github.com/golang/dep/cmd/dep
=> dep: update lock for dep's new format

cmd/rebuilddb2/rebuilddb2.go, config.go, db/dcrpg/pgblockchain.go, explorer/explorer.go, main.go
Updated version of PR https://github.com/decred/dcrdata/pull/546 for master
explorer/main: add no-dev-prefetch option (#546)  …
The no-dev-prefetch flag does the following:
Disable automatic dev fund balance query on new blocks. When true, the
query will still be run on demand, but not automatically after new
blocks are connected.
dcrpg: respect noDevPrefetch
=> explorer/main: add no-dev-prefetch option

.gitignore, db/dcrsqlite/sqlite.go
Fixes number of issues similar to the one described in the #532
`strings.Split(winners, ";")` is not a correct way to split the `winners` string.
=> dcrsqlite: correctly splits given string into array of strings

views/tx.tmpl
Remove the table and display a nice message if there are no votes in a transaction.
Fixes: https://github.com/decred/dcrdata/issues/442
=> Add message for no votes on a block.

api/insight/apiroutes.go, db/dbtypes/types.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/tables.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/address.tmpl
This PR is based of dcrdata 3.0.0.
- It introduces a new merged view debit page on the addresses history page the list only unique transactions where similar transactions appear.
- It also fixes a bug with the next button on the same page.
=> Consolidated debit view

config.go, main.go
This adds the flag `--sync-and-quit` to the dcrdata executable that will caus dcrdata to sync to the best block and then exit.  It will not start the explorer or API.
=> config: add --sync-and-quit flag to only sync

cmd/rebuilddb2/rebuilddb2.go, db/dbtypes/extraction.go, db/dbtypes/types.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/sync.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go, explorer/explorertypes.go
This PR adds support for tracking blocks and transactions that are in side chains.
For followup PR:
- Modify reorg handling to patch up the IsMainchain values.
=> dcrpg: start proper side chain handling, upgrades

config.go, db/dbtypes/extraction.go
dbtypes: DevSubsidyAddress now returns a non-nil error in special
cases (e.g. testnet2).
When parsing config, check chain params via DevSubsidyAddress to
automatically disable the dev fund prefetch when it would not be
possible to fetch a non-zero balance.
=> config: disable dev balance prefetch with invalid fund

api/apirouter.go, api/apiroutes.go, api/types/apitypes.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, main.go, txhelpers/subsidy.go
This adds .../subsidy paths to the block API endpoints (best, idx, hash), addressing Issue https://github.com/decred/dcrdata/issues/590.
The dcrd RPC:
```
$ dcrctl --notls getblocksubsidy 262307 5
{
"developer": 205399222,
"pos": 616197665,
"pow": 1232395335,
"total": 2053992222
}
```
The new API (any of: /block/262307/subsidy, /block/best/subsidy, or /block/hash/0000000000000000a42c701ea78a6f4a9d21979b820eb8100ab900d01744eebe/subsidy):
```
{
"height": 262307,
"hash": "0000000000000000a42c701ea78a6f4a9d21979b820eb8100ab900d01744eebe",
"work_reward": 1232395335,
"stake_reward": 123239533,
"num_votes": 5,
"stake_reward_total": 616197665,
"project_subsidy": 205399222,
"total": 2053992222
}
```
txhelpers: add RewardsAtBlock
api/types: add BlockSubsidies JSON-tagged type
api: add …
=> api: add block rewards endpoints

explorer/explorer.go, txhelpers/stake.go, txhelpers/stake_test.go
This is partly an example, and partly to ensure we don't break `CalcMeanVotingBlocks`. 
```
=== RUN   TestRewardPeriods
--- PASS: TestRewardPeriods (0.00s)
stake_test.go:68: mainnet expected locked time: 697h40m0s (29.06944444 days)
stake_test.go:68: testnet2 expected locked time: 34h36m0s (1.44166667 days)
stake_test.go:68: simnet expected locked time: 1m34s (0.00108796 days)
```
=> txhelpers/explorer: move and test CalcMeanVotingBlocks

.gitignore, Gopkg.lock, db/dcrsqlite/blocksretrieval_test.go, db/dcrsqlite/dcrsqlite_test.go
This is tier 3 of the #514 
Testing:
- `dcrsqlite/sqlite.go` `DB.RetrieveAllPoolValAndSize()`
- `dcrsqlite/sqlite.go` `DB.RetrieveBlockFeeInfo()`
=> dcrsqlite: test RetrieveAllPoolValAndSize and RetrieveBlockFeeInfo, tier 3

db/agendadb/db.go
When fetching all agendas if opening the db failed, the application still proceeded to use an invalid agendas db connection failed.
https://github.com/decred/dcrdata/issues/587
=> agendadb: Fix unhandled errors while fetching all agendas

main.go
Shows the golang version too on startup:
[INF] DATD: dcrdata version 3.0.0 (Go version go1.11beta3)
=> main: show golang version

db/dcrsqlite/blocksretrieval_test.go
This is tier 2 of the #514 
Testing:
- `dcrsqlite/sqlite.go` `DB.GetBestBlockHash()`
- `dcrsqlite/sqlite.go` `DB.GetBestBlockHeight()`
- `dcrsqlite/sqlite.go` `DB.GetStakeInfoHeight()`
=> dcrsqlite: test GetBestBlockHash, GetBestBlockHeight, GetStakeInfoHeight, tier 2

Gopkg.lock, cmd/rebuilddb/config.go, cmd/rebuilddb2/config.go, config.go, db/agendadb/db.go, explorer/explorer_test.go, explorer/explorerroutes.go, txhelpers/stake_test.go
- Update deps for dcrd, dcrwallet.
- Also update golang.org/x/...
- Remove all reference to params.TestNet2 as it was removed from chaincfg.
- Deprecate netName() in config.go.
- Change explorer.netName to work for any numbered testnet by stripping suffix after "testnet".
- Add tests for explorer.netName.
=> switch to testnet3

api/insight/apiroutes.go, blockdata/blockdata.go, blockdata/chainmonitor.go, db/agendadb/db.go, db/dcrpg/internal/txstmts.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, explorer/explorer.go, main.go, run_tests.sh, stakedb/ticketpool.go
`defer`s were missing in two sqlite functions, causing empty critical sections.
Any errors from `BlockDataSaver.Store` in `blockdata`'s `BlockConnectedHandler` were unhanded.  Now it logs the error and which saver it came from.
Fixes lots of misspelings.
=> missing defer in sqlite, lots of linting

blockdata/chainmonitor.go, db/dcrpg/chainmonitor.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go, db/dcrsqlite/apisource.go, main.go, notification/ntfnchans.go, notification/ntfnhandlers.go, stakedb/stakedb.go
This builds on the sidechain support in PR https://github.com/decred/dcrdata/pull/552
It adds a `ChainMonitor` to `dcrpg` and implements `switchToSideChain`.
* add `(*ChainDB).TipToSideChain`, used by `switchToSideChain` to move blocks from mainchain to sidechain, updating all related tables.
* add `(*ChainDB).SetVinsMainchainByBlock`, used by `TipToSideChain`, and add other mainchain queries for txns, votes, tickets, and addresses tables.
* notification: create block connected and reorg channels for dcrpg
* embed `ChainDB` in `ChainDBRPC` instead of having named field
* add `ChainDB.bestBlockHash`  to avoid unnecessary RPC
* Upgrade `tickets` table with `is_mainchain` column, forgotten in last PR.  This bumps the db scheme from 3.3.0 --> 3.4.0.
* Added new index `uix_votes_block_hash` to …
=> dcrpg: reorg handling

views/address.tmpl
Issue Fixed.
**Before:**
**After:**
=> Display the tiny qr code thumbnail by default

db/dbtypes/types.go, explorer/explorertypes.go, views/address.tmpl
Change `"merged debit"` to `"merged_debit"` so we don't get `?txntype=merged%20debit` in the url.
=> keep spaces out of the url

views/agendas.tmpl
This displays a ""No agendas found for {{NetName}}" message when no agenda exists on network. {{NetName}} is one of "Mainnet, Testnet, Simnet" depending on the current network.
This fixes #588
=> Show proper message when no agendas

README.md
Quote:
`dep ensure -vendor-only` fetches project dependencies, without making changes in manifest files `Gopkg.toml` and `Gopkg.lock`.
Call `dep ensure` to update project dependencies when introduce new imports.
For guides and reference materials about `dep`, see [the documentation](https://golang.github.io/dep).
The following FAQ explains [the difference between `Gopkg.toml` and `Gopkg.lock` files](https://github.com/golang/dep/blob/master/docs/FAQ.md#what-is-the-difference-between-gopkgtoml-the-manifest-and-gopkglock-the-lock).
=> Update README.md on dep ensure -vendor-only

db/dcrpg/internal/blockstmts.go, db/dcrpg/queries.go, db/dcrpg/upgrades.go
The `HashDB` function required the `is_mainchain` column, but it did not
yet exist at the time of upgrade.  This was added to the query after
the upgrade was initially tested.
=> dcrpg: fix the 3.2.0 -> 3.3.0 upgrade

README.md
Remove github releaes badge (only tags matter).
Update repository overview with new folders and better descriptions.
Update required dcrd to 1.3 (testnet3).
Clean up and clarify Upgrading Instructions.
Add more about PostgreSQL tuning.
Add System hardware requirements section.
Update JSON API tables with new endpoints (block subsidy, tx vinfo,
tx hex, tx decoded, address totals).
=> README: update for 3.0

db/dcrpg/upgrades.go
A missing fallthrough statement ad the end of the 3.4.1 -> 3.5.0 upgrade
broke upgrading to 3.5.1 from any version but 3.5.0.
=> dcrpg: fix upgrade to 3.5.1 from <3.5.0

Gopkg.lock, Gopkg.toml, README.md, config.go, config_test.go, go.mod, go.sum
* Adds a new packgae env that allows us to declare env variables
as a struct tag.
* previously in order to set config data one had to use a config
file or set a bunch of command line arguments.
* This adds the ability to use environment variables
which makes this more compatabile with 12 factor app design,
in addition to docker and docker-compose.
* Without this users are forced to invoke dcrdata in a non dynamic
way because config files and command line args must be hard coded.
* Adds simple config test file as no testing existed before
=> Adds ability to use environment variables as configuration

api/insight/apirouter.go, api/insight/apiroutes.go
This PR closes out the last remaining Insight API endpoint - `sync status`.  I have also done a little cleanup of unused functions left over from previous versions of Insight API implementation.
This PR should allow us to close #638,  #400 and #260.
finished status:
```
{
"status": "finished",
"blockChainHeight": 269385,
"syncPercentage": 100,
"height": 269385,
"error": null,
"type": "from RPC calls"
}
```
syncing status:
```
{
"status": "syncing",
"blockChainHeight": 269388,
"syncPercentage": 99,
"height": 269385,
"error": null,
"type": "from RPC calls"
}
```
Reference bitpay insight URL endpoint:
```
{
"status": "finished",
"blockChainHeight": 538770,
"syncPercentage": 100,
"height": 538770,
"error": null,
"type": "bitcore node"
}
```
reference existing insight api at mainnet.decred.org …
=> Insight API sync status and cleanup

README.md
main: updates the build instructions and dependency resolution tooling for golang 1.11.
Adds a new section for building with a docker container and cross compiling.
=> Updates README for golang 1.11

explorer/explorer.go, explorer/explorerroutes.go, explorer/websockethandlers.go
The home page was requesting a full read/write lock when it only needed a read lock.  Similarly, `RootWebsocket` was requesting unneeded full
locks in both the send and receive loops, which caused a deadlock. This resolves the issues.
Several accesses to `explorerUI.ExtraInfo` were not guarded with a read lock.  These data races are also fixed.
This also adds `(*explorerUI).Height()` for thread-safe access to `NewBlockData.Height`.
Remove several pointless closures.
=> explorer: address multiple deadlocks and data races

explorer/explorer.go, explorer/explorerroutes.go, explorer/websockethandlers.go
Backport of https://github.com/decred/dcrdata/pull/659 for 3.0.
Home page was requesting a full read-write lock when it only needed a
read lock.  Similarly, RootWebsocket was requesting full unneeded full
locks in both the send and receive loops, which caused a deadlock.
Add (*explorerUI).Height()  for thread-safe access to
NewBlockData.Height.
Remove several pointless closures.
=> [3.0] explorer: address multiple deadlocks and data races

db/dbtypes/types.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/explorer.go, explorer/explorerroutes.go, public/css/charts.css, public/js/controllers/address.js, views/address.tmpl
**Summary of Tasks Done**
-  Either `month`, `week`, `day` or `all blocks` interval can be selected. i.e. `month` is only select if the oldest transaction belonging to a given address was processed more than a month ago from now.  The same also happens to the rest intervals.
- Also if the total transactions count is less than 20, interval selected defaults to `all`.
- This helps in dealing with the network latency issues since the payload now requested by default will be smaller and more meaningful to the user.
__for Project Fund Address, it will always default to `month` interval__
=> Fix performance issues on address page

explorer/explorer.go, explorer/explorerroutes.go, public/css/main.css, views/block.tmpl, views/explorer.tmpl
Create invalidated-tx CSS style to gray out and change background color
of regular transaction table data, including the coinbase.
Resolves https://github.com/decred/dcrdata/issues/295.
=> views: style invalidated transactions on block page.

db/dcrpg/internal/txstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/templates.go, public/css/main.css, views/tx.tmpl
This adds a new query to get details for all blocks containing a specified transaction. The details are block index, height, hash, is_valid, and is_mainchain.  `ChainDB.TransactionBlocks` gets these data.
On the transaction page, use the new `TransactionBlocks` function in full mode to retrieve and display a list of blocks (on the transaction view) that contain the transaction.  When a transaction is found in multiple blocks, list them all with unambiguous links by hash.  Also pass the transaction index via `?ind=`
URL parameter so that we can use it on the block page to highlight the transaction (not done in this work). Create "grayed out" colors with a `"grayed"` class for `<body>` and `<a>` elements.  Also define these for dark/night mode. Also simplify the signature for several …
=> Transaction block list

db/dcrpg/pgblockchain.go, db/dcrsqlite/apisource.go
In both dcrpg (for full mode) and dcrsqlite (for lite mode), this
responds to address history requests without error when there are no
known transactions for a given address but no other error.
For the API, this means returning a non-nil *apitypes.Address with the
Transactions field set to a non-nil zero-length slice.  The slice must
be non-nil so that when marshalled to JSON, "address_transactions"
shows as [] instead of null.
So instead of code 422 and "Unprocessible Entity", the API  now responds
with code 200 and a valid JSON struct like:
```json
{
"address": "TsmSGofXA4hqx9XRNgWoRZtNMXXshhMLByA",
"address_transactions": []
}
```
This resolves issue https://github.com/decred/dcrdata/issues/662.
=> dcrpg/dcrsqlite: no transactions found for address is not an error

api/apirouter.go, api/apiroutes.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, explorer/websockethandlers.go, public/js/controllers/ticketpool.js
This implements a cache for the ticket pool data at the dcrpg package level.  The cache automatically updates on the first request when the data is stale.  Requests made when an update is already running are served with stale data.
So that the APIs and the explorer can easily leverage the cache but not even know about it, the cache should live entirely within `ChainDB` in the `dcrpg` package.  Also, consumers only need use `TicketPoolVisualization`, not the cache query and update functions. `ticketPoolDataCache` lives in pgblockchain.go (dcrpg) now, and it is managed entirely by `ChainDB`.
Modify tickets pool by date API response to include height of the data. Also pass `ChartsHeight` to the /ticketpool page template, for future use.
The `ticketPoolVisualization` function now ensures that …
=> cache the ticket pool data to avoid unnecessary DB queries

.travis.yml, run_tests.sh, testutil/tempfiles.go
This limits Travis to testing Go 1.11 only, and uses go modules exclusively, no dep.
GO111MODULE=on is set, and the vendor folder is not populated with dep or go mod vendor.  As such, linters are disabled until such time that the linter authors can figure out how to make them work with modules.
Also fix some testing issues:
- stakedb (ticketpool) test data in wrong folder.
- Missing formatting directives in testutil functions.
=> limit CI to go1.11 and fix some tests

db/dcrpg/pgblockchain.go, run_tests.sh, version/version.go
This fixes a concurrent map write on the dev balance.
Version is bumped to 2.1.3.
CI now ignores changes in dep lock.
=> [2.1] guard concurrent maps write

db/dcrpg/pgblockchain.go
This addresses an unguarded map write on the project fund balance map.
=> dcrpg: fix concurrent map write

db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go
The new block handler neglected to update valid_mainchain=false on the
previous block.  This change adds UpdateLastAddressesValid, which sets
valid_mainchain for the regular transactions in a given block.  Call it
from the "if !lastIsValid" block of (*ChainDB).StoreBlock, where the
previous vins and transactoins were correctly being invalidated.
Modify RetrieveTxnsVinsVoutsByBlock so the caller may specify if only
regular transactions' vins/vouts are needed, or all transaction types.
The rows of the addresses table that should have valid_mainchain=false
are identified with SelectAddressesGloballyInvalid.  The query to
correct the valid_mainchain values is UpdateAddressesGloballyInvalid.
These are called from a table version upgrade (3.5.2 -> 3.5.3).
=> dcrpg: valid_mainchain addresses table patch

api/insight/socket.io.go, api/insight/socket.io_test.go
Define a new type for a vout array element, and implement `json.Marshaler` using a temporay map with one key-value pair.
Clean up socket.io.go, embedding the address mutex into a new type, `roomSubscriptionCounter`.
Resolves issue https://github.com/decred/dcrdata/issues/682
=> insight: fix marshal of vout values in the tx message

db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, txhelpers/txhelpers.go, views/tx.tmpl
If a transaction is not known to dcrd, it is because it has been orphaned by a reorg, invalidated via stakeholder disapproval, or both. This change will attempt to load details of the transaction from the
dcrpg database, which may have decoded and recorded the transaction.
Add a message to the transaction page when the transaction is not found in any valid and mainchain block:
Tasks:
Future: See if it is easier, more efficient, or feasible to pull the entire block from dcrd instead of checking the database.
=> Invalidated transaction display

db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go
This fixes the tests in pgblockchain_test.go (started with `-tags mainnettest`, and using a live postgres server.
`SelectSpendingTxByPrevOut` should have been returning `tx_tree` also.
`SelectPkScriptByID` should also scan `version` with the `pkScript`.
`RetrieveVinByID` needed to scan `txType`.
=> [3.0]  dcrpg: backported bugfixes

explorer/explorerroutes.go, public/js/controllers/address.js, views/address.tmpl
This PR will allow the address page to be visible for an address with only unconfirmed transactions.  It will also insure the charts do not stall on loading and display a message that there are no CONFIRMED transactions to display (and thus no charts).
I could not find any open issues related to this.
=> Show address page for address with ONLY unconfirmed Tx

db/dcrpg/sync.go
If SyncChainDB fails to get a block from dcrd, the sync will hang
waiting to send the result back ot main, while dcrsqlite waits for the
block that it can't get.  This adds error logging in this case so it
is clear why caused dcrpg to end sync early, and that it is OK to
interrupt.
=> dcrpg: error logging for (*ChainDB).SyncChainDB

public/js/controllers/address.js
Uses LoDash rather than an array length to test for presence of chart data.  Fixes PR #680
=> Properly test object validity on null chart data

db/dbtypes/types.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/queries.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go, db/dcrsqlite/apisource.go, explorer/explorermiddleware.go, explorer/explorerroutes.go, explorer/explorertypes.go, main.go, public/css/main.css, views/address.tmpl, views/tx.tmpl
This PR is for issue #642.  There are three potential aspects to this issue - I have finished only the first one:
1.  This version will highlight the transactions on the page.  The matched transaction Vin/out is not easily available in the address page raw data and thus right now all we are doing is highlighting the transaction, but if there are multiple identical transactions they all get highlighted.
See example gif below. (address: DsiJmwqFbsCEc1H3HF8UeRjoqJtKt9ZFRKw)
2.  I can update the address page to also pull the matched tx vin/vout index but that will likely require changes to the query and/or a secondary query.  I don't know that its that critical to be able to isolate each vin/vout index.
3.  @chappjc mentions also adding a url parameter to the source/spent links to allow the …
=> Address page tx highlighting

main.go
This PR addresses startup issues notably on windows that will corrupt the badger db.  Addresses issue #645 
1.  Ctrl-C handler is moved earlier in main.go to insure its operational during stakedb load
2.  Sprinkles in additional channel selects to allow exiting startup at safe times.
3.  Modifies Ctrl-C handling to insure additional Ctrl-C's after the first one do not force an abrupt exit.
Testing shows this eliminates corruption due to Ctrl-C on startup that I saw previously.  Examples of shutdown are shown below (4 ctrl-c's pressed in each case):
```
2018-09-21 12:24:03.281 [INF] RPCC: Established connection to RPC server localhost:9109
2018-09-21 12:24:03.283 [INF] DATD: Connected to dcrd (JSON-RPC API v3.3.0) on MainNet
2018-09-21 12:24:03.300 [INF] SKDB: Loading ticket pool DB. This …
```
=> Initial ctrl-c fixes

db/dcrpg/insightapi.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go
This documents most of the query functions in queries.go, and structures the file to keep functions logically organized by table.  The exceptions are some maintenance functions that are moved to the top, and most of the Update functions that are grouped at the bottom since updates generally happen in response to the same events (stake invalidation or reorganization).
This also renames `RetrieveAddressTxnOutputWithTransaction` to `RetrieveAddressUTXOs`, and `RetrieveAllRevokesDbIDHashHeight` to `RetrieveAllRevokes` for clarity and readability.  The variable `totalMergedSpent` had a misleading name since it was a count, not an amount, so that was renamed to `numMergedSpent`, and the amount/value variables were renamed from `total*` to `amt*`.
=> dcrpg: document and reorganize query functions

README.md
Have listed endpoints for Insight API, as documented [in Issue #400](https://github.com/decred/dcrdata/issues/400) ( Closes #694 ).
Changes:
- Adds table with Insight API endpoints
- Puts 'Insight API' and 'dcrd API' as subheadings under new heading 'APIs'
- Tweaks text introducing APIs
I could have worked on this further, but wanted to put what I have out for review first. Also, here are  a few Qs I had as an imaginary user:
- Do we want to provide guidance on which API to use? Is one being depricated eventually (this is often implied when a new API is added)? Is one API better than another for a particular use case?
- Is the Insight API still experimental? Remove (EXPERIMENTAL) qualifier?
- Do we want to document the datatypes, as is done with dcrdata in the 'Type' column? 
- We say …
=> Adds Insight API endpoints to README

api/apiroutes.go, api/types/apitypes.go
This resolves issue https://github.com/decred/dcrdata/issues/441.
This PR modifies the following API endpoints to set output spend info
when the URL query ?spends=true is provided: /api/tx, /api/tx/decoded,
and /api/txs.
Add `(*c.appContext).setOutputSpends` to retrieve any known spending
transaction information for the outputs of a transaction.
Add wrappers `setTxSpends` and `setTrimmedTxSpends` to perform
lookup of spending info for `apitypes.Tx` and `apitypes.TrimmedTx`.
Update /api/tx, /api/tx/decoded, and /api/txs HTTP handlers to get
the spending info if requested on with the URL query param, spends.
Note: This lookup only functions in full mode, not lite mode.
Add `Spend` field to `apitypes.Vout` type.
The `Vout.Spend` field is of type `*TxInputID`, a new type that specifies a …
=> api: transaction output spent status

db/dcrpg/internal/addrstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go
This creates the addresses' table block_time_index *with sorting* on the
`block_time` column in order to avoid a sort when querying for rows by a
particular address.
Add `ReindexAddressesBlockTime`, to simplify dropping and re-creating the
block_time_index with this sorting.  Implement the upgrade from dcrpg
3.5.4 to 3.5.5 for this block_time reindexing.
This is motivated in part by the slowness of such queries with large numbers
of rows in the addresses table, such as
DshMNsvETDWpVoCe1re9NTAChiJagzsFV7J, which has over 116,746
transactions some of which have hundreds of inputs.
@papacarp Proposed the index sorting solution implemented here.
The reindexing is fairly quick:
```
15:01:38.196 [INF] PSQL: Reindex the addresses table on block_time
15:01:38.196 [INF] PSQL: Reindexing addresses …
```
=> dcrpg: addresses table query optimization with block_time_index sorting

explorer/templates.go
removed redundant time spec in agenda page by updating the `TimeConversion` template function to return a string with the format, `2006-01-02 15:04:05 MST`
https://github.com/decred/dcrdata/issues/652
=> agendas page: redundant time spec #652

views/extras.tmpl, views/tx.tmpl
This is a fix for https://github.com/decred/dcrdata/issues/637
Modified the `updateBlockData` function in the extras.tmpl file to append the parenthesis and the text 'confirmations' during WebSocket update.
the span with `data-confirmation-block-height` attribute should no longer the wrapped in parenthesis as the function will provide the full content during an update
=> 'confirms' formatting on websocket update in views/transaction

config.go, db/dcrpg/sync.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sync.go, main.go
Fix 1: Rewinding of stakedb never goes below 0, do not use `lastBlockPG`,
which will be -1 when auxDB is empty. This addresses:
`"failed to rewind stakedb: got 0, expecting -1"`
Fix 2: Prevent the startHeight of the block scan in `(*wiredDB).resyncDB`
from beginning beyond `fetchToHeight`, as this is the height at which the
`MasterBlockGetter` in `(*ChainDB).SyncChainDB` begins notifying of new
blocks it fetches via RPC, and begins waiting for blocks to be connected
in stakedb in `(*wiredDB).resyncDB`.
Note that the stakedb rewind in main ensures stakedb is not beyond the
height of `auxDB` (a `ChainDB`).
Thoroughly document semantics of `fetchToHeight` and the relationship of
`BlockGetter` in `baseDB` and `MasterBlockGetter` in `auxDB`.
Add an early loop continue in `(*wiredDB).resyncDB` …
=> fix stakedb rewind error on startup

db/dcrpg/indexing.go
Indexing subtitle notifications should be sent before the actual indexing starts. Currently, they are sent after indexing ends, which makes one not know what is happening in the background when the first indexing is running.
=> Display indexing subtitle notification before it starts

api/types/apitypes.go, blockdata/blockdata.go, blockdata/datasaver.go, cmd/scanblocks/scanblocks.go, db/dbtypes/types.go, db/dcrpg/insightapi.go, db/dcrpg/pgblockchain.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, db/dcrsqlite/sync.go, explorer/explorer.go, main.go, mempool/mempool.go, rpcutils/rpcclient.go, rpcutils/rpcclient_online_test.go, rpcutils/rpcclient_test.go
This adds the ability to get all known side chains from dcrd and import all side chain blocks into the aux (dcrpg) database.
This resolves issue https://github.com/decred/dcrdata/issues/338.
For a follow-up PR:  Do the check and import periodically *while running* so that new forks that were not reorganized may be added without having to restart dcrdata.
=> Full side chain import from dcrd on startup

main.go
Register for new blocks, new transactions and new winning tickets notifications before monitors start immediately after blockchain sync is complete.
Currently the registration is happening when the system is exiting.
=> Register for dcrd notifications before waiting for monitors to exit

explorer/explorerroutes.go, explorer/explorertypes.go, views/parameters.tmpl
Displayed MaximumBlockSizes in the view to fix https://github.com/decred/dcrdata/issues/678
=> show MaximumBlockSizes parameter on the /parameters page

explorer/explorerroutes.go
For the API endpoints the status 503 (Service Temporarily Unavailable)  should be used tell the user to resend the request later when the sync is complete.
=> Change the API return status code from 202 to 503

db/dcrpg/queries.go
When importing side chain blocks, we do not have the "validators" list,
which indicates which votes are expected in the block, so no
missed votes are identified.  However, InsertVotes was checking to
ensure that the number of misses + votes is 5.  Disable this check
when the validators slice is empty (importing side chain block).
=> dcrpg: fix panic while importing side chain block with missed vote

blockdata/blockdata.go, db/dcrpg/pgblockchain.go, db/dcrsqlite/apisource.go
Certain conditions are presently expected when importing a side chain
block.  Namely, there will be no ticket pool info, and the parent of the
side chain root block will be main chain.  Do not log these cases.
This also silences an expected condition in a wiredDB query:
With empty block tables, the best block height will be returned as -1.
In this case, return from GetBestBlockSummary early before trying
and failing to get the block summary for this non-existent block. This
change is meant to further clean up log messages when there is no
real error.
=> reduce messages for expected events on side chain block import

config.go, db/dcrpg/internal/addrstmts.go, main.go
The import of side chains from dcrd into dcrdata's dcrpg
backend has known issues, and it should be optional
functionality until it is more well tested. This adds a switch
to explicitly enable side chain imports.  The default is to
not import side chains (--import-side-chains=false).
=> config: add import-side-chains flag

README.md, config.go
Several env tags were accidentally removed; this restores them.
Also add env tags `DCRDATA_AGENDA_DB_FILE_NAME` and
`DCRDATA_IMPORT_SIDE_CHAINS`.
@logicminds 
Note: not to be backported to 3.0.x
=> config: restore env tags in config struct

db/dcrsqlite/sqlite.go, db/dcrsqlite/sync.go, main.go
This initially was to address a recent sync issue, but it now just contains a few minor fixes and some clean up.
In (*wiredDB).resyncDB, the following heights are kept updated: stakeDBHeight, summaryHeight, and stakeInfoHeight. 
The ticket pool info height check is now done even when found in cache.
The `updateStatusChan` was being sent the same value repeatedly.  Changed to i, the loop iteration.
Move the chain height check to the last operation in the loop.
After the sync loop, call DBHeights one more time and display final heights, for debugging.
Increase ticket pool cache size from 20 to 200 blocks over blocks behind.
In the secondary calls to getSyncd, auxDBHeight was not being updated.  Update it so fetchToHeight = auxDBHeight + 1 is correct even if there is a third call to …
=> Sync fixes

db/dcrpg/internal/blockstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/explorer.go
The pool status update for unspent expired and missed tickets updated
rows by matching hash.  However, the row IDs (primary keys) of these
ticket hashes are available in the TicketTxnIDGetter, the
unspentTicketCache of ChainDB.  This change uses the cache (without
expiring the entries since they may be needed if the tickets are
eventually spent via revocation) so the update does not require scanning
on the (unindexed) hash column.
The above optimization is noticable as there is no longer a significant
slowdown of the block processing further in the process.
The other optimization relates to the new check in UpdateLastBlock
that ensures the previous block is on the same chain.  This edit
replaces BlockStatus with the new BlockFlags query that does not involve
a join but only provides …
=> dcrpg: major optimization with pool status update

api/apiroutes.go, cmd/rebuilddb2/rebuilddb2.go, db/dcrpg/chainmonitor.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/sync.go, db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, explorer/mempool.go, main.go, rpcutils/rpcclient.go, stakedb/stakedb.go
These changes focus on dcrpg and correcting the side chain import process.  However, there is a considerable amount of added documentation, and tangential refactoring that supports these changes.
An key change is support for 3 different insert statements in several tables:
1. Insert without checking for constraint conflicts.  This can result in a constraint violation error, and is intended to be used during initial sync (before creation of the unique indexes).
2. Upsert (insert or update existing).  If there is a constraint conflict, this is considered an existing record, which will be updated with the upsert statement.  The updates columns are generally sidechain/valid flags, or other data that may change for side chains.
3. Insert or do nothing on conflict.  If there is no constraint …
=> side chain import fixes and block sync/store refactoring

README.md
Contribution section branching instructions 'git branch -b' -> 'git checkout -b'. First is not valid.
=> README updated. 

public/js/controllers/address.js
bug in address.js cause the loading animation to hang when chart isn't initialized
=> fix chart zoom for uninitialized charts

explorer/templates.go, views/explorer.tmpl, views/windows.tmpl
Formats the Tickets Price Windows list view to have:
- All columns with numerals and Age to be right aligned
- Fixes typo in the ticket price windows description.
- Add a thousand comma seperator on all aggregate values
#763
=> Format the ticketprice windows view

explorer/explorerroutes.go
Mempool spending transactions on `explorer.AddressPage` are now checked against previous address funding transactions. 
This is a partial solution to #603. @ademuanthony, I don't think this conflicts with #766. 
This populates the appropriate `AddressTx.MatchedTx` and `AddressTx.MatchedTxIndex` when a match is found between a spending mempool transaction and a previously funding stored transaction that matches it. This solves the "N/A" issues in #603 in the "Credit DRC" column
=> Mempool spending txs checked against confirmed txs on address page

views/block.tmpl, views/explorer.tmpl, views/home.tmpl, views/mempool.tmpl, views/windows.tmpl
Minor change that renames revocations to revokes in the front end.
Since our tables can have a lot of columns and space can be at a premium, we should always choose the shorter version of a word if it's just as clear as the longer version. This helps with using that horizontal space efficiently.
I think it's best to be consistent with the choice of words so I've renamed it in all places exposed to the end user.
=> rename revocations to revokes

db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, explorer/templates.go, public/css/main.css, public/js/controllers/main.js, views/extras.tmpl
Possible solution for #399. This is a persistent block time counter in the footer. The text comes red when the time is longer than my somewhat arbitrarily defined 8*blocktime = 40 minutes. 
It is not ready, but I need some advice. Right now, I don't see a straightforward way of getting basic block information into the footer on every page, but I might be missing something. There is no welcome message from the websocket with basic block info. And the page data struct used by `templates` is different for every page, so if I wanted to grab it there, I would have to add it to every page's handler in `explorerroutes`, I think. Is that the right approach? Is the basic best block information available somewhere that I'm not seeing?
=> Block time counter in the footer

db/dcrpg/internal/addrstmts.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, explorer/explorertypes.go, views/address.tmpl
Resolution of issue https://github.com/decred/dcrdata/issues/741
Added `TxType` to the `AddressTx` struct, set it for both lite and full mode and displayed it in the on the tx table in the address page.
=> Show Tx Type in the address page's tx table

explorer/explorerroutes.go, explorer/templates.go, public/css/main.css, views/extras.tmpl, views/tx.tmpl
Resolves #309
There is a related issue with the confirmations counter at the top that I didn't touch because is looks like it's being worked on. see https://github.com/decred/dcrdata/pull/766#issuecomment-433546786
The only difference between a confirmed transaction's /tx page and a mempool /tx page which is confirmed after page/turbolinks load is that the "Pool Status"  is not displayed after a mempool tx is confirmed. 
@gozart1 I put  the JS in the `updateBlockData` websocket callback. I wonder if we could build a little signal system for block data callbacks, ala
```
var blockCallbacks = {}
function registerBlockCallback(key, f){
blockCallbacks[key] = f;
}
function signalBlock(block){
for(key in blockCallbacks){
blockCallbacks[key](block);
}
}
...
// In createWebSocket()
var …
```
=> Mempool transactions on /tx update (mostly) correctly now

db/dbtypes/types.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/explorer.go, explorer/explorerroutes.go, public/js/controllers/address.js, views/address.tmpl
Bug https://github.com/decred/dcrdata/issues/656 happens when when a dataset with only one record is plotted. The charts button will always be disabled by default if the current address has only one or no transaction.
"Zoom" and "Group By" buttons that are likely to plot a graph with one record only are also disabled by default.
=> Disable buttons that plot a chart with one record.

api/types/apitypes.go, db/dcrsqlite/apisource.go
For #802.
Vout hex fields populated in api calls for decoded raw transaction info.
=> Hex field added to apitypes.ScriptPubKey. 

api/apiroutes.go, api/insight/apiroutes.go, api/types/apitypes.go
As per #800. 
Makes no changes yet to `/insight/api/status`, which already has a boolean `testnet` attribute.
=> Added network name to /api/status

explorer/explorerroutes.go, explorer/explorertypes.go, explorer/templates.go, public/css/main.css, public/css/nexthome.css, views/extras.tmpl, views/home.tmpl, views/tx.tmpl
See #241
This makes some changes to the table layout on the transactions page. The abridged/elided text is created using the `template.FuncMap`, so it can be used on any other page as well.
=> Elided text, vout/vin index, and table-layout: auto on tx page tables.

explorer/explorerroutes.go, public/js/controllers/address.js, public/js/controllers/charts.js, views/address.tmpl, views/charts.tmpl
Add Hash tag urls to each view of the /address page
- `/address/{{address}}#list-view` - Default view - List the address history transactions
- `/address/{{address}}#types` - Displays Transactions Types Chart
- `/address/{{address}}#amountflow`- Displays Send and Receive Chart
- `/address/{{address}}#unspent` - Displays Cumulative Total Unspent Chart 
Fixes a bug that results to no chart display on `/charts` if the wrong chart is fetched with a hashtag.
e.g. `/charts#hjgdjadbnmabcnfbcuj` defaults to `/charts#ticket-price`
=> History charts urls

public/css/main.css, views/home.tmpl
This fixes the misalignment of the amounts and the labels in the
home page's chain state table.  The amount was too high.
This adds the align-baseline-rows class, specifying baseline vertical
alignment for tr elements in a table. However, the class is not used
since not all rows require the same valign.
Before:
After:
While here, fix the disappearing space on websocket update of pool size by
moving the `&nbsp;` outside of the element that gets changed on websocket
update, and joining the following line.
=> amount alignment fixes in chain state table

public/css/main.css
When the `trailing-zeros` class is used with the `decimal` class, which adds
`margin-left: -2px;`, the zeros overlap with the other `decimal` digits to
the left. This overrides `margin-left` for elements with both classes.
Before:
After:
=> css: trailing zeros should not have negative margin

version/version.go
Now that 3.1 is branched off, begin the 3.2 dev cycle.  By default, builds will now be versioned as `v3.2.0-pre+dev`.
=> begin 3.2 dev cycle

public/js/controllers/address.js
The Group By buttons could change the active button because of an inaccurate class name comparing used to trigger state change.
=> Fix the group by chart buttons

db/dcrpg/queries.go
If there are no addresses, the Addresses should be nil or length
zero. However, strings.Split will return [""] if addresses is "".
If that is the case, leave it as a nil slice.
=> dcrpg: pkScript addresses slice should be zero length when no addresses

explorer/explorerroutes.go, explorer/templates.go, explorer/templates_test.go
The `hashStart` and `hashEnd` template functions must work with any length
input hash. This modifies these functions to work when the default indexing would
read outside the slice.
Add tests for `hashStart` and `hashEnd` that ensure they work with
different hash lengths, and that they work together to split the hash
without losing or repeating any characters.
While here, make `explorer.netName` work with a `nil` pointer input,
returning `"invalid"` as the network name instead of panicking.
=> explorer: fix and test hashStart and hashEnd tmpl functions

explorer/explorer.go, explorer/explorermiddleware.go, explorer/explorerroutes.go
Resolve [Issue 746](https://github.com/decred/dcrdata/issues/746)
Extended the search page to search for block and address in the chaindb if the specified block height index or hash is not found in the sqlite db and the app is running the full mode.
Transaction uses rpc and so was not altered as that should cover all cases in both full and lite mode
=> Extended search to check aux DB for blocks

api/apiroutes.go, api/insight/apiroutes.go, api/insight/converter.go, api/types/insightapitypes.go, config.go, config_test.go, db/dbtypes/types.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/sync.go, db/dcrpg/upgrades.go, explorer/explorer.go, explorer/explorermiddleware.go, explorer/explorerroutes.go, explorer/explorertypes.go, explorer/websockethandlers.go, main.go, public/js/controllers/address.js
This builds on the cancelable context added in PR https://github.com/decred/dcrdata/pull/761 by creating a configurable query timeout.
The timeout is set with `-T/--pgtimeout`, and is in seconds (`float64`).  The default is 1 day (effectively no timeout).
This adds `replaceCancelError` to recognize the standard postgres error message for a user-cancelled statement, and replace the message with a more user friendly message.
The error value returned by Retrieve* functions that use a context are now filtered in the wrapping functions with `replaceCancelError`.
Several functions in api/insight now have an error returned.
Lots of linting.
This also fixes a bug in the transaction page handler when the aux DB is used to get an orphaned transaction.  The inputs were incorrect previously.  Now …
=> add a timeout context to the pg DB

blockdata/chainmonitor.go, db/dcrpg/chainmonitor.go, db/dcrsqlite/apisource.go, db/dcrsqlite/chainmonitor.go, main.go, notification/ntfnchans.go, notification/ntfnhandlers.go, rpcutils/rpcclient.go, rpcutils/rpcclient_online_test.go, rpcutils/rpcclient_test.go, stakedb/chainmonitor.go, txhelpers/txhelpers.go
Resolving https://github.com/decred/dcrdata/issues/823
There is no longer a need for `BlockConnectedHandler` in dcrpg and dcrsqlite, so it is removed.  The goroutines are no longer started of course, and the synchronous `collectionQueue` now includes only `sdbChainMonitor.BlockConnectedSync` and `wsChainMonitor.BlockConnectedSync` (the synchronous collection and storage functions for the stakedb and blockdata packages.).
In short, the roles of each data saver's `ReorgHandler` are:
1. blockdata: Collect and store in the special reorgDataSavers the data for just the new chain tip block.  This is presently used to update the explorer UI.
2. stakedb: Disconnect the old chain blocks from the StakeDatabase, then connect the new chain blocks.
3. dcrsqlite: Collect and store data for the new …
=> Work with the new dcrd reorg ntfn sequence

cmd/rebuilddb2/rebuilddb2.go, db/dbtypes/conversion.go, db/dbtypes/types.go, db/dcrpg/chainmonitor.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/sync.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go, go.mod, go.sum, main.go, public/js/controllers/charts_controller.js, rpcutils/blockgate.go, rpcutils/rpcclient.go, views/charts.tmpl
Resolves #744 and #723.
This PR performs a PostgreSQL DB upgrade, adding a `TEXT` column, `chainwork`. Relevant block insertion routines are updated to grab the [newly available chainwork value](https://github.com/decred/dcrd/pull/1498) from dcrd.  Having chainwork also enables quick calculation of network hashrate data. A network hashrate chart and "total work" chart have been added to `/charts`.
=> Chainwork DB upgrade. Hashrate and Chainwork charts. 

api/apirouter.go, api/apiroutes.go, api/types/apitypes.go, blockdata/blockdata.go, blockmemdb.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, db/dcrsqlite/sync.go, main.go
For #747
The solution got a little bigger than I expected. Let me know if you want anything changed. The database went from 250 to 430 MB, which is more than I would have expected for essentially adding 3 columns in total. Maybe there's some optimization I'm missing. 
I did not duplicate the `is_mainchain` and `is_valid` columns on the stake table, but that means that a few queries required some `JOIN`s with the block summary table.
=> SQLite structure and routines updated for orphaned blocks

views/extras.tmpl
The footer elements did not get jsonly removed.
Also, put the removeClass in a location without
data-turbolinks-eval="false".
=> [3.1] jsonly removeClass in footer

public/js/services/keyboard_navigation_service.js, public/js/vendor/mousetrap-pause.js, public/js/vendor/mousetrap-pause.min.js
Resolving the following issue:
```
app.bundle.js:1 Uncaught TypeError: l.a.unpause is not a function
at Object.<anonymous> (app.bundle.js:1)
at d (app.bundle.js:1)
at Module.<anonymous> (app.bundle.js:1)
at d (app.bundle.js:1)
at a (app.bundle.js:1)
at vendors~app.bundle.js:1
at vendors~app.bundle.js:1
at Array.map (<anonymous>)
at r (vendors~app.bundle.js:1)
at Module.<anonymous> (app.bundle.js:1)
```
=> convert mousetrap pause extension into module format

dev/build.sh
This adds a bash build script to aid in testing and deployment.
```bash
#
```
For example, if running in a git repo:
./dev/build.sh   # uses git repo root to build, and does not install anything
If not running in a git repo:
./dev/build.sh .
Or maybe install it as dcrdatabuild.sh on your path:
dcrdatabuild.sh ~/work/decred/dcrdata
Specify an install folder to deploy:
./dev/build.sh . /opt/dcrdata
=> Add build/install script

webpack.common.js, webpack.prod.js
This fixes:
- script loading 404's in development mode due to bundles not being split.
- dynamic import 404 due to publicPath being relative ( eg entering app at /block/123 would result in attempts to load scripts at /block/dist/js )
=> make publicPath absolute, standardize bundle split across dev & prod

public/js/controllers/address.js, views/address.tmpl
Using outerText was flawed, and the new AddressValidation seems to
reject it while previously it was loaded.
=> [3.1] Get address for charts AJAX from stimulus dataset

public/index.js
Followup to #853. I'm not sure how I didn't see this in testing.
=> .jsonly elements shown on every Turbolinks visit

public/js/controllers/charts_controller.js
Replaces pushState with a Turbolinks version of `replaceState` so that page navigation works with the browsers forward and back arrows.
=> back and forward navigation fixed for charts page

api/apirouter.go, api/apiroutes.go, api/types/apitypes.go, db/dcrpg/pgblockchain.go, db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/websockethandlers.go, mempool/mempool.go, mempool/mempoolcache.go, public/js/controllers/ticketpool_controller.js, views/ticketpool.tmpl
Removes inline data from the ticketpool page. Initial chart data is retrieved instead via AJAX. 
There is a websocket call that retrieves the same data. I left the websocket source, though now that there is an API endpoint, there may be an argument against the duplication.
=> ticketpool chart data inline -> AJAX

version/version.go
3.2 will never be released as 3.2.  The changes are sufficiently
significant to warrant a major version bump.
=> 3.2 -> 4.0

run_tests.sh
The runs `npm install` and `npm run build` and checks the exit codes to ensure everything webpack does succeeds, including linting with eslinter and stylelint.
This requires https://github.com/decred/dcrdocker/pull/43 to update the docker build image.
=> Run npm install and run build in CI

public/index.js, public/js/controllers/connection_controller.js, public/js/services/desktop_notification_service.js, views/extras.tmpl
* Move logic for styling and handling clicks connection beacon into a stimulus controller
* Add 'clickable' styling to connection beacon
* Switch to using native DOM api [classList methods](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) to update classes for connection beacon ( in an effort to start eliminating jQuery dependency ) 
* Move desktop notification logic into a service module
=> Move connection indicator & desktop notification logic out of index.js

public/index.js, public/js/controllers/ticketwindow_controller.js, views/extras.tmpl, views/statistics.tmpl, views/windows.tmpl
1. Inline `DCRThings` moved to index.js
2. The `stats` page is a mystery to me (is there a link to it somewhere?), but it had some code for tooltips using a bootstrap jQuery plugin, which doesn't appear to be installed. I just removed the code. It does have a title that renders pretty nicely on dektop, though the page itself has some issues in firefox. I also removed some extraneous and duplicate `id` attributes I suspect of being copypasta.
3. New stimulus controller for the ticket price windows page.
=> Last of the inline JS removed

public/js/controllers/charts_controller.js
`event.data.chartsView` on line 174 was undefined.
Fixed by using arrow functions to maintain the top level `this` reference to the controller.
=> fix function scope mismatch when changing themes on chart page

public/js/services/keyboard_navigation_service.js
* call Moustrap.pause() when initializing keyboard navigation service.
Fixes the current problems of bindings executing when they shouldn't:
=> pause Mousetrap on init if keynav is inactive

views/mempool.tmpl
Resolves issue #889.
This resolves the last block age not functioning on the /mempool page.
With 3.1.0 release, the age was not working:
This restores the correct Stimulus.js controller for the 3.1 branch.
=> [3.1.1] Change mempool last block age controller back to main

db/dcrsqlite/sqlite.go, explorer/explorermiddleware.go
This resolves an issue with go-sqlite3 where the following error may be encountered:
database is locked
which corresponds to the [SQLITE_BUSY error](https://sqlite.org/rescode.html).
The issue is discussed at length in https://github.com/mattn/go-sqlite3/issues/274, but the gist is:
1. SQLite should be compiled in "sequential mode" to handle multithreaded access. This change was made for go-sqlite v1.10.0  in https://github.com/mattn/go-sqlite3/commit/acfa60124032040b9f5a9406f5a772ee16fe845e. This dependency update is made in https://github.com/decred/dcrdata/pull/877
2. Limiting the sql driver to just one active connection (the driver it maintains a connection pool) prevents concurrent access. 
```go
db.SetMaxOpenConns(1)
```
3. Setting a non-zero value for "busy_timeout" instructs …
=> dcrsqlite: mitigate database is locked errors

README.md, cmd/rebuilddb/rebuilddb.go, config.go, db/dcrpg/sync.go, db/dcrsqlite/apisource.go, db/dcrsqlite/chainmonitor.go, db/dcrsqlite/sync.go, explorer/explorer.go, explorer/explorermiddleware.go, explorer/explorerroutes.go, explorer/explorerroutes_test.go, explorer/mempool.go, explorer/syncstatus.go, explorer/templates.go, explorer/types/explorertypes.go, explorer/websocket.go, explorer/websockethandlers.go, main.go, notification/ntfnchans.go, notification/ntfnhandlers.go, views/parameters.tmpl
Note: this builds on a commit from @buck54321 in his PR https://github.com/decred/dcrdata/pull/845 so that this can integrate more easily.
This moves several types and functions to explorer/types (new package).
CommonPageData and all expStatus values are moved to explorerroutes.go
Export `wiredDB` -> `WiredDB`.
Views folder is now an argument to `explorer.New`.
Refactor sync status page coordination (ideally a separate PR, but it's tied pretty tightly now):
- Move sync status functions into new syncstatus.go
- two nil channels initially (`barLoad` and `latestBlockHash`)
- `explore.BeginSyncStatusUpdates` function takes `barLoad`
- Anonymous goroutine in main takes `latestBlockHash`
- Eliminate several unneeded functions
- One DB's sync function gets the non-nil channels
- Non-nil channels …
=> refactoring for httptest

public/index.js
=> Removed multiply by 1000 on a formatted date string. #876

api/apirouter.go, api/apiroutes.go
When the request user agent indicates a Windows client, use CRLF line
endings (default to CR on all other systems).
Remove the bufio.NewWriter call since bytes.Buffer is already a Writer.
Check the bytes written vs. bytes to send, even when err == nil.
=> csv download: set line endings for Windows

api/apiroutes.go, api/types/apitypes.go, db/dcrsqlite/apisource.go
This adds to total fees and total sent for a block to the API.
The following endpoints now have at total sent and total fees:
- /block/best
- /block/hash/{hash}
- /block/{idx}
The block range endpoints do not have these new fields.
The fields are omitted by default.  They must be requested with the txtotals URL query parameter, as in:
/api/block/303111?txtotals=true
```json
{
"height": 303111,
"size": 8846,
"hash": "00000000000000001d2f9f9712c3e51717368a6768da8ef46080545ac13b57b4",
"diff": 9876723357.051346,
"sdiff": 107.10317865,
"time": 1545537182,
"txlength": 0,
"fees": 611162,
"total_sent": 240672707327,
"ticket_pool": {
"height": 0,
"size": 41128,
"value": 4218846.64176546,
"valavg": 102.57845365117342,
"winners": [
"a2bc39293435b7b7fa75f18054ddfe9e7a954310ff7aa7cc2d20eb12f54e97fe", …
```
=> api: total fees and total sent for a block

public/js/controllers/charts_controller.js
* fix broken path for x-axis in transactions per day chart by changing `timestr` to `time` in txPerDayFunc
=> fix broken path to x axis (timestr => time) in txPerDayFunc

LICENSE, api/apiroutes.go, api/insight/apiroutes.go, api/types/insightapitypes.go, db/dcrpg/insightapi.go, db/dcrpg/pgblockchain.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, explorer/explorer.go, explorer/explorermiddleware.go, explorer/explorerroutes.go, main.go, middleware/apimiddleware.go
Modify the interfaces for both lite and full DBs so that
GetHeight returns (int64, error).
err == sql.ErrNoRows is expected with a fresh sync,
so do not log it.
=> db: GetHeight returns int64 and error

LICENSE, api/apiroutes.go, explorer/explorer.go, explorer/explorerroutes.go, views/address.tmpl
Instead of the API's CSV download handler inspecting the user agent,
use a URL query parameter (cr=true) to request a CSV file with CRLF line
endings.
The address page handler inspects the user agent and generates the
appropriate API endpoint link.
> "GET http://127.0.0.1:7777/download/address/io/DcZKvuV4BDMpit1ppCXTyyHwuRU8G7nNVKV HTTP/1.1" from 127.0.0.1:43506 - 200 436140B in 9.772752ms
"GET http://127.0.0.1:7777/download/address/io/DcZKvuV4BDMpit1ppCXTyyHwuRU8G7nNVKV?cr=true HTTP/1.1" from 127.0.0.1:43528 - 200 438790B in 10.949158ms
=> CSV download link specifies line endings

views/extras.tmpl, views/home.tmpl
This removes unwanted white space in the `"decimalFormat"` html template and in the formatting of the `NEXT TICKET PRICE ESTIMATE` values on the home page.
Before:
After:
This may have snuck in with https://github.com/decred/dcrdata/pull/893.  The amount selection fix in PR #893 is preserved.
=> views/home: remove extra white space

package.json
This avoids a vulnerability of in versions of webpack-dev-server prior
to 3.1.11 in which origin validation is missing. The vulnerability
allows source code to be accessed remotely when running `npm run watch`
(not done in production). For dcrdata, which is an open source project, this
is a minor issue or non-issue.
Ref: https://www.npmjs.com/advisories/725
This resolves the issue by updating webpack-dev-server in
devDependencies to ^3.1.14 from ^3.1.10.
=> npm: address webpack-dev-server vulnerability

config.go, db/dbtypes/types.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/rewind.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go, db/dcrpg/rewind.go, db/dcrsqlite/sync.go, main.go, stakedb/stakedb.go
Purging a block and all associated data from the DB involves removing
rows from several tables. This adds db/dcrpg/internal/rewind.go, which
defines the query strings to delete rows based on block hash, and
db/dcrpg/rewind.go, which defines the functions to execute the queries.
The added `DeleteBlockData` function performs the queries in the correct
order: vins, vouts, addresses, transactions, tickets, votes, misses,
blocks, and finally block_chain.
`DeleteBlockData` returns an instance of the new `dbtypes.DeletionSummary`
type that contains counts of the number of rows removed from each table,
and optionally timings for each query.
This also adds the helper functions `DeleteBestBlock` and `DeleteBlocks`.
`DeleteBestBlock` (and `DeleteBlocks`) returns the best block height _after_ …
=> dcrpg: Add block deletion/purge queries and functions.

db/dcrpg/pgblockchain.go, db/dcrpg/rewind.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, db/dcrsqlite/sync.go, main.go
Purge data from the base (sqlite) DB too. The number of blocks to purge
for each DB is computed so that the DBs will end on the same height.
Add `PurgeBlock`, `PurgeBestBlock`, and `PurgeBestBlocks` to `WiredDB`.
Add `deleteBlock` and `DeleteBlock` to `sqlite.DB` (used by `WiredDB`).
Organize the `dcrsqlite.DB` struct.
Add `getBlockSummaryHeight` and `getStakeInfoHeight` which bypass the best
block caches.  These functions are now called by `GetBlockSummaryHeight`
and `GetStakeInfoHeight`, which update the caches.
Add `deleteStakeInfo` and `deleteStakeInfoHeightMainchain` to dcrsqlite.DB.
Remove the locking from `RetrieveAllPoolValAndSize` since the lock is only
meant to guard `lastStoredBlock`, `dbSummaryHeight`, and `dbStakeInfoHeight`.
Add an optional "quiet" bool argument to `(db …
=> dcrsqlite: Add purge block functions to WiredDB (sqlite)

blockdata/blockdata.go, db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go
blockdata: Add `BlockchainInfo` to `BlockData` struct, and retrieve the
`dcrjson.GetBlockChainInfoResult` in `Collect` and `CollectHash`. This
makes it available to all `BlockDataSaver`s.
explorer: Add `BlockchainInfo` to `pageData`. Remove `ChartData` from
`AddressPageData` since it is no longer used.
Resolving issue https://github.com/decred/dcrdata/issues/678.
=> use getblockchain info for MaximumBlockSize

db/dcrsqlite/chainmonitor.go, db/dcrsqlite/sqlite.go
When storing data for a main chain block, `(db *DB).StoreBlock` will first
set `is_mainchain=false` for any other block at this height. Previously,
this was only being done in `Store`, which was not used during a reorg.
However, `Store` uses `StoreBlockSummary`->`StoreBlock`, so now this will
always happen.
Note that his is usually an unnecessary query since most of the time
`StoreBlock` is used outside of a reorg context.  But this solution is very
simple.  If performance of this query is an issue, it can be done
only from the `ChainMonitor`'s reorg handler.
NOTE: this should be backported for 3.1.2.
=> dcrsqlite: have StoreBlock set existing blocks to side chain first

api/apirouter.go, explorer/explorermiddleware.go, middleware/apimiddleware.go
This needs to be an `int`, not `int64`.
Change several ctx type assertion checks to Warning from Trace.
Also, fix `/api/tx/{txid}/trimmed`, which was using `getDecodedTransactions`
instead of `getDecodedTx`, resulting in an invalid `{txid}`.  Both functions
use `BlockData.GetTrimmedTransaction`.  TODO: give `getDecodedTransactions`
a `?spends=[bool]` URL query parameter too.
=> middleware: fix incorrect ctxBlockIndex data type

db/dcrsqlite/sqlite.go
Historically, SQLite did not handle concurrent writes internally,
necessitating a limitation of just 1 open connecton. With a busy_timeout
set, this is less important. With go-sqlite 1.10, this is not needed at
all since the library started compiling sqlite3 for
thread-safe/"serialized" operation (SQLITE_THREADSAFE=1). For details,
see https://sqlite.org/threadsafe.html and
https://sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfigserialized.
The change to go-sqlite3 is
github.com/mattn/go-sqlite3@acfa60124032040b9f5a9406f5a772ee16fe845e
=> dcrsqlite: This enables multiple sqlite connections again.

db/dcrsqlite/chainmonitor.go, db/dcrsqlite/sqlite.go
`StoreBlock` previously set all blocks at a given height as side chain
(`is_mainchain=false`) before adding the new block data, but this was
unnecessary unless the new block was being added as part of a reorg,
where there are actually such blocks that are being orphaned/demoted.
This change moves the `setHeightToSideChain` call from `StoreBlock` to
`switchToSideChain` where it belongs.
This resolves a significant performance regression with initial sync.
=> dcrsqlite: Only move blocks to side chain during reorg.

db/dbtypes/conversion.go, db/dbtypes/types.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/queries.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go, db/dcrpg/upgrades_test.go, explorer/syncstatus.go
Remove `extra_data`, `final_state`, `merkle_root`, and `stake_root` from `blocks`.
Remove the corresponding fields from `dbtypes.Block`.
Bump dcrpg tables version from 3.7.0 to 3.8.0.
Implement upgrade of table versions that removes the columns.
Add `deleteColumnsIfFound` to upgrades.go for future use.
=> dcrpg: remove several unused columns from blocks table.

db/dcrsqlite/apisource.go, main.go
The SQLite table heights are now checked early in main.
This adds (*WiredDB).ReportHeights.
=> dcrsqlite/main: Insert sanity check on SQLite table heights

config.go, db/dbtypes/types.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, main.go
This adds the `--fast-sqlite-purge` option does not follow the main chain back by N
blocks. Rather it deletes all data for blocks above a certain height
that is computed the same way as the normal purge.
Add `(*WiredDB).PurgeBlocksAboveHeight` and the queries:
`deleteStakeInfoAboveHeightSQL` and `deleteBlocksAboveHeightSQL`.
Change `RetrieveLatestBlockSummary` to query the best block on main chain.
Fix `getHighestStakeHeight` to join with the block summary table on hash
where `is_mainchain=1`.  This ignores side chain blocks when requesting best
block data.
Add a sanity check in `PurgeBestBlock` to ensure the block summary and
stake info tables are at the same height.
=> dcrsqlite: fast and thorough purge

api/types/apicache.go, api/types/apicache_test.go, db/dcrsqlite/sqlite.go
Add `StakeInfoExtended`, `height`, and `hash` to `CachedBlock`.
Create `(*APICache).StoreStakeInfo`.
Create `(*APICache).GetStakeInfo` and `(*APICache).GetStakeInfoByHash`, and
use them in `(*DB).RetrieveStakeInfoExtended[ByHash]`.
Do not enable API cache by default; enable it in `main` after sync.
=> api cache: Cache stake info too.

go.mod, go.sum
Update to the latest master of dcrutil to get the Block bytes cache fix.
=> Update dcrutil module dependency for Block cache fix.

db/dcrsqlite/dcrsqlite_test.go, db/dcrsqlite/sync.go, main.go
In `(*WiredDB).resyncDB`, recognize the unknown ticket spent in block
error, parse the ticket tx hash, get the block height of the ticket, and
append `purge-n-blocks` recovery instructions to the error message.
Add `(*WiredDB).supplementUnknownTicketError` to perform this error
message check/supplement.
Also clean up waitForSync.
=> dcrsqlite: provide advice for recovery on unknown ticket error

db/dcrsqlite/apisource.go, public/js/controllers/tx_controller.js, views/tx.tmpl
Vins in raw verbose transaction from dcrd for a mempool transaction are not given a block height, even if the previous outpoint has been confirmed. Looks them up. 
Also, a transaction can reference another mempool transaction, so in the "pending" case, stimulus checks for those txids in new blocks and add a link to the block once its included.
Resolves #906 and maybe #130
=> confirmed and unconfirmed previous outpoint links

api/insight/apiroutes.go, db/dcrpg/queries.go
This function was still querying with `int64` times instead of `time.Time`
values, which is necessary since the table column became a `TIMSTAMP`.
Note: This is not a backport candidate for 3.1 since 3.1 used int64 for time columns.
=> dcrpg/insight: fix get block summary by time

api/insight/apiroutes.go, db/dbtypes/types.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/explorerroutes.go, public/js/controllers/address_controller.js, views/address.tmpl, views/extras.tmpl
Makes a few changes to the  `AddressInfo` type. `TxCount` is an `int` instead of a getter, and removed the `NumMergedSpent` member. Instead, merged type rows are only counted on relevant requests, instead of
every time (see `RetrieveAddressSpentUnspent` changes). For simple debit and credit views, this provides a substantial performance boost.
Changes the response from `explorer.AddressTable` to a JSON object, with a `tx_count` and `html` field. The count is needed since the merged rows are not being counted every time anymore. This is possible because if there are credits and debits available, there are merged rows available, an vice versa.
Resolves #742
=> add merged and merged credit views

go.sum, version/version.go
The Sereal repo was affected by the symlink checksum bug of go 1.11.3.
This recomputes the checksum using go 1.11.5.
The dcrdata version is bumped to 3.1.2.
=> This fixes the bad checksum for Sereal.

README.md, api/apirouter.go, api/apiroutes.go, config.go, exchanges/bot.go, exchanges/exchanges.go, exchanges/exchanges_test.go, exchanges/log.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorerroutes_test.go, log.go, main.go, sample-dcrdata.conf, views/home.tmpl
The `exchanges` package contains `ExchangeBot`, which can be used to monitor DCR-BTC exchanges and BTC-fiat indices. Exchangebot can be disabled completely, or individual exchanges can be disabled.
The package currently has 5 Decred-BTC exchanges and 2 BTC-fiat index sources. The package is completely independent of other DCRData packages, but has been integrated with DCRData to demonstrate how I envision its use. 
New API endpoints added for retrieving the Decred exchange rate in one of almost 200 base currencies (indices). Results are JSON-formatted and support indenting. Try
```
http://localhost:7777/api/exchanges
http://localhost:7777/api/exchanges?indent=1&code=EUR
http://localhost:7777/api/exchanges/codes
```
On the website side, the price is simply displayed in a chosen default …
=> Add exchange rate monitoring

explorer/explorerroutes.go, explorer/types/explorertypes.go, explorer/websockethandlers.go, pubsub/pubsubhub.go, txhelpers/txhelpers.go, txhelpers/txhelpers_test.go
This sets the following fields of the `TrimmedTxInfo` struct in the `TrimMempoolTx` function that were not previously being set: `FormattedSize`, `Fee`, and `FeeRate`.  It is not clear why they were left unset.
While in this area, also:
- In `FilterUniqueLastBlockVotes`, make sure duplicate votes with the same tx id are not added to the returned votes slice.
- Add `txhelpers.FeeRate`, and use it in `TxFeeRate`.  Add tests.
- Fix the docs for `TxFeeRate`.
The changes with the `TrimMempoolTx` and the `TrimmedTxInfo` struct are visible in a `getmempooltxsResp` websocket message.
Before:
```json
{
"TxID": "c7c64fac57a404945295df4a4235617f339cbc1d2d3932f34ba54361366131f6",
"FormattedSize": "",
"Total": 3125.94048853,
"Fee": 0,
"FeeRate": 0,
"VoteInfo": null,
"Coinbase": false,
"Fees": …
```
=> explorer/types: set fee and fee rate in TrimMempoolTx

public/js/services/keyboard_navigation_service.js
In both the mempool and homepage controllers, `keyNav()` was being called on updates, and had no checks for whether keyboard navigation was actually enabled by the user.
=> fix mempool webocket message keynav bug

db/dcrpg/internal/system.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/system.go, db/dcrpg/system_online_test.go, db/dcrpg/system_test.go
This shows the PostgreSQL server version, performance related settings, and some server config.
e.g.:
```
[INF] PSQL: PostgreSQL 11.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.2.1 20181127, 64-bit
[INF] PSQL: postgres performance settings:
Name |     Setting |     Source |         File |  Line | Description                                     
════════════════════════════════╪═════════════╪════════════╪══════════════╪═══════╪══════════════════════════════════════════════════
autovacuum |         off |  conf file | NO PERMISION |       | Starts the autovacuum subprocess.               
autovacuum_work_mem |       -1 kB |    default |              |       | Sets the maximum memory to be used by each autov
checkpoint_completion_target |         0.9 |  conf file | NO PERMISION |       | …
```
=> dcrpg: show server config at startup

public/scss/_variables.scss, public/scss/home.scss, public/scss/table.scss, views/address.tmpl, views/agenda.tmpl, views/agendas.tmpl, views/block.tmpl, views/disapproved.tmpl, views/explorer.tmpl, views/home.tmpl, views/mempool.tmpl, views/parameters.tmpl, views/sidechains.tmpl, views/statistics.tmpl, views/timelisting.tmpl, views/tx.tmpl, views/windows.tmpl
This PR explores alternative possibilities for handling homepage layout in
https://github.com/decred/dcrdata/pull/961
Note this PR bumps up the boostrap grid to 24 cols, so would require updating the rest of the views if adopted. 
Mainly I'd like to find ways to make the layout simple, more uniform and space efficient
=> home layout refinement

explorer/types/explorertypes.go, mempool/collector.go
Summing up fees as floating point numbers was inaccurate (duh). Instead,
add as `int64` and then get the decimal representation for display.
Two big offenders:
- `(*MempoolInfo)Trim` added fees in float.
- `ParseTxns` did lots of summation in float instead of int, leading to loss of precision all over.  This fixes it by summing in `int64` and then converting to coin/DCR at the end.
Bad:
```
"Fees": 0.042270350000000005
"Total": 8727.786064009997
```
Good:
```
"Fees": 0.04227035
"Total": 8727.78606401
```
=> stop the floating point math for fee summation

db/dcrsqlite/apisource.go, txhelpers/txhelpers.go, txhelpers/txhelpers_test.go
This avoids needless getrawtransaction RPCs for a zero hash transaction, thus eliminating:
> [ERR] SQLT: Error getting data for previous outpoint of mempool transaction: -5: No information available about transaction 0000000000000000000000000000000000000000000000000000000000000000
Add `txhelpers.IsZeroHash` and `IsZeroHashStr` with tests.
=> dcrsqlite/txhelpers: avoid getrawtransaction for zero hash inputs

explorer/websockethandlers.go, pubsub/pubsubhub.go, pubsub/types/pubsub_types.go
WebSocket connections closing is normal, do not log these events.
Add `IsWSClosedErr` to `pubsub/types`, and use it in `explorer` and `pubsub`. The `pubsub/types`
package is used since the error relates to websocket connections and this is close to `pubsub`.
=> websocket: Do not log websocket closed errors

dev/build.sh
If the GNU `parallel` command is available, use it for gzipping the static assets.
Also check if `7za` is installed and fall back on `gzip`.
=> build.sh: use gnu parallel if available

api/types/apitypes.go, db/dcrsqlite/apisource.go
This changes `api/types.TxOut`, removing `PkScript` and `Addresses`, and adding
a `ScriptPubKey` struct, which include the script hex, address and more.
**/api/tx/9af946f599e09d68b4590ced2e046c3f883411e1f06e199c073efa621af18d93/out?indent=true**
Before:
```json
[
{
"value": 2.999738,
"version": 0,
"pkscript": "76a9147ac85ec3f05a103ad3f5da194ce2e7569461778a88ac",
"addresses": [
"DscA7xoE2FtJbkzaAkMZKMG8H6jZkpwYs5b"
]
},
{
"value": 0,
"version": 0,
"pkscript": "6a20e9eb2ae23893616da16e95834f37744201fb0231f684123ab767c93fbcf8aab5"
}
]
```
After:
```json
[
{
"value": 2.999738,
"version": 0,
"scriptPubKey": {
"asm": "OP_DUP OP_HASH160 7ac85ec3f05a103ad3f5da194ce2e7569461778a OP_EQUALVERIFY OP_CHECKSIG",
"hex": "76a9147ac85ec3f05a103ad3f5da194ce2e7569461778a88ac",
"reqSigs": 1,
"type": …
```
=> api: return decoded pkScript with /tx/{txid}/out endpoint

api/types/apitypes.go, api/types/apitypes_test.go, db/dcrsqlite/apisource.go
This adds `ScriptClass`, which represents the type of a transaction
output's pkscript. The values of this type are NOT compatible with
dcrd's `txscript.ScriptClass` values! Use `ScriptClassFromName` to get a
text representation of a `ScriptClass`.
Also add check the type returned by dcrd when in `GetAllTxOut` as a smoke
test for changes or additions to the strings returned by dcrd.
=> apitypes: add ScriptClass and friends

db/dcrsqlite/sqlite.go
Before the sqlite table upgade is performed, it is still necessary to
query the best block height in the block and stake info tables. This
adds alternate queries that do not reference the `is_mainchain` column.
Note that the upgrade worked before 9a5780a3dd2c75570d7b3fdf6119aa3c5e82736d, which added the `is_mainchain` constraint to the queries.
Add `RetrieveHighestBlockHeight` and `RetrieveHighestStakeHeight` that
perform the query without `is_mainchain`, and add the wrappers
`getBlockSummaryHeightAnyChain` and `getStakeInfoHeightAnyChain`.
`NewDB` is modified to recognize `"no such column: is_"` errors, and
to fallback on the `"AnyChain"` functions to set the heights.
At the end of a successful table upgrade, query for the stake info best
block height using the block summary table join …
=> dcrsqlite: add best block queries with no is_mainchain constraints

main.go, rpcutils/rpcclient.go, rpcutils/rpcclient_test.go
Uses the existing purge-n-blocks loop. `rpcutils.OrphanedTipLength` compares a database to dcrd from the tip height down until a common mainchain ancestor is found, and returns the number of sidechain blocks to be purged.
Resolves #601
=> Purge orphaned tip blocks on startup

db/dcrsqlite/apisource.go, explorer/explorerroutes.go, views/tx.tmpl
Coinbase transactions should show a pseudo-input on the /tx page that indicates mining fees collected.  This was accidentally broken when data types changed that resulted in the fees being zero.
Before the fix:
After the fix:
I believe this bug was unreported, but it also resolves https://github.com/decred/dcrdata/issues/651 together with dcrd's changes to utxo set semantics.
=> restore Coinbase txns block mining fee pseudo-input on /tx

views/home.tmpl
I missed porting updating the grid classes for the exchange rate datum in https://github.com/decred/dcrdata/commit/62adc564ae51c09b41740a981797f7e3aa6de79e
This aligns the exchange rate datum like the rest of the datums.
Before:
After:
=> fix grid layout for exhange rate datum in /home

README.md, cmd/rebuilddb2/config.go, cmd/rebuilddb2/rebuilddb2.go, config.go, db/dcrpg/pgblockchain.go, main.go, sample-dcrdata.conf
`hidepgconfig` blocks logging of the postgresql db configuration which happens by default.
To startup dcrdata now without displaying the tabular configuration settings can be achieved by running:
```shell
go build ./ && ./v4 --hidepgconfig
```
=> Add hidepgconfig flag

views/windows.tmpl
On `/ticketpricewindows` page the dropdown menu did not work because the blocklist `data-controller` was missing.
=> Fix windows view drop down navigation bug

db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go
Resolves https://github.com/decred/dcrdata/issues/999
This bumps dcrpg schema from 3.8.0 to 3.9.0.
Also set the postgres time zone to UTC in NewChainDB[WithCancel].
Maybe reindex time column of addresses and agendas table.
This *MUST* be merged prior to https://github.com/decred/dcrdata/pull/988
Tests:
=> dcrpg: upgrade all timestamp columns to timestamptz

public/js/controllers/ticketpool_controller.js
This fixes two bugs in ticketpool_controller.js.
1. incorrect chart data used for time_chart:
2. misspelling of `priceGraph`:
=> Ticketpool time chart

db/dcrpg/tables.go, semver/semver.go, semver/semver_test.go
`semver.ParseVersionStr` parses out a version from an input string.
Add tests for `ParseVersionStr`.
Use `ParseVersionStr` in `dcrpg.TableVersions`.
=> semver: add ParseVersionStr and Split, use in dcrpg

db/dcrpg/sync.go, db/dcrsqlite/sync.go, main.go
Premature closing of the `barLoad` channel resulted to a panic when trying to send data through a closed `barLoad` channel. 
Sending `nil` via the channel results to `barLoad` being assigned `nil` rather than closing it thereby avoiding the panic.
#1005
=> Open the barload channel always

explorer/websockethandlers.go, pubsub/pubsubhub.go, pubsub/types/pubsub_types.go
This avoids logging messages like the following when closing websocket connections with no listening client:
> [ERR] EXPR: Failed to close websocket: write tcp 127.0.0.1:7777->127.0.0.1:37520: i/o timeout
Closing a closed websocket connection can also result in a error with
the string "i/o timeout" since closing involves a send to the client.
When closing a websocket connection in a deferred function from the
websocket handers of explorer and pubsub, recognize such errors
and do not log the message.
=> pubsub/types: Add IsIOTimeoutErr and use when closing connections

db/dcrpg/internal/stakestmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/types/explorertypes.go, views/tx.tmpl
dcrpg: Add queries to locate the block in which a ticket missed via the
misses table.  Join with the blocks table to limit to mainchain.
explorerer: Add `TicketMiss(ticketHash string) (string, int64, error)` to
the `explorerDataSource` interface.
Use `TicketMiss` in `(*explorerUI).TxPage`, to retrieve the block hash for a ticket's
missed vote.
explorer/types: Add `LotteryBlock` to `TicketInfo`. `LotteryBlock` represents
the hash of the block in which a tickets was is supposed to vote.
views: Link the "missed" text to the lottery block where it is listed as
a missed vote.
=> dcrpg/explorer: link to the block where a missed ticket failed to vote

db/dbtypes/types.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go, db/dcrpg/sync.go, main.go
Add a UTXO set query, `RetrieveUTXOs`.
Run `RetrieveUTXOs` in `main` when resuming sync with no indexes.
Change `dbtypes.UTXOData` to have a `[]string` addresses instead of a
single address (bare multisig is supported now).
`insertSpendingAddressRow` inserts rows for all addresses of a tx output.
Add `(*utxoStore).Reinit` and `(*ChainDB).InitUtxoCache` to populate the
UTXO cache.
Resolves https://github.com/decred/dcrdata/issues/1028
=> dcrpg: this adds a UTXO cache refresh capability

views/mempool.tmpl
* Make top margin the same as other pages ( If there's interest in increasing the amount of top margin for page headings, it should be done globally, so the heading is always at the same height between the various pages )
* Increase font size of overview stat values
* Rework layout of secondary card to same labeling style as primary card
* Reduce spacing between tables
Current:
Proposed Changes:
proposed changes (mobile):
=> Refine mempool page layout

db/dcrpg/internal/blockstmts.go
Resolves #1004. I did verify that dygraphs handles out of order timestamps without issue.
=> Order chainwork query by block height

api/apirouter.go, api/apiroutes.go, db/dcrsqlite/apisource.go
This adds the following endpoints:
- /block/best/header/raw
- /block/{ind}/header/raw
- /block/hash/{hash}/header/raw
Use the same api/types.BlockRaw type as used for the raw block endpoints
=> api: add raw block header endpoints

public/js/controllers/homepage_controller.js, views/home.tmpl
The vote rewards (both per average reward period and yearly) need not be
shown with green for positive.
In the following section, the vote rewards do not need a color to indicate sign.
Change this to:
Note that this also removes the space before the percent symbol.
=> views/controllers: stop showing vote reward rates in color

explorer/explorer.go, explorer/types/explorertypes.go, public/js/controllers/homepage_controller.js, pubsub/psclient/client_test.go, pubsub/pubsubhub.go, views/home.tmpl
Keep daily hashrate in a separate variable for now.
This changes the `explorer/types.HomeInfo` variable and its JSON tags. It
now has `hash_rate_change_day` and `hash_rate_change_month` instead of just
`hash_rate_change`.
Update homepage controller to set `hashrateDeltaTarget` to monthly delta.
The hash rate is very choppy on a daily basis, so show monthly like this:
instead of daily:
=> explorer: change hashrate change from daily to monthly

views/home.tmpl
data-type of the size column on the Latest Blocks table was set to
"value" instead of "size".  This broke websocket JS updates.
Resolving https://github.com/decred/dcrdata/issues/1043
=> views/home: data-type of size column needs to be "size"

db/dbtypes/types.go, db/dcrpg/pgblockchain.go
This prevents an error when there his no txn history for either
`AddrTxnDebit` or `AddrMergedTxnDebit` views.
Also add `(AddrTxnType).IsMerged`.
Add TODO comments to handle unconfirmed transactions in merged views.
=> dcrpg: allow empty address history for merged debits too

api/apiroutes.go, api/insight/apiroutes.go, db/cache/addresscache.go, db/cache/addresscache_test.go, db/dbtypes/types.go, db/dcrpg/chainmonitor.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/sync.go, explorer/explorer.go, explorer/explorermiddleware.go, explorer/explorerroutes.go
Add a new `cache` package, starting with addresscache.go, which includes
`AddressCache` and `AddressCacheItem`.
Use `AddressCache` in `ChainDB`.
Remove `DevFundBalance` since it benefits from the general `AddressCache`.
Remove `addressCounts` since `AddressCache` includes balance.
To update an address' data, add `RetrieveAllMainchainAddressTxns` and
`RetrieveAllMainchainAddressMergedTxns`, which do not use `offset` or `N`.
Also cache transaction view type row counts via the new
`(*ChainDB).CountTransactions` function, which use cache or DB queries to
get the row counts for any of the supported txn view types.
Also:
- Use `vouts` table primary key in `SelectAddressUnspentWithTxn`.
- Avoid height query in `AddressUTXO`, using latest stored height instead.
- fix: `RetrieveAddressUTXOs` …
=> cache: add cache package and AddressCache for dcrpg

exchanges/bot.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/types/explorertypes.go, public/js/controllers/homepage_controller.js, public/js/helpers/humanize_helper.js, views/home.tmpl
Adds fiat conversions to the homepage for ticket price, coin supply, miner block reward, treasury block reward, and treasury balance. 
`exchanges` package gets `Conversion` type which has the `TwoDecimal` method for displaying its value, with a minimum of two decimal places and a minimum of three significant figures.
Values are updated live with websocket `newblock` updates.
=> more fiat conversions

docs/CONTRIBUTING.md
Sets 
`[Package/File/Directory Name]: [Short but concrete description of the PR/Issue]` 
as the standard issue/PR naming format
=> docs/contributing.md: Set the PR/Issues naming standard

public/js/controllers/blocklist_controller.js, public/js/controllers/pagenavigation_controller.js, views/explorer.tmpl, views/extras.tmpl, views/proposals.tmpl, views/timelisting.tmpl, views/windows.tmpl
This PR fixes the following bugs on the `/ticketpricewindows` , `/blocks`, `/days`, `/weeks`, `/months` and `/years` pages drop down menus.
- #1036 - fixed by having all those pages share stimulus js controller functions
- On Changing the page size on `/blocks`, `/days`, `/weeks`, `/months` and `/years` pages, some invalid URL query parameters were set.
- The pagesize dropdown never had a limit to the maximum page size that can be set. The maximum page size set via the drop down has been capped at 200.
=> Fix bugs on the blocks listing pages' dropdown menus

db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go
This accelerates InsightAddressTransactions, which is used for several
Insight API endpoints.
`InsightAddressTransactions` is modified to use the `rowsMerged` cache,
first checking that each address is in the cache, and then merging the
results as would be done by the DB query.
Add `(*ChainDB).AddressRows` to get the cached address rows, or query the
DB and update the cache.
Use cache-enabled `AddressRows` for `AddressTxIoCsv`.
Also add `dcrpg.MakeCsvAddressRows` to convert from `[]*dbtypes.AddressRow`
to [][]string for a CSV output.
Use AddressRows and AddressBalance in updateProjectFundCache instead
of the AddressHistory cludge.
Etc.:
- Remove the `JOIN` from `SelectAddressesAllTxn` since `block_time` is
already in the addresses table and sufficient for getting a "recent"
transactions …
=> caching and query tuning for InsightAddressTransactions

api/types/apicache.go, blockdata/blockdata.go, db/cache/addresscache.go, db/dcrpg/pgblockchain.go, db/dcrsqlite/sqlite.go, exchanges/bot.go, exchanges/exchanges.go, explorer/explorer.go, explorer/types/explorertypes_test.go, explorer/websocket.go, gov/politeia/proposals.go, mempool/collector.go, mempool/mempoolcache.go, mempool/monitor.go, pubsub/pubsubhub.go, rpcutils/blockgate.go, stakedb/chainmonitor.go, stakedb/stakedb.go, stakedb/ticketpool.go
It is the responsibility of the pkg to protect internal data, not the caller.
=> multi: do not export the mutex

gov/politeia/proposals.go, main.go
This PR 
- masks the error returned when `proposalsInstance.CheckProposalsUpdates();` is run in a goroutine.
- Reduce the http client timeout to 10 seconds
cc #1067
=> Fix data race

explorer/explorerroutes.go, views/block.tmpl, views/tx.tmpl
Some functionality of the new `exchanges.Conversion` type and associated ExchangeBot method was duplicated in `explorerroutes.go`.
=> use new exchanges.Conversion type for all fiat conversions

mempool/monitor.go
The mempool monitor is already read locked, so just access directly.
=> mempool: prevent double rlock

db/cache/addresscache.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go
When storing data in cache, ensure the stored data (rows, etc.) are
non-nil if the `BlockID` is also non-nil.  This means storing an empty
non-nil slice in the case of rows and utxos, and an `AddressBalance`
with only the `Address` field set.
Also, in `AddressHistory`, avoid calling `ReduceAddressHistory` when
address rows indicates no history (just return a zero balance).
This prevents a stack overflow with `AddressHistory`, etc. for such
addresses.  Deployed on alpha now.
=> dcrpg/cache: must store empty data as non-nil

api/insight/apirouter.go, api/insight/apiroutes.go, config.go, go.mod, go.sum, main.go, testutil/apiload/profiles.json
Previously the rate limit for the Insight API was hard coded. It is now
settable via the `"insight-limit-rps"` config option.
The default is 20 req/sec per IP address.
Add `(*insightApiContext).SetReqRateLimit`.
Also update the `apiload` profiles.json with an `"insight-addr"` attack
definition, which only hits the various addr/addrs endpoints.
This also updates the go.mod/go.sum entries for github.com/didip/tollbooth
to use pseudo versions.
=> api/insight: Add configurable insight API rate limit.

db/dcrpg/queries.go
Both variables are set each iteration, so just reuse them.
=> Do not allocate a big.Int for each row.

api/types/apicache.go
this saves an RLock/RUnlock every 250ms.
=> apicache: merge time restriction into doesNeedReheap

public/js/controllers/charts_controller.js, views/charts.tmpl
Also adds a constant network target line to the ticket pool size chart.
Resolves #781 and #1054.
=> explorer: add log scale option to charts

blockdata/chainmonitor.go, db/dcrsqlite/apisource.go, main.go, notification/ntfnchans.go, stakedb/chainmonitor.go
The synchronous `BlockConnected` functions (now named `ConnectBlock`) just
do the work without messing with the handler goroutine.
dcrdata (`main`) no longer launches the goroutines that listen on `blockChan`.
Since the goroutines no longer run, do not create the channels. Also do not
pass the channels in the chain monitor constructors.  Instead, create setters
so that other packages that want to use the monitor goroutines instead of the
synchronous functions may do so.
=> wireddb/stakedb: proper synchronous ConnectBlock funcs

db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/txstmts.go
This changes `SelectTxsPerDay` to query from the blocks table instead of the transactions table. This is much faster.
Before:
> Execution Time: 2071.276 ms (cost=297206.48..297257.65)
After:
> Execution Time: 198.559 ms (cost=60490.22..60541.39)
The results are identical.
Also remove "= TRUE" from some queries since it's already boolean.
=> dcrpg/internal: SelectTxsPerDay using blocks table

db/dbtypes/types.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go
Add `dbtypes.MergeRows` to converts a slice of non-merged
(regular addresses table row data) into a slice of merged
address rows. This involves merging rows with the same
transaction hash into a single entry by combining the signed
values. The `IsFunding` field of a merged transaction indicates
if the net value is positive or not, although the `Value` field is
an absolute value (always positive). A map of transaction hash
to `*AddressRow` is also returned.  `MergedRows` will return a
non-nil error of a merged row is detected in the input since
only non-merged rows are expected.
Add a test for `MergeRows` in pgblockchain_test since it is best
tested with a live DB using the project fund address.
Also change `AddressTransactionsAllMerged` so it only gets
`valid_mainchain` rows.
Change …
=> dbtypes/dcrpg: add MergeRows

explorer/syncstatus.go
Fixes: #1103
Adds a `stopTimer` channel shared between the goroutines launched in `BeginSyncStatusUpdates(barLoad chan *dbtypes.ProgressBarLoad) {`
=> explorer/syncstatus.go: Fix barload data race

public/scss/typography.scss
=> explorer: correct word-break value

explorer/explorer.go, explorer/types/explorertypes.go, explorer/websockethandlers.go, mempool/monitor.go, public/index.js, public/js/controllers/homepage_controller.js, public/js/controllers/mempool_controller.js, public/js/services/messagesocket_service.js, views/extras.tmpl, views/home.tmpl
Once the websocket client connects, check the clients mempool ID to see if anything has changed. If so, send a full mempool update. 
This corrects some issues when txs come in during the period after page load but before the websocket connection is made.
I still haven't pinned down how the vote icons can be missing completely, as shown in #1095. The votes for those icons are pulled from either `VotingInfo.BlockStatus` or `VoteTally.Status`, both of which pad their lists with `VoteMissing` to the correct length.
=> explorer: sync mempool on websocket connection

db/dcrpg/internal/common.go
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkMakeARRAYOfBIGINTs-2     26671         4559          -82.91%
benchmark                         old allocs     new allocs     delta
BenchmarkMakeARRAYOfBIGINTs-2     300            9              -97.00%
benchmark                         old bytes     new bytes     delta
BenchmarkMakeARRAYOfBIGINTs-2     22770         2040          -91.04%
```
=> db/internal: use bytes.Buffer

db/dcrpg/indexing.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go
- Adds drop duplicates implementation in agendas and agenda_votes tables
- Adds a more deterministic way to check if the auxiliary db requires an upgrade, re index or rebuild.
=> db/dcrpg: Remove non-determinist VersionCheck implementation

explorer/explorer.go, public/js/services/messagesocket_service.js, pubsub/pubsubhub.go
The `mempool` package was designed to trigger the mempool update events,
but the `sigMempoolUpdate` sends in `StoreMPData` for both `explorerUI` and
`PubSubHub` were not removed. This eliminates these duplicate sends.
=> explorer: only signal mempool update once

api/insight/apiroutes.go, cmd/rebuilddb2/rebuilddb2.go, config.go, db/cache/addresscache.go, db/cache/log.go, db/dbtypes/types.go, db/dcrpg/insightapi.go, db/dcrpg/insightapi_test.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/log.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go, explorer/explorerroutes.go, main.go, testutil/apiload/profiles.json
This reworks the `cache` package handling.
Make capacity measure row count, not address count. Respect cache
capacity when adding new cache items and when storing rows.
The row capacity is enforced on the total number of rows across all cached
addresses.
An address limit is also set since addresses with no rows should be cached,
but not an unlimited number of addresses.
A max number of UTXOs cached is set on a per-address basis. The limit
is computed given the address limit, a rough estimate of AddressTxnOutput
size, and a desired MiB limit.  This is presently hard-coded, but may be a
config parameter in the future.
Merged rows are not cached, so the functions `MergeRows` and
`MergeRowsCompact` are added to get the data on the fly for 
(*AddressCacheItem).Transactions`.
apiload: Add two …
=> cache: rework address cache capacity

package.json
Resolving https://github.com/decred/dcrdata/issues/1128.
This unbreaks formatting issues with Bootstrap 4.3 and possibly 4.2.
Run npm install after applying these changes.
The bug in issue #1128 is manifested when bootstrap is allowed to upgrade too liberally:
```sh
$ npm list |grep bootstrap     
├── bootstrap@4.3.1 invalid                        
```
With this change:
```sh
$ npm list |grep bootstrap     
├── bootstrap@4.1.3
```
Also pins down qrcode more tightly.
TODO: We should consider checking in a package-lock.json with our stamp of approval.  Otherwise we aren't sufficiently controlling what goes into the asset bundle.
=> tighten npm dep version specs

explorer/explorer.go, gov/agendas/deployments.go, gov/agendas/deployments_test.go, main.go
This PR replaced the hard-coded initial votes version with data obtained from `chaincfg.Params.Deployments` map.
=> gov/agendas: Remove hard-coded votes version

public/scss/responsive.scss, public/scss/table.scss, public/scss/themes.scss, public/scss/typography.scss, views/address.tmpl, views/agenda.tmpl, views/agendas.tmpl, views/block.tmpl, views/disapproved.tmpl, views/explorer.tmpl, views/extras.tmpl, views/home.tmpl, views/mempool.tmpl, views/parameters.tmpl, views/proposals.tmpl, views/sidechains.tmpl, views/timelisting.tmpl, views/tx.tmpl, views/windows.tmpl
Finally following up on discussion from https://github.com/decred/dcrdata/pull/982#discussion_r254529952.
Removes unused CSS and migrate v2-tables styling to all tables.
=> explorer: refactor table CSS

cmd/rebuilddb/rebuilddb.go, cmd/rebuilddb2/rebuilddb2.go, cmd/scanblocks/scanblocks.go, main.go, rpcutils/rpcclient.go, rpcutils/rpcclient_online_test.go
The RPC client autoreconnect option should be turned OFF.
The assumption is that once dcrdata starts up, there will never be a missed notification.
=> rpcutils/main: disable rpcclient autoreconnect

api/apirouter.go, api/apiroutes.go, db/cache/addresscache.go, db/dbtypes/types.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, testutil/apiload/profiles.json
This adds to the address cache all of the history that was obtained via
DB query by `(*ChainDB).TxHistoryData`. This corresponds to the data
retrieved from the API via AJAX for the charts on the address page. e.g.:
`/api/address/{addr}/amountflow/month`, `/api/address/{addr}/types/week`, etc.
The `AddressCacheItem` `metrics` placeholder is changed to `history`, of
a new type `TxHistory` that contains all types of address history used by
the charts on the address page.
`(*AddressCache).HistoryChart` gets the specified chart from cache.
`(*AddressCache).StoreHistoryChart` stores the given chart of the
specified type in cache.
`(*ChainDB).TxHistoryData` is modified similar to other cache-wired
functions to first check the cache. For a cache miss, the cache is held
locked while the actual DB …
=> cache/dcrpg: per-address History/charts data cache

rpcutils/rpcclient_online_test.go
This fixes syntax problems, but does not fix the "testnetRPC" tests since testnet2 is gone.
As noted in the added comment, all these test should run with regnet (TODO).
=> rpcutils: fix test code, make note about regnet

gov/politeia/piclient/piclient.go
fixes #1132
Since Politeia [guarantees](https://github.com/decred/politeia/blob/master/politeiawww/api/v1/api.md#http-status-codes-and-errors) that most requests should return http status code `200 OK`. 
Any of the Politeia API endpoints request returned with another other status code is considered to be a failed request.
=> politeia/piclient: Check for valid http status code

explorer/explorerroutes.go, explorer/explorerroutes_test.go, txhelpers/txhelpers.go, views/status.tmpl
Bitcoin address recognition was removed in https://github.com/decred/dcrdata/pull/1064.
This cleans up relics from that functionality.
=> explorer: remove ExpStatusBitcoin etc.

api/apirouter.go, api/apiroutes.go, api/insight/apirouter.go, config.go, go.mod, go.sum, main.go, middleware/apimiddleware.go
GZ compression with a middleware is not always useful, especially when
a reverse proxy like nginx is in use.  This makes compression a config
setting (`--compress-api`, off by default).
This enables compression for ALL Insight API endpoints, and just verbose
and raw dcrdata API endpoints.
chi is updated to include the compression middleware rewrite.
=> apis: make compression off by default and add --compress-api

txhelpers/subsidy.go, txhelpers/subsidy_test.go
The "rotation" API attack shows that right below SQLite queries,
`txhelpers.UltimateSubsidy` dominates CPU use:
```
Profiling CPU now, will take 30 secs...
Profile dump saved to: /tmp/profile382211380
Profiling dump saved to: /tmp/profile382211380
Binary file saved to: /tmp/binary999078659
File: binary999078659
Build ID: dac764d5609000fe955fb95b2afecec454b17e47
Type: cpu
Time: Mar 15, 2019 at 8:33am (CDT)
Duration: 30.14s, Total samples = 1.38mins (275.41%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 75.69s, 91.19% of 83s total
Dropped 543 nodes (cum <= 0.41s)
Showing top 10 nodes out of 126
flat  flat%   sum%        cum   cum%
48.31s 58.20% 58.20%     48.32s 58.22%  runtime.cgocall
23.13s 27.87% 86.07%     23.32s 28.10% …
```
=> txhelpers: store previously-computed ultimate subsidy values

explorer/explorerroutes.go
This strips leading and trailing Unicode-recognized whitespaces from the search term.
Removing these characters allows pasting data that might have tabs, spaces, etc.
that were accidentally picked up when copied from somewhere else.
Return `http.StatusBadRequest` (400) for an empty search term.
=> explorer: strip leading/trailing whitespace from search

api/apirouter.go, api/apiroutes.go, api/types/apitypes.go, db/dbtypes/types.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go
Adds the /tx/{txid}/tinfo endpoint, which responds with ticket status, purchase and lottery blocks, and spending txid.
Some endpoints for testing
- immature: /api/tx/10659139fc3a4ef2e00d8539180a761b1c2d1b823645ecff5c8ffba0dc909403/tinfo?indent=1
- live: /api/tx/07f0daf8be13be8e995931afb98b725d8ef23529c26749100ef26821e8eb3025/tinfo?indent=1
- missed, not revoked: /api/tx/08b98e68e18ebb82440d07f3dc70cc8c017df1dcb639493e9b7cd356d66174ae/tinfo?indent=1
- missed, revoked: /api/tx/7405d619e673ca4bb4681951828dcf1893e4004973133ff012e30e7c182bf168/tinfo?indent=1
- voted: /api/tx/5ba836dec32969110487f857be9a59ca98898860c84f66d5497e211f525e66e4/tinfo?indent=1
- expired, not revoked: /api/tx/0974112f3f7a41b2bafbbd4c0c7bd61b9db6f9838721d82e9bc59c42e40f6da6/tinfo?indent=1
Resolves #1024
=> api: create endpoint for ticket-specific info

api/apiroutes.go, api/insight/apimiddleware.go, api/insight/apiroutes.go, api/insight/converter.go, api/types/go.mod, blockdata/blockdata.go, cmd/scanblocks/scanblocks.go, db/cache/addresscache.go, db/dcrpg/insightapi.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, db/dcrsqlite/sqlite.go, db/dcrsqlite/sync.go, explorer/websockethandlers.go, go.mod, mempool/collector.go, mempool/mempoolcache.go, mempool/mptypes.go, middleware/apimiddleware.go, rpcutils/rpcclient.go, stakedb/stakedb.go
Also have api/types/go.mod want v4.0.0-rc3 (which is not yet tagged)
After this, tag dcrdata with v4.0.0-rc3 and api/types with api/types/v1.0.1.
=> use api/types module in dcrdata

api/types/go.mod, go.mod
This adds replace statements to the main go.mod and api/types/go.mod to the local code can be used.
This also changes api/types to require v4.0.0-rc4, and dcrdata to require api/types/v1.0.2
=> use replace statements

api/types/apitypes.go, api/types/apitypes_test.go
This adds `(*TimeAPI).UnmarshalJSON`. The required input must be a JSON
integer (not a string, with quotes), as provided by
`(*TimeAPI).MarshalJSON`.
Tests are added to ensure the proper marshal and unmarshal behavior.
Constructors `NewTimeAPI` and `NewTimeAPIFromUNIX` are added.
A `(TimeAPI).UNIX` method is also added.
=> api/types: add (*TimeAPI).UnmarshalJSON and ctors

api/insight/apimiddleware.go, api/insight/apirouter.go, api/insight/apiroutes.go, api/insight/apiroutes_test.go, middleware/apimiddleware.go
Remove middleware that duplicates existing functions in the `middleware`
package.
Remove unused method receivers from most Insight middleware.
Move `PostBroadcastTxCtx` to the `middleware` package.
Create `fromToForSlice` for validating and converting `?from=A&to=B` URL
query params to slice indexes.  Add test for `fromToForSlice`.
Numerous simplifications and doc fixes.
=> insight: clean up middleware

gov/politeia/proposals.go
Current implementation has a bug that prevent any unauthorized proposal in the proposal storm db from being updated.
=> gov/politeia: Fix update for unauthorized proposals

run_tests.sh
`go test ./...` seems to be working only for the package where `run_tests.sh` scripts is located.
`go test all` runs way too many unnecessary tests. https://go-review.googlesource.com/c/go/+/134095/1/src/cmd/go/internal/test/test.go
Therefore dcrdata submodules have to be passed as arguments as `go tests ./... {dcrdata_submodules}` for all the necessary tests to be run.
=> CICD: Run tests for all dcrdata modules

db/dcrpg/pgblockchain.go, db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorerroutes_test.go, explorer/templates.go, gov/agendas/go.mod, gov/agendas/tracker.go, gov/agendas/tracker_test.go, main.go, public/js/controllers/agendas_controller.js, public/js/helpers/meters.js, public/js/helpers/vote_meter.js, public/scss/bootstrap_overrides.scss, public/scss/charts.scss, public/scss/typography.scss, views/agendas.tmpl, views/parameters.tmpl
Adds `VoteTracker`, which refreshes with new blocks to update a cache of voting-related data. VoteTracker produces a `VoteSummary`, which has fields customized for use in templates. There might be some space to integrate `VoteTracker` with `AgendaDB`.
Front end: The information is incorporated at the top of the /agendas page here, with intention to use the same data in some way on the homepage and more. To display a graphic without using the `charts.js` package (which is huge), a new `VoteMeter` class displays a simple graphic with a central value displayed using the Canvas API. It'd be good to drop `charts.js`, which is dcrdata's largest vendor package and we barely use it. `VoteMeter` is about 6 kB unminified, compared to 160 kB for a minified `charts.js`.
=> gov: implement live vote tracking

api/insight/apiroutes.go, api/insight/apiroutes_test.go
URL query paramaters "from" and "to" are zero-based indexes for
inclusive range bounds.  This corrects the computation of "to" when it
is not specified.
=> insight: fix "to" computation when not specified

api/insight/apimiddleware.go, api/insight/apirouter.go, api/insight/apiroutes.go, api/insight/converter.go, cmd/rebuilddb2/rebuilddb2.go, db/dcrpg/go.mod, db/dcrpg/go.sum, db/dcrpg/pgblockchain.go, db/dcrsqlite/apisource.go, explorer/explorer.go, main.go, mempool/collector.go, mempool/go.mod, mempool/go.sum, mempool/monitor.go, rpcutils/rpcclient.go, txhelpers/txhelpers.go
The `rpcutils` package implementation of `UnconfirmedTxnsForAddress` is convenient, but it involves many RPCs, including a full `getrawmempool`.  These changes implement `UnconfirmedTxnsForAddress` in `mempool.MempoolMonitor`, the hub for mempool data and events for the other packages.
```
rpcutils.UnconfirmedTxnsForAddress completed in 8.912882ms
(*MempoolMonitor).UnconfirmedTxnsForAddress completed in 1.462µs
```
`mempool.MempoolMonitor` now keeps an address-keyed mempool txn inventory to facilitate
fast retrieval of transactions that are relevant to specific addresses.
`txhelpers` defines new types and functions for maintaining this address-txn inventory. `(*mempool.MempoolMonitor).Refresh`, `(*mempool.MempoolMonitor).TxHandler`, and `(*mempool.MempoolDataCollector).mempoolTxns` are …
=> txhelpers and mempool: UnconfirmedTxnsForAddress

package-lock.json, package.json
Need reproducible webpack builds.
```
$  npm list --depth=0 --prod
dcrdata@1.0.0 /home/jon/github/decred/dcrdata
├── bootstrap@4.3.1
├── dompurify@1.0.10
├── lodash-es@4.17.11
└── qrcode@1.3.3
```
```
$  npm list --depth=0
dcrdata@1.0.0 /home/jon/github/decred/dcrdata
├── @babel/core@7.4.0
├── @babel/plugin-syntax-dynamic-import@7.2.0
├── @babel/preset-env@7.4.2
├── axios@0.18.0
├── babel-eslint@10.0.1
├── babel-loader@8.0.5
├── babel-polyfill@6.26.0
├── bootstrap@4.3.1
├── clean-webpack-plugin@1.0.1
├── css-loader@1.0.1
├── dompurify@1.0.10
├── eslint@5.16.0
├── eslint-config-standard@12.0.0
├── eslint-loader@2.1.2
├── eslint-plugin-import@2.16.0
├── eslint-plugin-node@8.0.1
├── eslint-plugin-promise@4.1.1
├── eslint-plugin-standard@4.0.0
├── UNMET PEER DEPENDENCY jquery@1.9.1 - 3
├── …
```
=> update packages and checking package-lock.json

config.go, db/dcrpg/indexing.go, db/dcrpg/sync.go, main.go, rpcutils/blockgate.go, rpcutils/prefetcher.go, rpcutils/rpcclient.go, rpcutils/rpcclient_online_test.go
Add rpcutils/prefetcher.go, which defines a `BlockFetcher` interface,
satisfied by `rpcclient.Client`, and the `BlockPrefetchClient`, which also
implements `BlockFetcher`.
The `BlockPrefetchClient` prefetches a certain number of blocks beyond
the last block requested.
Use `BlockPrefetchClient` in BlockGate, and thus in `(*ChainDB).SyncChainDB`.
Use `BlockFetcher` in various `rpcutils` functions.
Clean-up in sync and indexing areas.
=> rpcutils: Add a block prefetching wrapper around a RPC client.

explorer/explorerroutes.go, public/scss/nexthome.scss, views/address.tmpl, views/agenda.tmpl, views/agendas.tmpl, views/block.tmpl, views/charts.tmpl, views/disapproved.tmpl, views/explorer.tmpl, views/extras.tmpl, views/home.tmpl, views/mempool.tmpl, views/nexthome.tmpl, views/parameters.tmpl, views/proposal.tmpl, views/proposals.tmpl, views/rawtx.tmpl, views/sidechains.tmpl, views/statistics.tmpl, views/status.tmpl, views/ticketpool.tmpl, views/timelisting.tmpl, views/tx.tmpl, views/windows.tmpl
Sets the `darkBG` CSS class on the body ahead of time to prevent flashing of light mode before script loads.
I'm also sneaking this in so that user's fiat index preference can be stored and `ExchangeBot` can serve personalized results.
=> explorer: check dark mode cookie server-side

rpcutils/prefetcher.go
When the stored `next` block is the requested hash, grab the block data
BEFORE `retarget` changes `p.next` (via `fetcher` -> `RetrieveAndStoreNext`
-> `storeNext`).
=> rpcutils: fix a race in (*BlockPrefetchClient).GetBlockData

db/dcrpg/internal/system.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/system.go, db/dcrpg/upgrades.go, stakedb/stakedb.go
Running PostgreSQL with `synchronous_commit = on` is an absolute performance killer,
and a quite common configuration mistake.  However, it is safe to set it to `"off"`.
These changes check the current setting, and set it to `"off"` if it is not already set that way.
=> dcrpg: check and set synchronous_commit

api/insight/apimiddleware.go, db/dbtypes/types.go, db/dcrpg/go.mod, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/system.go, db/dcrpg/upgrades.go, explorer/explorermiddleware.go, gov/agendas/tracker_test.go, gov/politeia/types/types.go, middleware/apimiddleware.go, rpcutils/rpcclient_online_test.go, stakedb/stakedb.go, txhelpers/txhelpers.go
A single database transaction is used to insert all of a blocks
intputs, outputs, and transactions: https://github.com/decred/dcrdata/pull/1233/commits/7ebd251e8fbf9cabefff056a6c69eb40f89ba76a
Spending address rows are also inserted in a single transaction: https://github.com/decred/dcrdata/pull/1233/commits/8930afc95a5a4d96f85a5a26471d9926d08a486e
Prepare address rows and UTXO cache concurrently with stake inserts: https://github.com/decred/dcrdata/pull/1233/commits/ef3f3804558ae69dde970a6ad53dea40d17fc849
99% of the speed gains come from 7ebd251e8fbf9cabefff056a6c69eb40f89ba76a
**`[INF] PSQL: Avg. speed: 1329 tx/s, 4894 vout/s`**
```
[INF] PSQL: Processing blocks 1 to 500...
[INF] PSQL: Processing blocks 501 to 1000...
[INF] PSQL: Processing blocks 1001 to 1500...
[INF] PSQL: Processing …
```
=> dcrpg: use single transaction for all in/out/tx inserts 

config.go, main.go
This is a workaround for machines hit by https://github.com/decred/dcrdata/issues/1020
=> config: add --sqlite-max-conns=[int] switch

api/apirouter.go, api/apiroutes.go, cmd/rebuilddb2/rebuilddb2.go, db/dbtypes/types.go, db/dcrpg/go.mod, db/dcrpg/go.sum, db/dcrpg/indexing.go, db/dcrpg/internal/indexes.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_charts_test.go, db/dcrpg/queries.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go, explorer/explorerroutes.go, go.mod, go.sum, gov/politeia/proposals.go, main.go, middleware/apimiddleware.go, public/js/controllers/proposal_controller.js, public/js/helpers/chart_helper.js, public/scss/charts.scss, run_tests_with_chartests.sh, views/proposal.tmpl, views/proposals.tmpl
fixes #995 
Using a [parser tool](https://github.com/dmigwi/go-piparser) to clone, query and parse politeia's votes data pushed to github with the help of git cmd tool and relevant  proposal tokens votes data is extracted.
The votes data is stored in `proposals` and `proposal_votes` tables after the db upgrade to `v3.11.0`.
Here are the UI changes made:
**Proposals Page**
**Proposal Details Page** - The donut pie has been replaced with the following synchronized charts.
=> gov:proposals: new proposal votes charts

gov/agendas/tracker.go, gov/agendas/tracker_test.go, main.go
Fetches the stake version from the active deployments map instead of using the wire protocol version.
Fixes this bug on testnet3.
```
2019-04-15 20:31:55.429 [INF] DATD: Closing connection to dcrd.
2019-04-15 20:31:55.429 [INF] DATD: Bye!
2019-04-15 20:31:55.680 [ERR] DATD: Unable to initialize vote tracker: Vote information not found: -32603: stake version 6 does not exist
```
=> gov/agendas: Correct the usage of the stake version

gov/politeia/proposals.go, views/proposal.tmpl, views/proposals.tmpl
It will help in updating past such an error if new data exists.
```
2019-04-15 19:17:13.120 [ERR] DATD: updating proposals db failed: RetrieveProposalByToken failed: retrieving 5d9cfb07aefb338ba1b74f97de16ee651beabc851c7f2b5f790bd88aea23b3cb proposal vote status failed: request (https://proposals.decred.org/api/v1/proposals/5d9cfb07aefb338ba1b74f97de16ee651beabc851c7f2b5f790bd88aea23b3cb/votestatus) failed with status code: 400 Bad Request 
```
=> [4.1] Proposals cleanup

gov/politeia/piclient/piclient.go, gov/politeia/proposals.go, gov/politeia/types/types.go
This is a bug fix that corrects the wrong marshaling of the single proposal payload fetched.
It also adds logs to warn when empty or invalid payloads are detected.
=> [4.1] Fix the incorrect single proposal marshaling

gov/politeia/piclient/piclient.go, gov/politeia/proposals.go, gov/politeia/types/types.go, views/proposal.tmpl, views/proposals.tmpl
It also adds logs to warn when empty or invalid payloads are detected.
It will help in updating past such an error if new data exists.
```
2019-04-15 19:17:13.120 [ERR] DATD: updating proposals db failed: RetrieveProposalByToken failed: retrieving 5d9cfb07aefb338ba1b74f97de16ee651beabc851c7f2b5f790bd88aea23b3cb proposal vote status failed: request (https://proposals.decred.org/api/v1/proposals/5d9cfb07aefb338ba1b74f97de16ee651beabc851c7f2b5f790bd88aea23b3cb/votestatus) failed with status code: 400 Bad Request 
```
=> [4.0] Fix proposal update

views/extras.tmpl
This enables browsers that support `rel="preload"` to preload the fonts and svg symbols instead of waiting to process style.css.
Working: Chrome, Epiphany (probably Safari too), Firefox ([network.preload setting](https://user-images.githubusercontent.com/9373513/56443923-3db29c00-62bc-11e9-9980-e0c63a12eab1.png))
https://caniuse.com/#search=preload
**Without preload (first 200ms of page load):**
The webfonts, logo.svg, and connecting.svg are delayed for about 160 ms while the stylesheet is processed.  Also, Chrome reports the initiator is Turbolinks.
Also note that connected.svg is not loaded in this time period because it is loaded only after the websocket connects.
**With preload (first 200ms of page load):**
The webfonts, the logo.svg, and connecting.svg are loaded immediately.  Also, …
=> views: preload webfonts and svg

package-lock.json
Address node package vuln due to js-yaml: https://www.npmjs.com/advisories/813
This prevents all the malicious Decred devs from p0wning other devs.
=> npm update js-yaml

cmd/rebuilddb2/rebuilddb2.go, db/dcrpg/internal/meta.go, db/dcrpg/internal/txstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_charts_test.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go, db/dcrpg/rewind.go, db/dcrpg/sync.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go, db/dcrpg/upgrades_legacy.go, main.go
This creates a new database versioning system for the `dcrpg` package.
Resolves https://github.com/decred/dcrdata/issues/591
Prior to these changes, each table had a version, stored in the comments of the table.  This turned out to be problematic because:
1. In practice, each table should have the same version, which actually indicated a database schema. But this was violated when new tables were created.  As a result, upgrades could get messy.
2. Table comments seem to be a PostgreSQL extension and are not supported in CockroachDB.
In this PR, a new database versioning system is created that uses a "meta" table.  The structure of the meta table is as follows:
```
net_name              | text    |
currency_net          | bigint  |
best_block_height     | bigint  |
best_block_hash       | …
```
=> dcrpg: meta table versioning

gov/politeia/piclient/piclient.go, gov/politeia/proposals.go, gov/politeia/types/types.go, package-lock.json
Instead of comparing `votestatus` and `timestamp` only to check for updates, compare more `proposalInfo` fields to capture lots more changes when they happen.
```Golang
if proposal.Data.VoteStatus == statuses[0] || proposal.Data.Timestamp == val.Timestamp {
```
In the conditions above, the `Timestamp` was expected to change every time a minor change was effected on the proposal but was only found to change when the proposal author changed the proposal version.
Also Lots of other properties like `Censorship`, `Name`, `State`, `NumComments`, `StatusChangeMsg`, `CensoredDate`, `AbandonedDate`, `PublishedDate`, `Token`, `VoteStatus`, `TotalVotes` and `VoteResults` have a high likelihood of changing as the proposals moves through the various life cycle stages but were not initially considered.
=> [4.1] Compare all proposal data to check for updates

api/Insight_API_documentation.md, api/insight/apirouter.go, db/cache/charts.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/templates.go, explorer/templates_test.go, main.go, middleware/apimiddleware.go, sample-nginx.conf, views/insight_root.tmpl, views/ticketpool.tmpl
This makes a basic HTML page for the `/insight` to provide information about the Insight API on dcrdata.
The above shows "https://alpha.dcrdata.org/insight".  To support reverse proxy configurations that map requests on the root path to /insight on the backend, a middleware (`OriginalRequestURI`) is added to embed the original request URI.  This middleware allows the new Insight page handler to generate links relative to *the original client request URI*, not the host root or the request URI as known by the backend.  Again, this will happen with a reverse proxy that modifies the request URI.  For example, here is http://insight.alpha.dcrdata.org:
Note that the "API sub-path" now links to /api/status instead of /insight/api/status since the proxy prefixes all requests with /insight behind …
=> Insight root page and api redirect

db/cache/charts.go, main.go
This add a check on input height in `NewChartData`.  A minimum number of blocks for initial capacities is now `chainParams.StakeDiffWindowSize`.
Also, in main, avoid `uint32(-1)`.
=> db/cache: check input height in NewChartData

db/cache/charts.go, db/cache/charts_test.go
I'm still not certain what was the cause of the panic on master, but I think I've corrected a couple of weak spots, and added a test. 
From appearances, it appears the reorg was being attempted on a zero-length day-binned data set. This would have been possible if there was an error in `(ChartData).Lengthen`, in which case the data set would have been emptied to trigger a full refresh. I don't see the associated `Warnf` anywhere though, so it's not clear that's what happened. 
Regardless, the `Snip` length in `ReorgHandler` needed to be checked anyway.
=> cache: validate snip length and test ReorgHandler

views/extras.tmpl
The `href` for each of the `<link rel="preload"` elements was using relative paths, causing 404s when not on the home page.  This makes the `href`s use an absolute path (e.g. `/images/connecting.svg` vs `images/connecting.svg`, which would end up loading `scheme://host.tld/tx/images/connecting.svg` when on the tx page)
=> views: preload link paths must be absolute

db/cache/charts.go, db/cache/charts_test.go
Once `func (charts *ChartData) Update() {` was invoked to fetch the latest charts data update, the derived data `charts.Days` dataset wasn't updated by invoking `func (charts *ChartData) Lengthen() error {`.
Failure to invoke `func (charts *ChartData) Lengthen() error {` on data update.
- Allowed stale data to be persisted till the next system start up.
- When a fresh data query (cache .gob file missing) was run the derived data was bound to return some empty datasets thus affecting functionality of some charts.
=> charts: Update derived data on db charts data query

api/insight/apiroutes.go, config.go
config: increase default max insight addrs to 25 
insight: set limits on Insight addrs UTXOs and txns
maxInsightAddrsUTXOs limits the number of UTXOs returned by the
addrs[/{addresses}]/utxo endpoints when the {addresses} list has more
than one address. The project fund address has 263383 UTXOs at block
height 342553, and this is a ~75MB JSON payload. Set
maxInsightAddrsUTXOs to 500000.
maxInsightAddrsTxns limits the number of transactions that may be
returned by the addrs[/{addresses}]/txs endpoints when the {addresses}
list has more than one address. This limit is applied to the "to" and
"from" URL query parameters. Note that each transaction requires a
getrawtransaction RPC call to dcrd. Set maxInsightAddrsTxns to 250.
=> insight: set new limits on Insight API addrs endpoints

package-lock.json
Resolves https://github.com/decred/dcrdata/issues/1309
The node-gyp authors decided not to use tar 4.x and instead wait for the fixes backport to 2.x: https://github.com/sass/node-sass/issues/2625#issuecomment-492464554
The patched tar 2.2.2 release: https://github.com/npm/node-tar/releases/tag/v2.2.2
=> node: update node-sass>node-gyp>tar dep

api/apirouter.go, api/apiroutes.go, api/types/apitypes.go
Backport of https://github.com/decred/dcrdata/pull/1321 to `4.1-stable`.
After merging, `github.com/decred/dcrdata/api/types/v2` must be tagged with v2.1, and
dcrdata's go.mod updated to use it.
This adds a new API endpoint, `/api/status/happy`, for bottom line health checks.
The happy endpoint responds with a 503 (service unavailable) if dcrdata is not "happy".
A JSON response marshaled from the new `api/types.Happy` struct is returned
regardless of 200 (OK) or 503 (service unavailable).
An example response with HTTP response code 200:
```json
{
"happy": true,
"api_ready": true,
"tip_age": 1530,
"node_connections": 1
}
```
This may seem redundant with the `/api/status` data, but the configuration of health checks
is often very limited.  The 503 response code is returned when `"happy"` is …
=> [4.1]  /api/status/happy and periodic node connection check

package-lock.json
https://github.com/decred/dcrdata/pull/1329 for `4.1-stable`
=> [4.1] node: update tar and fstream deps

api/insight/apiroutes.go, config.go
This tweaks the Insight API's `addrs` endpoints' handling of the address list.
config: increase default max insight addrs to 25.  This is needed to support
Exodus out of the box.
insight: set limits on Insight addrs UTXOs and txns
`maxInsightAddrsUTXOs` limits the number of UTXOs returned by the
addrs[/{addresses}]/utxo endpoints when the {addresses} list has more
than one address. The project fund address has 263383 UTXOs at block
height 342553, and this is a ~75MB JSON payload. Set
`maxInsightAddrsUTXOs` to 500000.
`maxInsightAddrsTxns` limits the number of transactions that may be
returned by the addrs[/{addresses}]/txs endpoints when the {addresses}
list has more than one address. This limit is applied to the "to" and
"from" URL query parameters. Note that each transaction requires a …
=> [4.1] insight: set limits on Insight addrs UTXOs and txns 

explorer/explorerroutes.go
Backport of the URL fix that was included in https://github.com/decred/dcrdata/pull/1274 to `4.1-stable.`
StatusPage panics because `dummyRequest` has a nil `*URL`.  This give `StatusPage` and `timeoutErrorPage` the `*http.Request`.
=> [4.1] explorer: give StatusPage the  http.Request

db/cache/charts.go, db/cache/go.mod, db/dcrpg/queries.go, public/js/controllers/charts_controller.js, views/charts.tmpl
The following changes were made and UI changes are shown on the screenshot below:
1. The chart was renamed from `Network Hashrate` to `Hashrate`.
2. The previous y-Axis and legend used `K` instead of hash rate specific labeling like `TeraHash/s`, `PentaHash/s` for the legend and `Th`, `Ph` for the axis.
3. The charts cache versioning implementation was added back - It should help in managing the cache especially when its data has new structural changes whose only solution is to trigger a fresh update.
**UI Changes**
=> Hashrate chart: labeling and legend units update

pubsub/democlient/go.mod, pubsub/democlient/go.sum, pubsub/democlient/main.go, pubsub/psclient/client.go, pubsub/psclient/client_test.go, pubsub/psclient/log.go, pubsub/pubsubhub.go, pubsub/types/pubsub_types.go
This addresses https://github.com/decred/dcrdata/issues/1319
The user of the `psclient.Client` no longer has to coordinate calls to `Receive[Msg]` with requests like `Subscribe`.  `Client` runs a loop internally to manage all sends/receives.  See democlient changes.
pubsub/types: create new request and response types
psclient: monotonically increasing per-client request ID
rewrite psclient and democlient.
=> v3 of pubsub and pubsub/types

api/apirouter.go, api/apiroutes.go, api/types/apitypes.go
This adds a new API endpoint, `/api/status/happy`, for bottom line health checks.
The happy endpoint responds with a 503 (service unavailable) if dcrdata is not "happy".
A JSON response marshaled from the new `api/types.Happy` struct is returned
regardless of 200 (OK) or 503 (service unavailable).
An example response with HTTP response code 200:
```json
{
"happy": true,
"api_ready": true,
"tip_age": 1530,
"node_connections": 1
}
```
This may seem redundant with the `/api/status` data, but the configuration of health checks
is often very limited.  The 503 response code is returned when `"happy"` is `false`.
The condition for `"happy"` is `api_ready && node_connections > 0 && tip_age > 90min`.
To keep `node_connections` current, a 5 second ticker triggers an RPC and update of …
=> API: /api/status/happy and periodic node peer connection check

public/js/helpers/chart_helper.js
When dygraph bar graph has to plot too many bars in a very tiny space, too much color overlapping is distorting the actual data on display.
=> charts: Reduce the bars color overlapping

explorer/explorerroutes.go, explorer/templates.go, public/js/controllers/homepage_controller.js, views/home.tmpl
Resolves #1225 
Instead of
`Ticket Pool Size: 41,285 (100.79% of target 40,960)`
shows
`Ticket Pool Size: 41,285 (+0.79% of target 40,960)`
It takes less space, faster to read, and in case of negative number -1% is more useful than 99%
=> ticketpool: Presents the ticket pool PercentTarget as a diff from 100% target

gov/politeia/proposals.go
`after` parameter used to return old data because of the reverse chronological sorting in place but because storm db ignores entries that violate the unique constraint thus no duplicate data was stored.
`before` returns the newest updates thus its use.
Fetching the last updated proposal returned the oldest token because of incorrect retrieval of the last updated proposal token
=> Proposals: Change the reverse chronologically retrieval url parameter

db/dcrpg/queries.go, public/js/controllers/ticketpool_controller.js, views/ticketpool.tmpl
Since counting the `sstxcommitments` outputs is simpler than counting all outputs of a given ticket, the `sstxcommitment` tx count are used to represent the output count for a given ticket in the ticketpool.
**New Tickets Output Distribution Table**
=> ticketpool: Count only sstxcommitments outputs

go.mod, go.sum, gov/politeia/proposals.go
This is a backport of https://github.com/decred/dcrdata/pull/1352 to 4.1-stable.
It is presently deployed to https://explorer.dcrdata.org/proposals.
=> [4.1] Change the reverse chronologically sorting url to return new data

pubsub/democlient/go.mod, pubsub/democlient/main.go, pubsub/go.mod, pubsub/psclient/client.go, pubsub/pubsubhub.go, pubsub/types/pubsub_types.go
pubsub/types: Create a JSON-tagged `Ver` struct for sending the pubsub server version in JSON messages.
pubsub (server): Create an unexported `var version = semver.NewSemver(3, 0, 0)`, accessible via the new  `pubsub.Version() semver.Semver` function.  Recognize incoming messages with the event ID `"version"`, and respond to the client with a marshaled `pubsub/types.Ver`.
pubsub/psclient (client): Add `psclient.Version() semver.Semver`, which returns `pubsub.Version()` result. Note that the shared version indicates a module version.  On startup of a new client, a server version check is performed:
```
[INF] PSCL: Server pubsub version: 3.0.0
[DBG] PSCL: Response to  request ID=1 received. Success = true. Data: {"major":3,"minor":0,"patch":0}
```
If the server version is not compatible, …
=> pubsub: add version, and version request/response

explorer/templates.go, public/scss/themes.scss, public/scss/typography.scss, views/proposals.tmpl
Partiallyresolves(editing this so that the main issue is not closed) #1287 
add votes count and approval percentage columns in the proposals view
=> proposals: add votes count and approval percentage columns

api/apiroutes.go, db/cache/charts.go, db/cache/charts_test.go, public/js/controllers/charts_controller.js, public/js/helpers/zoom_helper.js, public/scss/_variables.scss, public/scss/charts.scss, views/charts.tmpl
All historical charts have a button that enables switching between the two x-axis types namely: Block Height and Block Time. A group button at the chart bottom was added to enable easy swapping of either of the two x-axis. Since dygraph doesn't support display of multiple x-axis the two distinct x-axes cannot not be displayed together.
No changes to the data stored in charts cache was made to enable an extra x-axis to be swapped on a chart with the same y-axis data set.
The query below allows the index of each record retrieved to be used like a `Block Height` since the query is ordered by height. Therefore no extra data is required when the bin value is set to blocks.
```sql
SelectBlockStats = `SELECT height, size, time, chainwork, numtx
FROM blocks
WHERE is_mainchain
AND height > $1 …
```
=> Charts: Dual x-axis support for all historical charts

exchanges/bot.go, exchanges/exchanges.go, exchanges/exchanges_live_test.go, exchanges/exchanges_test.go, exchanges/websocket.go
This PR is for testing. The exchanges package seems to have some issues lately that may or may not be related to recent work to implement websockets. This PR effectively just adds some trace output, though the foundations are being laid for some more sophisticated error monitoring. 
If you are testing, run this PR with `--debuglevel=XBOT=trace` on dcrdata, and `--loglevel=trace` on rateserver. Feel free to give me your logs.
=> debug exchanges

explorer/websocket.go, pubsub/websocket.go
This resolves shutdown races that could cause panics in rare cases.
There are multiple goroutines that send to `HubRelay` in both the pubsub
and explorer packages.  The `WebsocketHub` is the receiver, but there are
other senders. Closing the channel is not necessary to terminate the run
loops.  Since the senders have alternate select cases to prevent indefinitely
blocking, the solution is to not close the channel.
Also, to quit the run loops, `Stop()` now closes `quitWSHandler` instead of
sending on it.  There are NO senders, only a receiver.
=> pubsub/explorer: leave the HubRelay channels opened

views/proposals.tmpl
Added a tooltip to the proposal vote status column for the entries showing the approval percentage.
Added the `In Discussion` vote status to include the period when the proposal has been approved but no votes exist yet.
=> proposal listing: Add tooltip to the vote status

README.md, cmd/rebuilddb2/rebuilddb2.go, db/dcrpg/README.md, db/dcrpg/indexing.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/common.go, db/dcrpg/internal/meta.go, db/dcrpg/internal/rewind.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/queries.go, db/dcrpg/rewind.go, db/dcrpg/sync.go, db/dcrpg/tables.go, db/dcrpg/upgrades_legacy.go, main.go
<s>Resolves</s> Working toward https://github.com/decred/dcrdata/issues/1291, the following changes are made to support CockroachDB (crdb):
- Detecting use of cockroach.
- Removal of custom PostgreSQL types (i.e. `vin_t` and `vout_t`) and related code since crdb does not support them.
- Not erroring out when checking PostgreSQL-specific information (e.g. `synchronous_commit` and almost all the `pg_settings` dumped in the table at startup).
- Setting the `sql_sequence` SERIAL operating mode since by default `SERIAL` type columns in crdb do not create a sequence.
- Empty arrays made using the `ARRAY[]` constructor in CockroachDB require type _annotation_ (e.g. `ARRAY[]:::BIGINT[]` with ***three*** `:` characters for annotation instead of conversion), a concept that does not exist in …
=> CockroachDB support

api/insight/apiroutes.go, api/insight/apiroutes_test.go, api/types/go.mod, api/types/go.sum, api/types/insightapitypes.go, blockdata/go.mod, db/cache/addresscache.go, db/cache/addresscache_test.go, db/cache/go.mod, db/cache/go.sum, db/dbtypes/types.go, db/dcrpg/insightapi.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, dev/heap_in_use.m
The Insight API's `/addr/{address}/utxo` endpoint can consume excessive memory
for addresses with many UTXOs.  This imposes a limit on the number of "in-flight"
UTXOs to restrict how much memory can be consumed at the request of a client.
The `.../utxo` endpoint is handed by `(*InsightApi).getAddressesTxnOutput`, to which
these edits add in-flight UTXO counting and limiting.  To do this, a new field is added to
`InsightApi` called `inflightUTXOs` that tracks how many UTXOs are currently loaded
from DB queries by the `getAddressesTxnOutput` method.
Limiting is implemented by:
1. Restricting the number of address UTXO queries to one (1) concurrent request with a `Mutex`.
2. Atomically updating the `inflightUTXOs` counter while the lock is still held.
3. Checking if the counter is over a …
=> db/{cache,dcrpg}: improved memory management

public/js/controllers/status_controller.js
The "redirecting in 20 seconds" function keeps redirecting to the homepage every couple of seconds (until you close the tab and open a new one) after the db sync is completed.
=> sync: Disable multiple home page redirects

api/apiroutes.go, config.go, config_test.go, db/dbtypes/go.sum, db/dcrpg/pgblockchain.go, explorer/explorer.go, explorer/explorerroutes.go, main.go, mempool/go.sum
A new flag to disable Piparser and Politea API query is added.
`--disable-piparser` ensures that `/proposals` and `/proposal` page returns:
The API returns:
```bash
$ curl http://localhost:7777/api/proposal/a4f2a91c8589b2e5a955798d6c0f4f77f2eec13b62063c5f4102c21913dcaf32 
piparser is disabled.
```
Fixes #1374
=> piparser: Add piparser disable flag

mempool/monitor.go, txhelpers/txhelpers.go
Fees computed for mempool transactions in `(*MempoolMonitor).TxHandler` were not using the actual values of the previous outputs consumed by the inputs.  This gets the values while getting the addresses in `txhelpers.TxPrevOutsByAddr`.  The values is a new output of `txhelpers.TxPrevOutsByAddr`.
=> mempool: set inputs' values when getting prevout addresses

pubsub/pubsubhub.go, txhelpers/txhelpers.go
This PR was split from https://github.com/decred/dcrdata/pull/1385
coinbase transactions were included in the address subscriptions, and
this also includes coinbase in `newtxs`.
txhelpers: add `MsgTxToHex` (reverse of `MsgTxFromHex`).
`(*PubSubHub).Store` only needs the coinbase tx size
=> pubsub: broadcast newtxs including coinbase

rpcutils/rpcclient.go
When golangci-lint updates, it will catch this.
=> spelling: retrive --> retrieve

db/dcrpg/pgblockchain.go
On the /address page, unconfirmed transactions "funding" the address were not set as `IsFunding=true`, causing the incorrect display when the "All" or "Credits" views were selected.
Before (oops, definitely not an sstxcommitment)
After
=> dcrpg: unconfirmed txs funding an address were not labeled funding

explorer/explorer.go, explorer/explorerroutes.go, explorer/templates.go, public/js/controllers/address_controller.js, views/address.tmpl, views/extras.tmpl
Three main chainges:
* views: Reduce byte size of `addressTable` template html.
Also avoid the unneeded template if and range variables.
* explorer: reduce max address rows
* explorer: use `strings.Builder` instead of `bytes.Buffer`
In `(*templates).execTemplateToString`, use `strings.Builder` instead of
`bytes.Buffer` to avoid an unnecessary copy when calling `String()`.
TODO: look into preallocating its buffer.
=> views/explorer: improve address page memory utilization

db/dcrpg/go.mod, db/dcrsqlite/go.mod, go.mod, mempool/go.mod, stakedb/go.mod
To be tagged as rpcutils/v1.2.0 as per https://github.com/decred/dcrdata/issues/1379
=> prepare for rpcutils v1.2.0

README.md
This should not be merged until 5.0 is ready for release.  **Do not forget to bump the version in version.go before tagging!**
=> update README.md for 5.0 release

db/dcrpg/pgblockchain.go
When detecting an empty database, only checking for the "blocks" table
since some of the tables are created by schema upgrades (e.g.
"proposal_votes").
this will bump `dcrpg` from v3.0.0 to v3.0.1
=> dcrpg: check for an empty database via the blocks table only

api/insight/socket.io.go, blockdata/go.mod, db/dcrpg/go.mod, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_common_test.go, db/dcrsqlite/apisource_charts_test.go, db/dcrsqlite/chainmonitor.go, db/dcrsqlite/go.mod, db/dcrsqlite/sqlite.go, db/dcrsqlite/sync.go, dcrrates/rateserver/go.mod, exchanges/go.mod, explorer/explorer.go, go.mod, go.sum, log.go, main.go, middleware/apimiddleware.go, pubsub/democlient/go.mod, pubsub/go.mod, pubsub/pubsubhub.go, testutil/dbconfig/go.mod, testutil/dbload/go.mod, testutil/dbload/main.go
After merge, tag the following:
- gov v1.0.1
- middleware v2.2.0
- exchanges v2.0.1 - NOTE: only updated dcrdata and rateserver deps!
- blockdata - v3.0.0 (major from v2 to v3)
- testutil/dbconfig - v2.0.0 (major from v1 to v2)
- cache - v2.1.0 - before dcrpg
After this commit is merged, update and tag:
- pubsub v2.0.1 (updated for blockdata major bump)
- db/dcrpg v3.0.2
- db/dcrsqlite v3.0.1
=> mod updates

db/dcrpg/go.sum, db/dcrsqlite/go.sum, dcrrates/rateserver/go.sum, pubsub/go.sum, testutil/dbload/go.sum
Given the newly tagged modules (blockdata/v3, cache/v2, dbconfig/v2, and exchanges), tidy the dependents.
After this the following modules are ready to tag: pubsub@2.0.1, db/dcrsqlite@v3.0.1 and db/dcrpg@v3.0.2
=> tidy: dbload, rateserver, dcrsqlite, dcrpg

api/insight/apiroutes.go, db/dcrpg/insightapi.go, db/dcrpg/pgblockchain_fullpgdb_test.go
The Insight API endpoints `/api/addr[s]/{address}[/txs]` should include spending transactions as well as funding.
Also include a test for `(*ChainDB).AddressRowsMerged` to ensure it includes both funding and spending.
=> dcrpg: InsightAddressTransactions should include spending

api/insight/apiroutes.go
For unconfirmed transactions, this sets a non-zero time value for the following Insight API endpoints:
- `/insight/api/addrs/{address}/txs`
- `/insight/api/txs?address={address}`
Note that this sets the `"time"` JSON value for unconfirmed transactions only. After confirmation, both `"time"` and `"blocktime"` will be set to the value from the `getrawtransaction` RPC (the mempool time is no longer known).
=> insight: set time with MempoolTime from mempool tx store

views/proposals.tmpl
Resolves #1382 
1. Adds tooltip for all vote statuses - this is because of the reduced text in the mobile form
2. For the mobile view:
- Shortens `Vote count` and `Proposal Vote status` column titles
- Shortens status percentages to just the percent
- Shortens `Abandoned` and `In Discussion` which get expanded by the tooltip
=> proposals page: make page mobile friendly

public/js/controllers/menu_controller.js, public/scss/navigation.scss, public/scss/themes.scss, views/extras.tmpl
Firefox appears not to propagate click and hover events on disabled buttons, so this works around it.
=> explorer: fix darkmode on firefox

api/insight/converter.go, api/types/insightapitypes.go
`Vout` and `Sequence` should not be omitted when zero. Instead, use a nil
pointer to omit them.
`Value` and `ValueSat` never need be omitted.
These changes require a *major* version bump to the api/types module.
=> api/types: do not omit zero-value InsightVin.Vout

api/insight/converter.go, db/dcrpg/insightapi.go, db/dcrpg/queries.go
For non-coinbase/stakebase inputs, the previous outpoint itself may be
in mempool, in which case it is necessary to retrieve the inputs' txns
and decode the pkScript.
In addition to the above fix, which uses `txhelpers.OutPointAddressesFromString`,
amount summation is performed in integers rather than floats, and fee computation
is now correct for both coinbase and stakebase (vote) transactions.
=> insight: DcrToInsightTxns can RPC for prevout addresses

api/insight/apirouter.go, api/insight/apiroutes.go, db/dcrpg/insightapi.go, middleware/apimiddleware.go
The `pageNum` URL query param was being ignored with the `/txs` endpoint.
This checks for the `pageNum` parameter and goes to the correct page of
transactions.
This also fixes the computation of the `pagesTotal` JSON response field,
which previously was set to the total number of transactions rather than
than the number of pages.
Resolves https://github.com/decred/dcrdata/issues/1459
=> insight: add pageNum middleware and use in /txs endpoint

api/insight/apimiddleware.go, api/insight/apiroutes.go
The PostAddrsTxsCtx middleware processes parameters given in the POST
request body for an addrs endpoint. While the addresses list, "addrs",
must be in the POST body JSON, the other parameters may be specified
as URL queries. POST body values take priority.
e.g. `curl -s -X POST "http://127.0.0.1:7777/insight/api/addrs/txs?noScriptSig=0&noAsm=0&noSpent=0&from=0&to=25" -H 'Cache-Control: no-cache' -H 'Content-Type: application/json' -d '{"addrs":"DsTxcEnumw212AEjG2tfKoPA5nXBfWng2VG"}'`
=> insight: also check URL queries for params in PostAddrsTxsCtx middleware

gov/politeia/proposals.go, gov/politeia/proposals_test.go, gov/politeia/types/types.go
This PR fixes two bugs:
1. Fixes #1441 
2. The [vetted proposals(/api/v1/proposals/vetted)](https://github.com/decred/politeia/blob/master/politeiawww/api/www/v1/api.md#vetted) URL returns a snapshot of most recent proposals to be added in Politeia. This implies that `?after=` should be used when running a fresh sync and `?before=` when fetching new updates.
Param `before=` works like `next=` and `after=` like `previous=` based on politeia usage.
=> gov/politeia: Manage duplicate proposal ref id instances

explorer/explorerroutes.go, views/home.tmpl
Resolves #1457
Resolves #992
- Adds an extra row in Blocks section
- Makes the 2 columns flexbox in order to evenly distribute their content
- Removes bottom margin from Distribution section so it aligns with end of the column
Full desktop width
Width 900
Width 864
=> Align section heights of the homepage

explorer/explorerroutes.go, views/proposals.tmpl
The following UI changes were made;
- The previous tooltip on the proposals vote status was found not to be that informative as anticipated. Adding the word `approval` was found to be effective. The approval percentage description was highlighted in grey for all status with a percentage.
- Column  Title/Proposal Name was combined with Author column.
- The proposal sync times status was shifted from bottom center to top just after the page title.
- More description about the Time remaining was added to the `In progress` vote status cell.
- The vote count for all abandoned proposals shows `__` instead of 0.
=> proposals page: Tweak the UI

public/js/controllers/charts_controller.js
=> explorer: reformat unminted legend value in charts

go.mod
Most of the modules had a major version bump to use the new `jsonrpc/types` dcrd package.
See the diff for the following commit range to see what was changed before this: https://github.com/decred/dcrdata/compare/2ca45e7c17e6962d4a0aff3c3fd35d6f10bdbe85..d6b240d52b934a13f00718eef6cbf8a63d2305ff
=> restore replace statements for dcrdata

db/cache/addresscache.go, db/dcrpg/pgblockchain.go
Before updating the balance with unconfirmed transaction information,
the AddressData balance struct should be copied. Previously only the
pointer to the cached balance struct was being copied.
Resolves https://github.com/decred/dcrdata/issues/1475
=> dcrpg: AddressData should copy the cached AddressBalance

.gitignore, testutil/dbconfig/config.go, testutil/dbconfig/config_test.go
Since the file is scanned several bytes at a time, my custom token scanner using `LastIndex(` function was checking the last occurrence of `;\n` characters in the chunk already scanned.
`Index(` now returns the first occurrence of `;\n` in the scanned chunk thus you can not debug the tests.
=> Run each testutil query individually

api/insight/socket.io.go
By default, the socket.io server is limited to 1000 connections. This increases it to 16384.  Note that scaling higher may be achieved by adding more backends.  This limit may be made configurable in future work, but it is hard coded for a patch release to dcrdata 5.0.
These edits also supplement the socket.io log messages to give the current connected user count on each connect and disconnect event.
=> insight: count client connections and set max to 16384

README.md
This updates the releasees table with dcrd RPC server info.
Also add /status/happy to the API endpoint table.
=> README: update releases table with dcrd RPC server info

public/js/controllers/market_controller.js, public/js/helpers/humanize_helper.js
Resolves #1484 
Modifies the depth chart gap display to show values in BTC, fiat, and percent, where percent is taken as (gapWidth/midGap*100).
Adds negative value support to `humanize.threeSigFigs`.
=> explorer: market: add fiat and percent values to the market depth gap

views/home.tmpl
Resolves #1478
Adds chart links to already existing data titles.
1. Ticket Pool Size -> /charts?chart=ticket-pool-size
2. Total Staked DCR -> /charts?chart=stake-participation
3. Hashrate -> /charts?chart=hashrate
4. Total Coin Supply -> /charts?chart=coin-supply
/ticketpool was suggested for \# 1, but I think that the ticket pool size chart is more fitting for the label.
=> explorer: home: add more chart links to homepage data titles

views/proposals.tmpl
Resolves #1510
Not sure about the dark mode tooltip text color though
=> proposals: add voting not started status

db/cache/charts.go, db/cache/charts_test.go, db/dcrpg/pgblockchain_charts_test.go, public/js/controllers/charts_controller.js
Changes the /api/chart responses from JSON object keys of x,y,z to custom keys. Updates the charts controller to use the new scheme. Removed that time array from block-binned data with axis=height, cutting half off of those response sizes.
=> explorer: charts: custom keyed chart responses. refactor controller

go.mod, go.sum
The current gops master uses modules properly and removes the vendor folder.
=> Update github.com/google/gops to latest master, 

dcrrates/go.mod, dcrrates/go.sum, go.mod, go.sum, pubsub/go.mod, pubsub/go.sum
addressing http2 vulnerability: https://github.com/golang/go/issues/33606
It's not clear if the affected code hits our imports, but update to be safe.
=> update x/net for http2 exploit fix

api/apirouter.go, explorer/explorer.go, go.mod, go.sum
github.com/rs/cors v1.7.0 allows specifying a custom logger.  This updates to cors v1.7.0 and uses our loggers in both the api and explorer routers.
=> use our logger with the cors middleware v1.7.0

api/types/go.mod, blockdata/go.mod, db/cache/go.mod, db/dbtypes/go.mod, db/dcrpg/chkdcrpg/go.mod, db/dcrpg/go.mod, dcrrates/go.mod, exchanges/go.mod, explorer/types/go.mod, go.mod, gov/go.mod, mempool/go.mod, middleware/go.mod, pubsub/go.mod, pubsub/types/go.mod, rpcutils/go.mod, semver/go.mod, stakedb/go.mod, testutil/dbconfig/go.mod, testutil/dbload/go.mod, txhelpers/go.mod
The reason for keeping these updated with latest-1 is that these version lines in go.mod apparently can also activate certain go features, according to the [Go 1.13 beta release notes](https://tip.golang.org/doc/go1.13#language):
> If your code uses modules and your go.mod files specifies a language version, be sure it is set to at least 1.13 to get access to these language changes. You can do this by editing the go.mod file directly, or you can run go mod edit -go=1.13.
I do not know of any such features that are enabled with `go 1.12`, but updating go.mod in this way should be done on each new release.
=> require at least go 1.12 in each go.mod

go.mod, go.sum
Go 1.13 is more strict when it comes to validating module pseudo-versions.  There are four transitive dependencies with invalid pseudo-versions that must be replaced as described at https://tip.golang.org/doc/go1.13#version-validation
```
go: github.com/decred/dcrdata/gov/v2@v2.0.2 requires
github.com/decred/politeia@v0.0.0-20190716200512-2a928f2c2084 requires
github.com/marcopeereboom/sbox@v0.0.0-20190125180204-32a7c85e429a requires
github.com/golangci/golangci-lint@v1.13.1 requires
github.com/go-critic/go-critic@v0.0.0-20181204210945-0af0999fabfb: invalid pseudo-version: does not match version-control timestamp (2019-01-08T19:27:14Z)
github.com/golangci/gofmt@v0.0.0-20181105071733-0b8337e80d98: invalid pseudo-version: does not match version-control timestamp (2018-12-22T12:35:16Z) …
```
=> deal with invalid module pseudo-versions in transitive deps

dcrrates/rateserver/go.mod, exchanges/exchanges.go, exchanges/go.mod
Adds a progressive reconnection delay, so even persistent errors can be recovered. Fixes a bug where the error counter was not being reset.
=> exchanges: better websocket error handling and reconnect logic

api/insight/socket.io.go
Insight Socket.io users who are subscribed to an address "room" previously only got tx event notifications if the relevant address was paid to by an output.  It seems that the address room should trigger event notifications if the address apears in one of the previous outputs for one of the inputs of a new transaction.
Note that this also prevents multiple duplicate notifications for the same tx if the address appears in multiple places (multiple inputs, outputs, or both).
=> insight: socket.io address room subs apply to prevouts too

db/cache/addresscache.go, db/cache/charts.go, db/dcrpg/indexing.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/tables.go, exchanges/exchanges.go, explorer/types/explorertypes.go, gov/politeia/types/types.go, middleware/apimiddleware.go, notification/notifier.go, notification/notifier_test.go
In addition to lots of docs clean up, this PR removes two exported functions from the `dcrpg` package:
- `RetrieveFundingTxsByTx`, unused internally and documented with `// TODO: this does not appear correct.`
- `(*ChainDB).AddressTransactionRawDetails`, unused internally and documented with `// TODO: finish`.
=> doc and naming cleanup

db/cache/charts.go, db/cache/charts_test.go
This seems to be the solution, though I still don't know what caused the bug to suddenly manifest long after the the cache branch was merged. Regardless, the tests should have covered repeated day increments anyway, and now they do.
=> cache: fix dupe-day bug in chart cache

config.go, log.go
This allows user control of the number of zipped log files the log
rotator will retain. The default is now 16.
This also increases log size threshold for zipping to ~32MB.
=> config: Add max-log-zips config setting.

pubsub/pubsubhub.go, pubsub/websocket.go, sample-dcrdata.conf
When sending a signal to a pubsub client (i.e. `*spoke <- hubMsg`) and
the channel buffer is full, that does not mean the client is dead.
Instead, block the send unless `client.killed` is closed (when its
`WebSocketHandler` returns after both send and receive loops have
returned). There is no longer a `default` case.
Assign each client a random id, and add more logging around address messages.
Remove `SQLT` log subsystem from sample-dcrdata.conf
Add timeout for sends on the `hubSpoke` message channel send to
catch programmer error that could lead to deadlock.
=> pubsub: fix possible dropped messages

db/dcrpg/pgblockchain.go, explorer/explorer.go, gov/agendas/deployments.go, gov/agendas/deployments_test.go, gov/agendas/tracker.go, gov/agendas/tracker_test.go, main.go, public/js/controllers/agenda_controller.js, public/js/helpers/meters.js, views/agenda.tmpl, views/agendas.tmpl, views/proposals.tmpl
This eliminates the use of `chaincfg.Params.ConsensusDeployments` for determining the range of valid stake versions.  There is no reason to have this be compile time information when it can be figured out via `getvoteinfo`:
```
[DBG] AGDB: Stake version 4: [sdiffalgorithm lnsupport]
[DBG] AGDB: Stake version 5: [lnfeatures]
[DBG] AGDB: Stake version 6: [fixlnseqlocks]
[DBG] AGDB: Stake version 7: [headercommitments]
```
This also fixes a few bugs:
- In the agendas_controller, `Meter.drawIndicator`, and thus `ProgressMeter.draw` were broken because `Meter` was trying to reference `super`.
- The agendas table was in no particular order.  It is now ordered by vote version, then ID.
- Agenda votes in the defined state (yet to begin voting) threw JS errors from cumulativeVoteChoicesData and …
=> gov/agendas: do not use compiled ConcensusDeployments

db/dcrpg/pgblockchain.go, explorer/explorer.go, go.mod, gov/agendas/deployments.go, gov/agendas/deployments_test.go, gov/agendas/tracker.go, gov/agendas/tracker_test.go, main.go, public/js/controllers/agenda_controller.js, public/js/helpers/meters.js, views/agenda.tmpl, views/agendas.tmpl, views/proposals.tmpl
This is the backport of https://github.com/decred/dcrdata/pull/1586.
This eliminates the use of `chaincfg.Params.ConsensusDeployments` for determining the range of valid stake versions.  There is no reason to have this be compile time information when it can be figured out via `getvoteinfo`:
```
[DBG] AGDB: Stake version 4: [sdiffalgorithm lnsupport]
[DBG] AGDB: Stake version 5: [lnfeatures]
[DBG] AGDB: Stake version 6: [fixlnseqlocks]
[DBG] AGDB: Stake version 7: [headercommitments]
```
This also fixes a few bugs:
- In the agendas_controller, `Meter.drawIndicator`, and thus `ProgressMeter.draw` were broken because `Meter` was trying to reference `super`.
- The agendas table was in no particular order.  It is now ordered by vote version, then ID.
- Agenda votes in the defined state (yet …
=> [5.1] get valid vote versions via RPC

api/apiroutes.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go
Uses new queries for selecting ranges of API blocks. The query methods now bypass the block cache, but are much faster. 
Resolves #1523
=> api,pg: faster block range API queries

README.md
We're running with PG 12 in production now.
=> Note PostgreSQL 12.x support

blockdata/chainmonitor.go, blockdata/datasaver.go, db/cache/charts.go, db/dcrpg/indexing.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/indexes.go, db/dcrpg/pgblockchain.go, db/dcrpg/tables.go, db/dcrpg/upgrades.go, explorer/explorer.go, explorer/templates.go, gov/politeia/proposals.go, main.go, notification/notifier.go
**WARNING: This PR now updates the dcrpg table scheme from 1.2.0 to 1.3.0.**
This PR is meant to address a number of inefficiencies with new block handling.
`Notifier.processBlock()` has been taking between 10-20 seconds on production
servers, which is far too long.  For reference, on my workstation it took about 1.6
seconds, which is also longer than I would expect.
- Put `PubSubHub`'s `Store` before `explorerUI`'s since `explorerUI` launches
many computationally expensive tasks, which aren't required for downstream
block update handling.
- Make chart's `TriggerUpdate` run async.  `blockdata.BlockTrigger` now has an
`Async` `bool` field for this purpose.
- Log timing of each `Store` call in `(*chainMonitor).ConnectBlock`.
- Prevent concurrent calls to `(*ChartData).Update()`, which could …
=> speed up new block ntfn and storage handling

public/js/controllers/charts_controller.js
Before:
After:
Note that this also fixes the legend, which had ticket pool value *1e8, and the huge percentage:
=> fix stake participation data scale

db/dcrpg/internal/stakestmts.go
This constrains the agenda votes retrieval query to only votes in mainchain blocks.
Resolves https://github.com/decred/dcrdata/issues/1627
**Before**
**After**
=> dcrpg: only count mainchain votes in agenda votes queries

explorer/templates.go
Previously the home page would just say "remaining" when the ticket price window count reached 144 of 144.  This is the number of blocks mined in the current ticket price window.  This could be changed to stop at 143, proceeding to 0 next, but for now this fixes the time remaining when the entire ticket price window has been mined.
=> when time remaining is 0, show "imminent"

config.go, go.mod, main.go, middleware/apimiddleware.go, sample-nginx.conf
This adds a middleware to set Server in the HTTP response header. This is helpful to deal with reverse proxies like nginx that just set `Server: nginx` (or worse, with the entire version string).
=> set server header

api/insight/apiroutes.go, db/dbtypes/extraction.go, db/dbtypes/types.go, db/dcrpg/indexing.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/indexes.go, db/dcrpg/internal/rewind.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_fullpgdb_test.go, db/dcrpg/queries.go, db/dcrpg/rewind.go, db/dcrpg/sync.go, db/dcrpg/upgrades.go, txhelpers/txhelpers.go
This upgrades the database scheme from 5 to 6 (specifically, v1.5.1 -> v1.6.0).
- add `vouts.mixed` (BOOLEAN), true for outputs of mix transactions, and the stake transactions that spend them.
- add `vouts.spend_tx_row_id` (INT8) referencing the row ID (PK) in the transactions table, of the spending transaction, default is NULL
=> dcrpg: add vouts.mixed and vouts.spend_tx_row_id

pubsub/democlient/go.mod, pubsub/democlient/go.sum, pubsub/democlient/main.go, pubsub/psclient/client.go, pubsub/pubsubhub.go, pubsub/websocket.go, pubsub/websocket_test.go
The following changes are made, which effectively require the client to receive pings from the server at the interval the server sends them otherwise the client will shutdown assuming the connection has died.  The clients no longer have to `Ping` at the application level to detect when the connection is lost.  And the server's outgoing pings are used to clean up dead clients.
* Fix the server->client pings that were supposed to be sent automatically to all clients since the ping subscription was removed.
* Export `pubsub.PingInterval`, the server's ping interval, and set it to 30 seconds.
* In the client (`psclient`), set the default read time out to `pubsub.PingInterval * 10 / 9`, although this is still configurable by via `psclient.Opts`.
* **A read timeout in the client's receive loop …
=> pubsub,psclient: fix server->client pings and require them in client

go.mod, pubsub/democlient/go.mod, pubsub/democlient/go.sum, pubsub/democlient/main.go, pubsub/psclient/client.go, pubsub/pubsubhub.go, pubsub/websocket.go, pubsub/websocket_test.go
Backport of https://github.com/decred/dcrdata/pull/1645 for 5.2-stable.
The following changes are made, which effectively require the client to receive pings from the server at the interval the server sends them otherwise the client will shutdown assuming the connection has died.  The clients no longer have to `Ping` at the application level to detect when the connection is lost.  And the server's outgoing pings are used to clean up dead clients.
* Fix the server->client pings that were supposed to be sent automatically to all clients since the ping subscription was removed.
* Export `pubsub.PingInterval`, the server's ping interval, and set it to 30 seconds.
* In the client (`psclient`), set the default read time out to `pubsub.PingInterval * 10 / 9`, although this is still configurable …
=> [5.2] pubsub,psclient: fix server->client pings and require them in client

dev/build.sh
The SCSS files aren't part of the hosted assets, so this excludes them from the zipping in dev/build.sh.
This also excludes gz, png, and woff2 since they are incompressible. Some of the woff files do compress a bit however, so those are not ignored in the zipping.  The cleanup commands are updated to remove previously-zipped files that are no longer zipped.
=> limit asset zip further, excluding scss, png, and woff2

config.go, explorer/explorer.go, main.go, sample-dcrdata.conf, views/extras.tmpl
Display configurable Onion link in the footer.
Solves #1624
=> Onion v2 address configuration option and footer link

views/extras.tmpl
This was live-demoed for a while, but not committed.  This gets rid of the "Explore Blockchain" div that wastes so much space.
Resolves issue https://github.com/decred/dcrdata/issues/1607
=> views: remove the Explore Block chain div that wastes space

db/dcrpg/queries.go, db/dcrpg/upgrades.go
The index on vouts.spend_tx_row_id should have been created as part of a previous upgrade.  Instead, the startup index check detected that it was missing and reindexed everything.  This change just creates the index, if it does not already exist.
=> dcrpg: create the vouts.spend_tx_row_id index

views/block.tmpl
Replaces PR https://github.com/decred/dcrdata/pull/1620
- There was a missing `</td>` tag that is fixed.
- Switch to tabs to be consistent with extras.html (and use fewer chars and allow IDE set indent depth)
- Eat whitespace in template elements (`{- .adsf -}`)
Space savings is relatively minor.
- Before: block.tmpl 19127 bytes / block.tmpl.gz 2678 bytes
- After: block.tmpl 13013 bytes / block.tmpl.gz 2417
The generated html is however much cleaner and more consistently formatted, with a couple tag fixes.
=> cleanup blocks html template - whitespace, missing tags, indentation

explorer/explorer.go, explorer/explorerroutes.go, gov/agendas/deployments.go, gov/agendas/deployments_test.go, main.go
Disables `VoteTracker` and `AgendaDB` when simnet is in use. `VoteTracker` is not initialized, and `AgendaDB` has reasonable return values from exported functions.
=> gov: fix simnet agenda db and vote tracking

db/dbtypes/types.go, explorer/templates.go, explorer/types/explorertypes.go, public/js/controllers/blocklist_controller.js, public/js/helpers/humanize_helper.js, views/agendas.tmpl, views/explorer.tmpl, views/extras.tmpl
Moved timezone strings from timestamps to column headers in table views in order to clean them up.
Closes #1614
=> Timestamp cleanup in table views

explorer/explorer.go, explorer/explorerroutes.go, explorer/types/explorertypes.go, pubsub/pubsubhub.go, views/charts.tmpl
This fixes the charts page's target ticket pool size, which was showing ticket expiry in blocks. This must have slipped in because on mainnet these are equal values although their units are different and need not be the same value.
In `(*explorerUI).Charts` get target pool size from `exp.pageData.HomeInfo.PoolInfo.Target`, and pass to page template.
`explorer/types`: change `TicketPoolInfo.Target` from `uint16` to `uint32`.
=> explorer,views: fix charts page target ticket pool size

public/js/controllers/charts_controller.js, views/charts.tmpl
=> ticket-charts: add smooth mode switch

explorer/explorerroutes.go, views/explorer.tmpl, views/timelisting.tmpl, views/windows.tmpl
Here is the bug fix report for issue [1629](https://github.com/decred/dcrdata/issues/1629)
- Removed the pagination option for maximum number of rows per page with less than 10 rows, because it was greyed out and not selectable.
- Ordered the pagination options for maximum number of rows per page numerically.
- Removed the 144 rows per page on pagination options, to prevent overlapping of windows.
___OTHER BUGS ENCOUNTERED___
___Incorrect rows count on /years page___
_Steps to reproduce_:
Go to the table's top right on the [/years](https://explorer.planetdecred.org/years) page.
_Expected result_:
`1 – 5 of 5 rows` due to the 5 rows available.
_Actual result_:
`1 – 5 of 4 rows` despite having 5 rows.
_Cause_:
Data categorized per year which does not align with count of years since the …
=> Pagination selector and incorrect row count

db/cache/charts.go, public/js/controllers/charts_controller.js, views/charts.tmpl
This removes the unused chainparams field that, and tweaks some chart wording:
- Anonymity Set -> Mixed Coins (as per matrix discussion)
- Coinjoins y axis label -> Mix Rate
=> Mix chart tweaks

public/js/controllers/address_controller.js, public/js/controllers/agenda_controller.js, public/js/controllers/charts_controller.js, public/js/controllers/proposal_controller.js, public/js/helpers/humanize_helper.js
Closes #1681 
This PR updated the legend formatter of the chart on all the pages to show date in YYYY-MM-DD format. This include the charts on the main chart page, address, proposal and agenda page.
huminzie.date function is updated to accept a third parameter for hiding the H:i:s part of the date string
=> Show date in YYYY-MM-DD format on chart legends

public/js/controllers/address_controller.js, views/address.tmpl
Closes #1684 
This PR resolved the issue of chart loading indicator spinning forever on dummy address pages.
=> Fix chart loading indicator spinning forever

public/js/helpers/humanize_helper.js
Closes #1682 
This PR adds 0 to the left of minute and second time units that are less than 10.
=> Show double-digit numbers for non-leading time units

explorer/explorer.go, explorer/explorerroutes.go, main.go, public/js/controllers/attackcost_controller.js, public/js/helpers/chart_helper.js, public/scss/application.scss, public/scss/attackcost.scss, public/scss/charts.scss, views/attackcost.tmpl, views/extras.tmpl
Fix #1022 
This is a replacement for #1617 
It is a continuation of work done by other developers on the 51% attack cost.
This PR adds a page for majority attack cost calculation for both internal and external attack type using network hashrate, ticket price and ticket pool size. 
The user has the ability to adjust parameters like attack time, electricity cost, exchange rate and mining device, and see the attack cost in US dollar for every selected set of options.
=> 51% attack cost page

views/proposal.tmpl
Fix for [#1671](https://github.com/decred/dcrdata/issues/1671)
Added voter turnout (% of eligible tickets that voted) on the individual [proposal](https://explorer.planetdecred.org/proposal/decred-europe-marketing-and-events-proposal) pages
=> Percentage turnout of voters on the proposal page

views/mempool.tmpl
Fix for [#1680](https://github.com/decred/dcrdata/issues/1680)
mempool: small fee rate are displayed in scientific notation instead of the standard 8-decimal notation
_Steps to reproduce_
Go to [mempool](https://explorer.planetdecred.org/mempool) page
_Expected results_
Standard 8-decimal notations for fee rate
_Actual results_
Scientific notations for small fee rates.
_Cause_
The fee rates not being rounded up to 8-decimal notations
_Solution_
Rounded the fee rates to 8-decimal notations
=> 8-decimals notation on fee rate in mempool tickets and transactions

db/dcrpg/internal/blockstmts.go, db/dcrpg/queries.go, sample-dcrdata.conf, views/windows.tmpl
A ticket window ends when `(height + 1) % window_size == 0`;
Orphaned blocks should be excluded from ticket window block count in `/ticketpricewindows`.
=> Fix ticket window end block and block count.

public/js/controllers/charts_controller.js, views/charts.tmpl, webpack.common.js
Also work around bug in npm watch script.
=> charts: add raw data URL to charts page

db/dcrpg/internal/blockstmts.go, explorer/templates.go, views/timelisting.tmpl
Group blocks by UTC datetime regardless of server timezone;
Link day rows to the last block of each day instead of the tip.
=> Force UTC timezone and fix day links in time-based block list.

db/cache/charts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, public/js/controllers/charts_controller.js
Fix #1689 
This PR adds a height constraint to the query that fetches vouts for computing anonymity set.
=> Mixed chart query optimisation

api/apirouter.go, api/apiroutes.go, api/insight/apirouter.go, api/insight/apiroutes.go, main.go, middleware/apimiddleware.go, middleware/apimiddleware_test.go
Provides access to the `existsaddresses` RPC call and parses the result to a `[]bool`. Allows multiple comma-separated addresses to be specified in the same way as the `addrs` insight endpoints. Limited to 64 addresses, mostly because it simplifies parsing and use of the RPC result.
The dcrd address existence index is enabled by default and seems to be quite fast. I did a little DB testing with the query
```
SELECT exists(select 1 from addresses where address = a) FROM unnest(ARRAY[...]) AS a;
```
and it seems to be roughly the same speed on my system and network.
=> api: add address/{address}/exists endpoint

explorer/explorerroutes.go, public/js/controllers/address_controller.js, views/address.tmpl
Pagination selector on address page was not changing the number of rows displayed. The param being passed in was not properly being used. The function was hard coded to 20 rows. This has been resolved.
Additionally, changing the transaction type selector caused the total transaction count to lose comma formatting. This has also been fixed.
Also added pagination page number links.
Resolves https://github.com/decred/dcrdata/pull/1719
=> Address page pagination rows fix and comma formatting

README.md, api/apirouter.go, api/apiroutes.go
This adds the `/api/supply/circulating` endpoint with the optional `dcr=[true|false]` URL query (default is false, meaning atoms).
Because CMC needs a number not some silly JSON thign.
```
$  curl http://127.0.0.1:7777/api/supply/circulating
1134639036687827
$  curl http://127.0.0.1:7777/api/supply/circulating?dcr=false
1134639036687827
$  curl http://127.0.0.1:7777/api/supply/circulating?dcr=true
11346390.36687827
```
=> supply only

db/dcrpg/indexing.go
The 1.8.0 DB schema upgrade made these indexes, but they would be missing after a fresh sync.
=> dcrpg: include index of txns on height in (De)IndexAll

api/insight/apimiddleware.go, middleware/apimiddleware.go
A few middlewares (insight.PostAddrsUtxoCtx, insight.PostAddrsTxsCtx,
and middleware.TransactionsCtx) were still storing a string in
middleware.CtxAddress instead of a []string.
PostAddrsUtxoCtx and PostAddrsTxsCtx now Split the string from the
part of the request body holding the address list.
TransactionsCtx now just wraps the address string from the "?address="
url query, i.e. []string{address}.  And handler using this middleware is
responsible for validating the address in the slice.
fixes:
- GET /insight/api/txs?address={address} via middleware.TransactionsCtx
- POST /insight/api/addrs/utxo via insight.PostAddrsUtxoCtx
- POST /insight/api/addrs/txs via insight.PostAddrsTxsCtx
=> middleware,api/insight: fix setting middleware.CtxAddress

api/apirouter.go, api/insight/apirouter.go, go.mod, go.sum, middleware/go.mod, middleware/go.sum
chi 4.0.3-pre to 4.1.0 release has a number of fixes and improvements to
the Compress, Recover, and Throttle middlewares.
middleware too
=> update chi to 4.1.0

explorer/explorerroutes.go
Closes #1672
This pull request enables searching for a transaction outpoint formatted as `txid:out` where `txid` is a transaction hash and `out` is a transaction output index. Function `Search` redirects to path `/tx/{txid}/out/{out}` after seeing such search pattern. The transaction page then highlights the corresponding output.
=> Allow searching for a transaction outpoint

views/proposals.tmpl
Fixes [#1583](https://github.com/decred/dcrdata/issues/1583)
Added a fix for proposals showing `In discussion` instead of `Abandoned`.
=> Fixed vote status for proposals showing in discussion instead of abandoned

views/block.tmpl
This puts spaces that were incorrectly being eaten by the template generator on the block page:
Before:
After:
=> views: restore missing spaces on ticket/vote/rev counts

explorer/explorerroutes.go, public/js/controllers/attackcost_controller.js, views/attackcost.tmpl
This PR checks the total amount of DCR needed for the calculated PoS attack and displays a warning indicator when the amount of DCR needed for the attack is greater than the total amount of DCR in circulation.
=>  Attack Calc - Display warning about max possible DCR

api/insight/apiroutes.go, config.go, db/cache/addresscache.go, explorer/explorerroutes.go
Multiple config tweaks and clean-up:
* remove deprecated --pg option
Full mode is the only option, and --pg was deprecated in a previous
release, so remove it now.  Also clean up config options.
* change default disabled exchanges
- huobi is now enabled by default
- polo disabled by default
* <s>change link urls to decred.org tlds (e.g. https://explorer.dcrdata.org/ => https://mainnet.decred.org)</s> The {mainnet,testnet}.decred.org domains are still special cases that rewrite /api => /insight/api for compatibility with older insight consumers that used these domains when they were actually running Insight.
* increase default address cache sizes
=> config: remove pg option and other tweaks

db/dcrpg/internal/blockstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/explorer.go, explorer/explorerroutes.go, views/block.tmpl
Display (link to) other block hashes if two or more blocks are found for a given height. Helps to provide visual feedback when there are multiple blocks for a given height.
=> explorer: display alt. block hashes on /block page

explorer/explorerroutes.go, main.go, views/extras.tmpl, views/home.tmpl
Close #1742 
This PR adds a /treasury path that shows the Decred Treasury address page.
=> Short URL for the treasury page

public/js/controllers/market_controller.js, views/extras.tmpl
This PR removes the dark line of the spikes seen on the aggregated depth chart. Have not yet figured out how to remove the colored part, but that is much more subtle. 
It should be noted that the Dygraphs issue also has the consequence that the sell value at duplicated price points in the overlapping region are not accumulated correctly, so there is still a display bug. At this point, I don't plan to try to work around Dygraphs anymore. I'll spin up the chart on my own if we really want these kinks worked out.
=> markets: partially resolve Dygraphs spikes issue on agg depth chart

api/apirouter.go, api/apiroutes.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, sample-nginx.conf, views/address.tmpl
The encoding of CSV should not have been entirely in memory, instead
encoding to the http.ResponseWriter one line at a time.
Previously this had a very specific requirement from a public facing
reverse proxy to avoid multiple simultaneous requests to the same
address but it was easy to mess up, so this is the best fix.
For the csv download path, eliminate the cr query and add an optional
"/win" suffix instead to use carriage returns at the end of each line.
This change also reduces the likelihood of server misconfiguration
causing a cache miss. And this change makes implementing said
server configuration all the simpler.
Thank you to the reporter of this issue, but note that the proxy config
required for safe deployment without this code change is both subtle
and error prone in practice. …
=> [5.3] api: streaming CSV encodes

api/apirouter.go, api/apiroutes.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, sample-nginx.conf, views/address.tmpl
The encoding of CSV should not have been entirely in memory, instead
encoding to the http.ResponseWriter one line at a time.
Previously this had a very specific requirement from a public facing
reverse proxy to avoid multiple simultaneous requests to the same
address but it was easy to mess up, so this is the best fix.
For the csv download path, eliminate the cr query and add an optional
"/win" suffix instead to use carriage returns at the end of each line.
This change also reduces the likelihood of server misconfiguration
causing a cache miss.
=> api: streaming CSV encodes

cmd/dcrdata/public/js/controllers/attackcost_controller.js, cmd/dcrdata/public/scss/attackcost.scss, cmd/dcrdata/public/scss/charts.scss, cmd/dcrdata/views/attackcost.tmpl
Images:
- [Before, Mobile](https://user-images.githubusercontent.com/11244180/89160555-d8afb200-d5a3-11ea-8b05-89ea0f637a3a.png)
- [After, Mobile](https://user-images.githubusercontent.com/11244180/89160563-da797580-d5a3-11ea-8cfa-85bf237cc6b7.png)
- [Before, Firefox](https://user-images.githubusercontent.com/11244180/89160543-d3eafe00-d5a3-11ea-93d6-a646ad3ad6ab.png)
- [After, Firefox](https://user-images.githubusercontent.com/11244180/89160550-d64d5800-d5a3-11ea-80b2-ef63dae2e3c1.png)
Notable Changes:
- Correctly display current network name
- Load additional costs from query string
- Fixed step value of exchange rate input
- Fixed input and select widths on firefox
- Improved layout of parameter sections
- Fixed margin and removed z-index of legend
- Format units consistently in the …
=> Attack cost calculator layout changes and bug fixes

cmd/dcrdata/config.go
I'm seeing an issue on Windows with the **github.com/caarlos0/env** package seemingly related to [this closed issue](https://github.com/caarlos0/env/issues/151), but with no such solution available.
I can dig deeper, but this gets me up and running on Windows.
---
The initial error manifested as this message, for any field that didn't have an env tag.
```
Failed to load dcrdata config: env: parse error on field "MaxCSVAddrs" of type "int": strconv.ParseInt: parsing "ExitCode=00000000": invalid syntax
```
And even after applying this fix, I still had an issue with `env.Parse` overwriting the value of my `IndentJSON` with some nonsense. Here's what the beginning of an indented verbose tx looks like.
```
{
ExitCode=00000000"txid": "9052b50634c08c850282b7b38fb5db460a826eafcea66ea99f687899343a5 …
```
=> cmd/dcrdata: env tag all the things

cmd/dcrdata/api/apirouter.go, cmd/dcrdata/api/apiroutes.go, cmd/dcrdata/api/insight/apirouter.go, exchanges/bot.go, exchanges/exchanges.go, exchanges/exchanges_test.go
`api/exchanges` is a lot of data. `api/exchangereate` is the same thing without the huge binned order data sets.
=> api: add a simpler exchange rate API endpoint

exchanges/exchanges.go, exchanges/exchanges_live_test.go, exchanges/exchanges_test.go
Also some basic Refresh tests, but they didn't catch the bug.
=> prevent double Close'ing of the signalr and websocket connections

cmd/dcrdata/api/apiroutes.go, cmd/dcrdata/api/insight/apimiddleware.go, cmd/dcrdata/api/insight/apiroutes.go, cmd/dcrdata/middleware/apimiddleware.go, cmd/dcrdata/middleware/apimiddleware_test.go, cmd/dcrdata/sample-nginx.conf, exchanges/exchanges_test.go
Both the insight and dcrdata http APIs need to be more cautious with their responses that might include html.
For the most part this involves using `html.EscapeString` with any string that might contain user input, such as an error message.
=> rigorous html escaping

cmd/dcrdata/package-lock.json, cmd/dcrdata/package.json, cmd/dcrdata/public/js/controllers/address_controller.js, cmd/dcrdata/public/js/controllers/agenda_controller.js, cmd/dcrdata/public/js/controllers/charts_controller.js, cmd/dcrdata/public/js/controllers/market_controller.js, cmd/dcrdata/public/js/controllers/proposal_controller.js, cmd/dcrdata/public/js/controllers/ticketpool_controller.js, cmd/dcrdata/public/js/helpers/http.js, cmd/dcrdata/views/extras.tmpl
This drops the axios dependency, using `fetch` instead.
This reduces the size of the vendors bundle (4.bundle.js) from 104 KiB to 90.3 KiB, and grows app.bundle.j by 1 KiB.
=> replace axios with fetch

cmd/dcrdata/explorer/explorerroutes.go, cmd/dcrdata/views/proposals.tmpl, cmd/dcrdata/views/timelisting.tmpl
Replacing https://github.com/decred/dcrdata/pull/1780, which needs conflict resolution, and I'm not allowed to push on the OP's branch.
Fixes the Bad request error that occur on the /proposals page when one changes the vote status on the drop down from All to any other option, then back to All.
=> fix bad byvotestatus type, and offset computation

cmd/dcrdata/explorer/templates.go, cmd/dcrdata/explorer/templates_test.go, cmd/dcrdata/views/block.tmpl
This changes the wording around stakeholder (dis)approval to what it really means.
Saying (in)valid is misleading as the blocks are still valid, just that the stakeholders
have disapproved the regular tree transactions.
This change is visible on the /block page in two places:
Instead of just the integer vote bits above, it shows "approve" or "disapprove".
And in the votes table:
=> blocks page: (dis)approved vs. (in)valid wording

README.md, cmd/dcrdata/explorer/explorer.go, cmd/dcrdata/explorer/explorerroutes.go, cmd/dcrdata/main.go, cmd/dcrdata/sample-dcrdata.conf, db/cache/addresscache.go, db/dbtypes/types.go, db/dcrpg/chainmonitor.go, db/dcrpg/indexing.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/sync.go, gov/politeia/proposals.go, txhelpers/txhelpers.go
This PR has been running on tip.dcrdata.org, the hidden service, testnet, and one mainnet backend.
This contains a few distinct improvements, all related to DB or sync and are thus stacked commits:
- Each step of the startup sync is described in terms of **stages**.  e.g. `Beginning SYNC STAGE 1 of 6 (block data import)...`
- The **batch update of `the vouts.spend_tx_row_id` column is eliminated** and is done on-the-fly always, just like normal during operation.  The mega query that did this update (see `updateSpendTxInfoInAllVouts`) during the initial sync step previously was surprisingly costly on slower drives.  On an SSD, it would be less than 30 minutes, but on a HDD it ran for 12+ hours (not acceptable).  Doing the update on the fly even for the initial block data import is …
=> sync clarity and eliminate batch vouts.spend_tx_row_id update

cmd/dcrdata/main.go, db/dbtypes/types.go, db/dcrpg/internal/rewind.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/rewind.go
When using `--purge-n-blocks`, there was a bug that prevented the `vouts.spend_tx_row_id` column from being reset to `NULL` for purged transactions.  This fixes the buggy query (`ResetVoutSpendTxRowIDs`), adds purge timing to the `DeletionSummary` and it's `String` method, and cleans up some of the purge logic in `main` from when sqlite was removed.
```
2021-07-20 15:11:21.635 [INF] DATD: Purging PostgreSQL data for the 200 best blocks back to 573320...
2021-07-20 15:12:02.936 [INF] DATD: Successfully purged data for 200 blocks from PostgreSQL (new height = 573320):
200 Blocks purged in 6.524621816s
22774 Vins purged in 433.885111ms
25705 Vouts purged in 387.882755ms
42265 Addresses purged in 903.273033ms
3899 Transactions purged in 97.149828ms
21316 Vout spending tx row ids reset in …
```
=> fix purge not resetting vouts.spend_tx_row_ids

cmd/dcrdata/public/js/controllers/proposal_controller.js
This resolves the JS error described in https://github.com/decred/dcrdata/pull/1829#issuecomment-893836773
The above happens when a proposal has no votes yet and thus cannot have charts or a progress meter.
=> js: fix proposal contoller for props with no progress or votes

.github/workflows/build.yml, README.md, cmd/dcrdata/explorer/reloadsig.go, cmd/dcrdata/explorer/reloadsig_windows.go, cmd/dcrdata/go.mod, cmd/dcrdata/signal_unix.go, cmd/swapscan-btc/go.mod, db/dcrpg/go.mod, db/dcrpg/pgblockchain_charts_test.go, db/dcrpg/pgblockchain_common_test.go, db/dcrpg/pgblockchain_fullpgdb_test.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/system_online_test.go, db/dcrpg/types_online_test.go, exchanges/exchanges_live_test.go, exchanges/go.mod, go.mod, gov/go.mod, rpcutils/rpcclient_online_test.go, testutil/dbconfig/config_fullpgdb.go, testutil/dbconfig/config_testdb.go
Update for Go [1.16, 1.17] req. Update max node to 16.x from 15.x.
Re-run `go fmt` on everything with the go 1.17 version that adds the go:build comments.
=> update min tool versions: go 1.16

blockdata/blockdata.go, cmd/dcrdata/api/apiroutes.go, cmd/dcrdata/api/insight/apiroutes.go, cmd/dcrdata/main.go, db/dcrpg/insightapi.go, db/dcrpg/pgblockchain.go, mempool/collector.go, mempool/monitor.go, pubsub/pubsubhub.go, rpcutils/rpcclient.go, stakedb/stakedb.go, txhelpers/staketree.go, txhelpers/txhelpers.go, txhelpers/txhelpers_test.go
This reduced a lot of reliance on the rpcutils and rpcclient packages.
In a future version we might make rpcutils it's own module again since I'd like the main module not to require either github.com/decred/dcrd/rpcclient or rpcutils.
=> interfacing and less rpcutils and rpcclient reliance

cmd/dcrdata/views/tx.tmpl, db/dcrpg/pgblockchain.go, explorer/types/explorertypes.go
This diff adds the tx and script versions to the tx details areabox.
Edit:
Before:
After: 
Let me know if any UI changes are needed for a better UX 👍 
closes #1851
=> ui: show tx & script version on tx details

cmd/dcrdata/public/js/controllers/homepage_controller.js, cmd/dcrdata/views/extras.tmpl
The following line in homepage_controller.js would error when a new block arrived:
```js
this.mixedPctTarget.innerHTML = ex.mixed_percent.toFixed(0)
```
`this.mixedPctTarget` was undefined because the `'this.mixedPct'` target was not listed in output of the homepage controller's `targets` method.
=> fix missing mixedPctTarget breaking home page updates

cmd/dcrdata/explorer/explorerroutes.go, cmd/dcrdata/views/tx.tmpl, db/dbtypes/types.go, db/dcrpg/pgblockchain.go, explorer/types/explorertypes.go, explorer/types/explorertypes_test.go, mempool/collector.go, mempool/monitor.go, pubsub/pubsubhub.go
This updates the `explorer/types.MempoolTx` type with a `Version` field (transaction version).
It also moves the script version from `explorer/types.TxInfo` to `explorer/types.TxBasic`, which is embedded by other types including `TxInfo` and `TrimmedTxInfo`.
The first commit changes the "Version" column of the Transaction Outputs table on the /tx page to change between "Version" and "Ver" at the `sm` responsive break point.
=> script Version for MempoolTx

mempool/mempoolcache.go
This resolves an issue with the /ticketpool page not loading when there are no tickets in mempool, which caused a NaN value for ticket price to break JSON parsing in the browser.
=> mempool: fix NaN in json without tickets in mempool

cmd/dcrdata/views/ticketpool.tmpl
The /ticketpool page's handler is unique in that it does not embed
`CommonPageData` in a parent struct, instead passing it directly as the
only page data.  This broke the execution of `"html-head"` from that
page since it tried to use `.CommonPageData`.
This changes it to use just `.` so the template execution succeeds.
=> views: fix ticketpool's arg to html-head template

db/dcrpg/indexing.go, db/dcrpg/internal/indexes.go, db/dcrpg/internal/stats.go, db/dcrpg/rewind.go, db/dcrpg/upgrades.go
CAREFUL: This will upgrade your DB schema version.
This removes a redundant index on `stats.height`.
`\d stats` was showing this:
```
Table "public.stats"
Column   |  Type   | Collation | Nullable | Default 
-----------+---------+-----------+----------+---------
blocks_id | integer |           |          | 
height    | integer |           |          | 
pool_size | bigint  |           |          | 
pool_val  | bigint  |           |          | 
Indexes:
"stats_height_key" UNIQUE CONSTRAINT, btree (height)
"uix_stats_height" UNIQUE, btree (height)
Foreign-key constraints:
"stats_blocks_id_fkey" FOREIGN KEY (blocks_id) REFERENCES blocks(id) ON DELETE CASCADE
```
The `"stats_height_key" UNIQUE CONSTRAINT, btree (height)` index is created automatically because of the table definition: …
=> dcrpg: remove redundant stats(height) index

db/dcrpg/internal/system.go, db/dcrpg/pgblockchain.go, db/dcrpg/system.go, db/dcrpg/system_online_test.go
This adds a PostgreSQL version check to `NewChainDB`, which will return an error if the postgres service in use indicates a version less than the required minimum version defined by the new `pgVerNumMin` `const`.
This enforces the requirement already documented in README.md.
=> db/dcrpg: enforce a min required postgres version

cmd/dcrdata/views/proposals.tmpl
[Politeia ](https://proposals.decred.org/) use terms `Approved `and `Rejected `for proposal vote outcomes. This diff changed terms [dcrdata ](https://dcrdata.decred.org/proposals) use for proposal vote outcome(`Failed `and `Passed`) to what Politeia uses for consistency.
Closes #1848
=> Changed terms for proposal vote outcomes.

cmd/dcrdata/api/apirouter.go, cmd/dcrdata/api/apiroutes.go, cmd/dcrdata/explorer/explorer.go, cmd/dcrdata/explorer/explorerroutes.go, cmd/dcrdata/views/treasury.tmpl, db/dbtypes/types.go, db/dcrpg/pgblockchain.go
**db**: fix treasury spend tally amount
This fixes the treasury spend sum that uses a postgresql query.
This also renames the TGenCount and TGen fields of the
dbtypes.TreasuryBalance struct to TBaseCount and TBase.
The bins of the balance correspond to the treasury types: treasury
adds, spends, bases.  The "tgen" wording confuses this categorization
with output types, where TGEN is the opcode in the outputs of a
treasury spend, while the opcodes in the outputs of a both treasury add
and treasurybase txns are TADD.
Note that when rows are inserted into the treasury table, they are are
currently the change to the treasury and the txn type.
This adds Height and MaturityHeight to the TreasuryBalance struct.
**api:** add /api/treasury/balance
=> Treasury balance updates

cmd/dcrdata/public/js/controllers/agendas_controller.js, cmd/dcrdata/public/scss/table.scss, cmd/dcrdata/views/agendas.tmpl, cmd/dcrdata/views/extras.tmpl
Room for improvement but will at least show all the voting meters for multiple agendas at the same stake version.
Was showing like the following:
=> agendas page: show all agenda meters

cmd/dcrdata/public/scss/charts.scss, cmd/dcrdata/views/extras.tmpl
Bootstrap 5 updated the `row` class to apply a `width: 100%` to its childrens. Apparently this was done to prevent the columns from becoming too narrow when dealing with smaller grids. This made the custom input checks from the treasury page to be overflown from its parent div. Since we do want the columns to be narrow in this specific case,
this diff applies a `width: unset` to the column children's class `.customcheck`.
Before:
After:
=> ui: Fix customcheck width on treasury page

cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/webpack.common.js
This diff adds automatic cache bust by adding an inline webpack
plugin, which parses the bundles hashed filenames through the app
entrypoints and replaces them on the `extras.tmpl` template.
=> webpack: Add plugin to replace bundle hashes

cmd/dcrdata/views/address.tmpl, cmd/dcrdata/views/agendas.tmpl
Resolves a failure going between pages of the address table:
=> views: stimulus targets loose ends

cmd/dcrdata/internal/api/apirouter.go, cmd/dcrdata/internal/explorer/explorer.go, cmd/dcrdata/internal/explorer/explorermiddleware.go, cmd/dcrdata/internal/explorer/explorerroutes.go, cmd/dcrdata/internal/middleware/apimiddleware.go, cmd/dcrdata/main.go, cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/views/verify_message.tmpl
This adds the verify message feature to dcrdata:
- New endpoints `GET /verify-message` and `POST /verify-message`
- Endpoint handlers `VerifyMessagePage` and `VerifyMessageHandler` for `GET` and `POST` respectively.
- A responsive page for the verify message form.
Closes #1771
UI:
=> multi: add verify message feature

cmd/dcrdata/internal/explorer/explorer.go
minor inconvenience, but it was still the correct github repo, just a 404
=> explorer: update broken insight docs link

cmd/dcrdata/public/js/controllers/homepage_controller.js, cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/views/home.tmpl
After a new block was mined, only the dev fund amount was displayed on the home page and the decentralized treasury was not included.
Closes #1914
=> views: Incorrect treasury balance on home page

cmd/dcrdata/internal/explorer/explorerroutes.go, cmd/dcrdata/public/js/controllers/address_controller.js, cmd/dcrdata/views/address.tmpl, cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/views/treasury.tmpl
The treasury page was returning all of the transactions for the tx count regardless of the selected tx type. Also, the pagination section is now hidden if there are no transactions returned.
Closes #1925
=> views,explorer: Fix treasury pagination

cmd/dcrdata/views/charts.tmpl
=> ui: add margin between last element display and footer on `/charts` page

db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go
Duplicate deletion queries were keeping the vouts/vins that were from the stake-invalided transactions instead of the newer/replaced ones.
Before
After (the "unspent" is now a link)
@dajohi 
Requires full resync/ibd to resolve
=> db/dcrpg: deleted oldest dups, not newest

cmd/dcrdata/views/blocks.tmpl, cmd/dcrdata/views/timelisting.tmpl, cmd/dcrdata/views/windows.tmpl
This diff adds a message to a hand full of unused info icons. Closes #1939
=> UI: add message to unused info icons

README.md, api/types/apitypes.go, cmd/dcrdata/internal/api/apiroutes.go, cmd/dcrdata/internal/middleware/apimiddleware.go, db/dbtypes/extraction.go, db/dbtypes/types.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_fullpgdb_test.go, dev/dcrdata-harness.tmux, rpcutils/rpcclient.go
Requires https://github.com/decred/dcrdata/pull/1922.  This PR starts with the `use db instead of searchrawtransactions` commit.
dcrd's `addrindex` is no longer required.  Previously it wasn't even really strictly necessary except for a single http endpoint and unused functions; sync always worked without it.
There are breaking changes as a type has change, but this is in dcrdata/v7 only, which is not yet tagged.
db/dcrpg:
Rewrite `GetAddressTransactionsRawWithSkip` to use the pg db instead of the `searchrawtransactions` RPC.
Remove `InsightSearchRPCAddressTransactions`, which was unused.
api/types:
Stop using `chainjson.VinPrevOut`.
Add `VinShort` type that is similar to `chainjson.Vin`, although lacking `Sequence` and `ScriptSig`, and the `Coinbase`, `StakeBase`, etc. fields are just …
=> use db instead of searchrawtransactions

cmd/dcrdata/internal/explorer/templates.go, cmd/dcrdata/public/js/controllers/market_controller.js, cmd/dcrdata/public/js/helpers/humanize_helper.js, cmd/dcrdata/views/blocks.tmpl, cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/views/market.tmpl, cmd/dcrdata/views/proposals.tmpl, cmd/dcrdata/views/timelisting.tmpl, cmd/dcrdata/views/windows.tmpl
Before:
After:
Before:
After:
Before:
After:
Before:
After:
=> UI: fix dcrdata UI quirks

cmd/dcrdata/views/tx.tmpl
=> cmd/dcrdata/views: display treasury adds and treasury bases as not spendable

api/types/apitypes.go, db/dcrpg/pgblockchain.go
This returns a tx's `tree` as part of the  `apitypes.Tx` type which is used as the return value for the `api/tx/{txid}` endpoint. Closes #1797
=> dcrpg: add "tree" to apitypes.Tx type

cmd/dcrdata/config.go, cmd/dcrdata/internal/explorer/explorermiddleware.go, cmd/dcrdata/main.go, cmd/dcrdata/sample-dcrdata.conf, cmd/dcrdata/sample-nginx.conf, cmd/dcrdata/views/extras.tmpl
Since reverse proxy config is often not adequate or correct, this adds an allowed hosts middleware to dcrdata to ensure that any `Host` header value set in the request header is on a whitelist of hosts.
However, the reverse proxy should be configured with:
- a `default_server` black hole or redirect-only `server`, as a catch-all, preventing one of the other `server`s from becoming the default
- all other `server`s should specify `server_name` values including fqns, IPs, and `""` for when the `Host` header is not set.  These configuration changes prevent invalid or unexpected `Host` values.
However, to use without the above settings (or no reverse proxy at all), this change adds the `AllowedHosts` middleware, which ensures the `http.Request.Host` matches one of a number of hosts specified …
=> cmd/dcrdata: allowed hosts

cmd/dcrdata/sample-dcrdata.conf, db/dcrpg/internal/addrstmts.go
Resolves https://github.com/decred/dcrdata/issues/1961
```
$  curl -ks http://127.0.0.1:7777/api/address/DshMNsvETDWpVoCe1re9NTAChiJagzsFV7J/amountflow/day | jq '.net | add'
-3.637978807091713e-12
$  curl -ks http://127.0.0.1:7777/api/address/DshMNsvETDWpVoCe1re9NTAChiJagzsFV7J/amountflow/day | jq '.received | add'
950200.8645353797
```
jq is doing lossy floating point addition there and I didn't feel like multiplying by 1e8 and rounding before adding.
=> dcrpg: query for only valid mainchain data in address chart queries

cmd/dcrdata/views/block.tmpl, db/dcrpg/pgblockchain.go, explorer/types/explorertypes.go
=> multi: Show PowHash on blocks view page for DCP0011

cmd/dcrdata/go.mod, cmd/dcrdata/go.sum, db/dcrpg/go.mod, db/dcrpg/go.sum, db/dcrpg/pgblockchain.go, go.mod, go.sum, gov/go.mod, gov/go.sum, pubsub/democlient/go.mod, pubsub/democlient/go.sum
This modifies the recently-added logic to include the proof of work hash in the explorer block info to make use of the new PoWHash field of the verbose block output when available.
=> dcrpg: use PoW hash from block result when avail

docs/CONTRIBUTING.md
I was reading `contributing.md`, and I noticed there was a link to coffee. I clicked it and was immediately warned by Google that it was dangerous due to some security breach and phishing attacks. I didn't investigate much further, but I figured I should remove the link.
While there, I just did a quick update to the suggested Go line. Figured 1.8.3 was a bit old.
=> docs: Removed an old sketchy URL that appeared to be pwnd

README.md
The treasury info endpoint was not added to the README when it was added to the API (#1894). Including it now so it becomes Google-able and CTRL+F-able.
=> docs: Add /treasury/balance endpoint to README.md

cmd/dcrdata/public/js/controllers/homepage_controller.js, cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/views/home.tmpl
This is a quick fix for displaying the difficulty on the homepage. I just changed it to show the raw value instead of being divided by 1e6 and showing a "Mil" value.
I thought about trying to do something complicated and make a scaling value that switched formats if it became longer than 1e6, but I don't think it's worth the time investment it would take me.
=> views/home: Use ThreeSigFigs to display difficulty on homepage

run_tests.sh
`./run_tests.sh` fails on my Mac. 
Error message: `./run_tests.sh: line 16: conditional binary operator expected.` 
```
% bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
Copyright (C) 2007 Free Software Foundation, Inc.
```
This PR uses a stable conditional expression `-n` to test for bash script argument in `./run_tests.sh`.
=> Use `-n` to test for bash script argument

cmd/dcrdata/views/block.tmpl
Closes #1745
Issue: Visit the https://dcrdata.decred.org/side and click on any block, then click on the `api` link on the displayed block view. It'll display data for the mainchain block.
=> {cmd/dcrdata/views}: Fix orphan block `api` link on the block view

exchanges/exchanges.go
Closes https://github.com/decred/dcrdata/issues/2005
=> dcrdata/exchanges: use `EndRate` from dcrdex `EpochReportRoute` as dcr rate

cmd/dcrdata/internal/explorer/templates.go, cmd/dcrdata/views/extras.tmpl
This PR adds a `currentYear` template function to display the correct current year so we don't need to update this every year.
=> {cmd/dcrdata}: Use template func for footer year

cmd/dcrdata/internal/explorer/explorerroutes.go, cmd/dcrdata/views/treasury.tmpl
This PR fixes a 4-year-long TODO to list unconfirmed tspends and tadds(rare) on the `/treasury` page.
=> fix: add unconfirmed tspend and tadds on `/treasury` page
