decred/dcrdata

.gitignore, cmd/scanblocks/README.md, cmd/scanblocks/jsonarray2csv.sh, cmd/scanblocks/scanblocks.go, txhelpers/staketree.go
This adds a README.md for scanblocks, along with a helper .sh script, and some related code cleanup.
=> scanblocks README.md

apimiddleware.go, apirouter.go, apiroutes.go, blockdata/blockdata.go, blockmemdb.go, cmd/rebuilddb/rebuilddb.go, config.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, dcrsqlite/sqlite.go, main.go, rpcutils/rpcclient.go, txhelpers/staketree.go
This addresses https://github.com/dcrdata/dcrdata/issues/8
Seems to be working.
=> extended stake info for sqlite and rebuilddb

README.md, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, main.go, mempool/mempool.go, mempool/mempoolcache.go
Addresses https://github.com/dcrdata/dcrdata/issues/28
=> Add time stamp to mempool data.

dcrsqlite/sync.go, main.go, mempool/mempool.go, mempool/mempoolcache.go, reloadsig.go, reloadsig_windows.go, views/root.tmpl, web.go
These commits add mempool to the HTML/web interface.
=> Webui update

.gitignore, version.go, web.go
Fixes https://github.com/dcrdata/dcrdata/issues/40
=> With < 20 tickets in mempool, report 0.01 as lowest mineable

blockdata/log.go, cmd/rebuilddb/rebuilddb.go, cmd/scanblocks/scanblocks.go, config.go, dcrsqlite/log.go, glide.lock, glide.yaml, log.go, main.go, mempool/log.go, rpcutils/log.go, stakedb/log.go, version.go
This also removes seelog, and updates several other dependencies.
=> Switch to new logger (btclog+jrick's logrotate)

apirouter.go, glide.lock, glide.yaml
I've started working on a separate front end and have enabled CORS so that it can make ajax requests. Saw an issue related to this https://github.com/dcrdata/dcrdata/issues/33
New to go so feedback welcome.
=> enable CORS for /api

sample-dcrdata.conf
Simply changed the default nodaemontls value
=> Fixed nodaemontls value

.gitignore, apimiddleware.go, blockdata/blockdata.go, main.go, public/js/messagesocket.js, version.go, views/root.tmpl, web.go, websocket.go
This adds websocket support to the web interface:
- /ws is the websocket path
- JS in the main page html automatically connects a websocket on this path, and updates a elements on the main page (height, hash, size, diff, sdiff) when a new block is connected.
- Added the new`WebsocketHub` to manage active connections
- `(*WebUI).WSBlockUpdater` is the new http.HandlerFunc for the `/ws` path.  It manages a single connection, from register, updates, and disconnect.
- A bunch more (will edit this PR description before merging)
=> WebSocket support

config.go
Analogous to dcrd PR https://github.com/decred/dcrd/pull/741/files
=> Use btclog for determining valid log levels

apimiddleware.go, apirouter.go, apiroutes.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go
This is another step toward addressing issue https://github.com/dcrdata/dcrdata/issues/61
The first step was PR https://github.com/dcrdata/dcrdata/pull/69 that added the ability to get transactions for a block (and lookup by block hash).
=> Transaction API Endpoint

apirouter.go, apiroutes.go, config.go
Tried to pass an anonymous struct to writejson but that didn't work so just wrote it directly
Issue #74
=> Added Transaction count for Block Transactions

blockdata/blockdata.go, blockdata/chainmonitor.go, cmd/scanblocks/scanblocks.go, dcrsqlite/sync.go, glide.lock, glide.yaml, rpcutils/rpcclient.go, stakedb/chainmonitor.go, stakedb/stakedb.go
After pulling this, you **MUST** `rm -r vendor` and `glide install` before building.
=> Update deps, deal with GetBlock() returning msgBlock now

apimiddleware.go, apirouter.go, apiroutes.go
`/api/block/range/{idx0}/{idx}/{step}`
`/api/block/range/{idx0}/{idx}/{step}/size`
=> Step param in block range requests

config.go, sample-dcrdata.conf
=> Change default APIListen to 127.0.0.1:7777

dcrsqlite/apisource.go, stakedb/stakedb.go
=> Do not continue startup if stake DB is already opened (unavailable)

apimiddleware.go, apirouter.go, apiroutes.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go
Adds the following endpoints:
Info
Endpoint
| --- | --- |
| Summary of past 10 transactions involving address| `/address/X` |
| Raw info of past 10 transactions |  `/address/X/raw` |
| Summary with N transactions |  `/address/X/count/N` |
| Raw info with N past transactions | `address/X/count/N/raw` |
=> Added Address endpoint

README.md, apimiddleware.go, apiroutes.go, blockdata/blockdata.go, blockmemdb.go, cmd/rebuilddb/log.go, cmd/scanblocks/log.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, dcrsqlite/sqlite.go, dcrsqlite/sync.go, err.go, mempool/mempool.go, mempool/mempoolcache.go, rpcutils/rpcclient.go, semver/semver.go, stakedb/stakedb.go, txhelpers/staketree.go, txhelpers/txhelpers_test.go, version.go, web.go, websocket.go
Updated README.md to include the current endpoints, bumped version in version.go and added comments to all exported types I could find from  `golint -min_confidence 0.9 $(glide nv)`
=> Updated README.md, version.go and added comments

apiroutes.go
=> Added hard limit of 2000 for address requests

public/css/main.css
addresses https://github.com/dcrdata/dcrdata/issues/109
=> fixed footer nav

views/extras.tmpl
Moving the cookie logic script to the top of the body should fix the temporary light theme flash
=> Fix light theme flash

views/extras.tmpl
=> autofocus search input

views/address.tmpl, views/root.tmpl, views/tx.tmpl, web.go
Removed extra B from some size values and humanized size value on root page
=> Humanize root blocks

blockdata/blockdata.go, dcrdataapi/apitypes.go, views/root.tmpl
=> Corrected block subsidy on home page

explorer.go
=> Sorting on the block page

views/tx.tmpl
=> Show N/A for unconfimed tx fees

explorer.go, views/address.tmpl, views/block.tmpl, views/tx.tmpl
Resolving issue #118.
I feel like some of the changes requested have already be done. Please explain in more detail if i overlooked anything. Thank you
=> template enhancement

dcrdataapi/apitypes.go, dcrsqlite/apisource.go, views/block.tmpl
resolves issue https://github.com/dcrdata/dcrdata/issues/204
=> block view: show vote version in table

public/css/main.css, views/address.tmpl, views/block.tmpl, views/explorer.tmpl, views/extras.tmpl, views/root.tmpl, views/tx.tmpl, web.go
This PR is a work in progress for https://github.com/dcrdata/dcrdata/issues/200.
I'll keep refining this, and also planning to rebase and work on top of https://github.com/dcrdata/dcrdata/pull/202 once that merges to master.
=> layout rework wip

Gopkg.lock, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, explorer/explorertypes.go, views/block.tmpl, views/tx.tmpl
The new `dcrjson.Vin` includes `Stakebase string` and `func IsStakeBase() bool`.  This PR updates dependencies to include the recent fixes to dcrd, and utilizes the new property and function.
The other deps are updated too.
=>  Use the new dcrjson.Vin with Stakebase

README.md
Addresses issue https://github.com/dcrdata/dcrdata/issues/215
=> Update README.md for dep

Gopkg.lock, Gopkg.toml, apiroutes.go, blockdata/blockdata.go, blockdata/chainmonitor.go, cmd/rebuilddb/config.go, cmd/rebuilddb/rebuilddb.go, cmd/scanblocks/scanblocks.go, config.go, dcrdataapi/apitypes.go, dcrsqlite/apisource.go, dcrsqlite/sync.go, explorer/explorertypes.go, log.go, main.go, mempool/mempool.go, ntfnchans.go, ntfnhandlers.go, rpcutils/rpcclient.go, stakedb/chainmonitor.go, stakedb/stakedb.go, txhelpers/staketree.go, txhelpers/txhelpers.go, txhelpers/txhelpers_test.go
dcrd now has rpcclient and dcrutil.
Update deps for decred repo reorganization.
=> Update deps for dcrd and base58.

blockdata/blockdata.go, dcrsqlite/sync.go, stakedb/stakedb.go, txhelpers/staketree.go, txhelpers/txhelpers.go, txhelpers/txhelpers_test.go
`FeeInfoBlock` and `FeeRateInfoBlock` are much faster now.  Hence sync is way faster now (40% or more).
Add TicketTxnsInBlock.
=> Remove lots of pointless RPC calls.

dcrsqlite/apisource.go, explorer/explorertypes.go, views/tx.tmpl
=> Added ticket maturity to tx page

dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorertypes.go, views/address.tmpl
=> Summary at the top of the address page

apimiddleware.go, apirouter.go, apiroutes.go, dcrsqlite/apisource.go
Add RPC calls to getvote info.
Add middleware to get latest vote version.
@karamble
=> Add /api/stake/vote/info?version=X route.

dcrdataapi/apitypes.go, dcrsqlite/apisource.go, dcrsqlite/sqlite.go, explorer/explorertypes.go, txhelpers/txhelpers.go
=> Correcting all the discovered misspelled words

views/block.tmpl
=> saying no tickets mined in this block when none is

cmd/rebuilddb2/config.go, cmd/rebuilddb2/rebuilddb2.go, db/dbtypes/types.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/sync.go, dcrdataapi/apicache.go, dcrdataapi/apitypes.go, txhelpers/staketree.go
This was OK until I introduced `RetrieveBestBlockHeight` in the constructor.
Plus lots of linting.
=> Fix NewChainDB with empty or non-existent tables

views/block.tmpl
Resolving the additions to issue #245
=> Case when no votes exist in block

main.go
The `heightDB, err := db.HeightDB()` line was added recently and it broke `--lite` mode.  Skip all the PostgreSQL stuff here to avoid panic in lite mode.
=> Fix nil pointer deref when using lite mode

views/block.tmpl
Resolving the first stage of issue #228
=> Adding the last block valid to the vote row

blockdata/blockdata.go, db/dcrpg/pgblockchain.go, db/dcrsqlite/apisource.go, web.go
To address issue https://github.com/dcrdata/dcrdata/issues/283
=> change date format to yyyy-mm-dd

views/tx.tmpl
For discussion on @McEdward's branch
=> Linking corresponding vote/ticket for a ticket/vote

explorer/explorer.go, explorer/explorerroutes.go, main.go, public/css/main.css, version.go, views/address.tmpl, views/block.tmpl, views/error.tmpl, views/explorer.tmpl, views/extras.tmpl, views/home.tmpl, views/rawtx.tmpl, views/tx.tmpl
Built with setting `main.CommitHash`:
Built without setting `main.CommitHash` (default):
=> Put version in footer, rearrange items, format.

explorer/explorerroutes.go, explorer/websockethandlers.go, main.go, views/extras.tmpl
This should solve most of #261 (just not the update search with websocket part).
=> Changed search to use the url

db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/address.tmpl
For #255, Still working on how to implement websocket to update when/if a transaction comes in for that address.
=> Searching for an address with no tx/websocket implementation on address page

views/block.tmpl
Addresses issue https://github.com/dcrdata/dcrdata/issues/316
=> fix version in block page footer

views/address.tmpl
=> Remove qr functionality from conditional block

db/dcrpg/pgblockchain.go, explorer/explorer.go, explorer/explorertypes.go, mempool/mempool.go, views/extras.tmpl, views/home.tmpl
Added the following stats to the front page:
- Ticket Rate of Interest
- Ticket Pool Size
- Ticket Pool Value
- Block Reward Adjustment progress
- Dev Fund balance (In full functionality mode)
=> Added Extra info to front page

version.go
feature set is significantly over 1.2
- front page extra info
- full ticket pool endpont
- http profiling
- other minor fixes
=> bump to 1.3

README.md, sample-dcrdata.conf
addresses issue https://github.com/dcrdata/dcrdata/issues/333
=> Update README.md and sample-dcrdata.conf

explorer/explorerroutes.go, explorer/explorertypes.go, views/block.tmpl
=> showing msg for when there are no transactions available on the block page

db/dcrsqlite/apisource.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/address.tmpl
This should fix the new issues with #255
=> fixing the search for addresses with no transactions

explorer/explorer.go
Getting the dev fund balance can take up to 15 seconds, which is not acceptable if this must be done before when storing a block.  The balance is only used on the explorer pages, so this can be fired off in a goroutine, and explorerUI.Store can continue
=> Defer query for dev fund balance when storing a new block.

config.go, main.go, sample-dcrdata.conf
=> making lite mode the default mode in the cfg

.travis.yml
(delayed until gimme adds 1.10)
=> travis: test with go 1.10.x, drop 1.8.x

db/dcrsqlite/apisource.go
=> Show block reward transaction as its own type "Coinbase"

db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, explorer/mempool.go, explorer/websocket.go, explorer/websockethandlers.go, main.go, mempool/mempool.go, ntfnchans.go, ntfnhandlers.go, txhelpers/txhelpers.go, views/block.tmpl, views/extras.tmpl, views/home.tmpl, views/mempool.tmpl
For issues #230 and #129 
Todo:
- ~~Extra mempool page for votes and revocations~~
Mempool page is now similar to block page
=> Live Mempool Page

Gopkg.lock, db/dbtypes/types.go, db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/tx.tmpl
=> ticket page: luck and additional data

db/dcrsqlite/apisource.go
This is a temporary band-aid for this issue: https://github.com/decred/dcrdata/issues/393
=> do not request previous vout extra data when just counting transactions

main.go
Due to a failure to update the `fetchToHeight` variable after dcrdata's table reindexing, sync would hang the first time run.  This is corrected.
=> main: prevent hang after reindex

explorer/explorer.go, explorer/explorermiddleware.go, explorer/explorerroutes.go, explorer/templates.go
Simple refactoring to make it easier to add templates since the current system is more complicated that it should be.
=> explorer: refactor the explorer templates so they are easier to manage

api/apiroutes.go, api/insight/apimiddleware.go, api/insight/apirouter.go, api/insight/apiroutes.go, db/dcrpg/insightapi.go, middleware/apimiddleware.go
This includes the `rawblock` Insight API endpoint, and a bunch of clean up.
=> insight: rawblock endpoint

views/tx.tmpl
=> pool status bug fix

views/address.tmpl
=> Page size selector feature

public/css/main.css, views/address.tmpl, views/explorer.tmpl, views/extras.tmpl, views/tx.tmpl
This is an initial pass to align current theme closer to the new design being worked on.
https://projects.invisionapp.com/share/K6GFONQ5AU7
Changes include table styling, background and text colors, and top nav search styling
(winging the dark theme here, I'm sure DZ will come up w/ something nicer!)
borderless search input
=> update colors, table styles and header/footer in move towards new design

README.md
=> Hint for the index settings of dcrd.conf to work with dcrdata

db/dcrsqlite/apisource.go, explorer/mempool.go
this would cause an invalid slice index panic when there was just one txn
@RogueElement was there are reason you were doing that `len-1`?
=> fix prepend to LatestTransactions

explorer/websocket.go
The channel send on `sendBufferChan` (after `addTxToBuffer`) was sending back to the event loop.  It had a buffer of length 1, so deadlock was not hard.
No longer send to the event loop from the event loop.  Schedule the send by firing off a goroutine.
=> prevent deadlock in websocket event loop

public/css/main.css
=> darken progress bar background for dark theme

public/css/main.css, views/extras.tmpl
This addresses menu toggle alignment raised in https://github.com/decred/dcrdata/issues/423 and refines styling to match the design spec.
=> refine hamburger menu style & animation

explorer/explorer.go, explorer/explorerroutes.go, views/address.tmpl, views/block.tmpl, views/error.tmpl, views/explorer.tmpl, views/extras.tmpl, views/home.tmpl, views/mempool.tmpl, views/parameters.tmpl, views/rawtx.tmpl, views/tx.tmpl
Fixes issues #475  and #474 
✅ added Title that currently says Chain State to say MainNet Chain State
✅ added menu switch between testnet and mainnet
✅ reordered menu items
=> Show net on home page and Reorder menu items

Gopkg.lock, Gopkg.toml, api/insight/log.go, api/log.go, blockdata/log.go, cmd/rebuilddb/rebuilddb.go, cmd/rebuilddb2/rebuilddb2.go, cmd/scanblocks/scanblocks.go, config.go, db/dcrpg/log.go, db/dcrsqlite/log.go, db/dcrsqlite/sqlite.go, explorer/log.go, log.go, mempool/log.go, middleware/log.go, notification/log.go, rpcutils/log.go, stakedb/log.go
- remove `btcsuite/btclog`
- `btcsuite/websocket` removed by `dep`
- import `decred/slog`
- replace all `btclog.` occurrences with `slog.`
=> replace loggers: /btcsuite/btclog >>> decred/slog

Gopkg.lock, db/dcrpg/pgblockchain.go
Addressing issue https://github.com/decred/dcrdata/issues/504
=> dcrpg: prevent stacking multiple calls to updateDevFund

views/extras.tmpl
Resolving https://github.com/decred/dcrdata/issues/488
=> html: update header descriptions

.gitignore, db/dcrsqlite/.gitignore, db/dcrsqlite/dcrsqlite_test.go, db/dcrsqlite/sqlite.go, stakedb/stakedb.go, testutil/tempfiles.go
Adds test to reproduce https://github.com/decred/dcrdata/issues/515
=> dcrsqlite: create DB-file parent directory when necessary

stakedb/ticketpool.go
Fix bug in `LoadAllPoolDiffs` where multiple diff sets for the same height
were loaded due to badger storing multiple value versions.
=> stakedb: fix loading bug in ticket pool db

views/block.tmpl
Hide 'No missed votes in this block'
This resolves issue #472
=> views: hide missed table when empty

explorer/explorer.go
=> explorer: do not fetch charts data in lite mode

db/dcrsqlite/dcrsqlite_test.go, db/dcrsqlite/missingparentfolder_test.go, db/dcrsqlite/sqlite.go, testutil/print.go, testutil/tempfiles.go, testutil/testutil.go
This is tier 1 of the #514 
- refactors the test setup
- also includes minor refactoring of the `dcrsqlite/sqlite.go`
=>  testutil: refactor test setup

.gitignore, testutil/testutil.go
=> testutil: fix error message formatting

db/dcrpg/pgblockchain.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/address.tmpl
=> Fix bugs in addresses page view

db/dcrpg/upgrades.go
When handleBlocksTableMainchainUpgrade has an error, it now names the block hash that caused it.
=> dcrpg: provide error context in handleBlocksTableMainchainUpgrade

views/extras.tmpl
changed https://mainnet.decred.org to https://explorer.dcrdata.org in main menu
=> changed https://mainnet.decred.org to https://explorer.dcrdata.org in main menu

views/parameters.tmpl
=> added TargetTimePerBlock in views/parameters.tmpl

api/apiroutes.go, db/dcrpg/chainmonitor.go, db/dcrpg/pgblockchain.go, explorer/explorer.go, main.go
This resolves issue https://github.com/decred/dcrdata/issues/610
=> lite mode fixes with new ChainDBRPC struct

main.go
resolves issue https://github.com/decred/dcrdata/issues/614
=> fix another lite mode crash

stakedb/ticketpool.go
addressing issue https://github.com/decred/dcrdata/issues/619
=> stakedb: Close badger iterator after View

api/insight/apiroutes.go, api/insight/converter.go, api/types/insightapitypes.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/queries.go
Looks like a few things broke when we upgraded the tables with PR #427.  I'll go through all of insight and retest.
[1] ok
[1.1] ok
[2] ok
[2.1] ok
[3] ok
[4] ok
[5] ok
[5.1] ok
[6] missing addr field - fixed, missing spent fields - fixed
[6.1] ok
[7] ok
[7.1] ok
[8],[8.2] missing transaction list - fixed
[8.1] ok
[9.1] ok
[9.2] ok
[9.3] ok
[9.4] ok
[10] incorrect UTXO - fixed
[11] ok
[12] ok
[13] duplicate transactions - fixed
[14] ok
[15] ok
[16] ok
[17] not tested (send raw transaction)
[19] ok
[20]  ok
[21] ok
=> Insight API fixes for upgraded tables

blockdata/blockdata.go, config.go, db/agendadb/db.go, main.go
This adds a configuration option that make the agendadb filename configurable. 
It also ensures that the file location is housed in the datadir. 
This is a final fix for #587
=> Make agendadb filename configurable and house it in datadir folder

blockdata/blockdata.go, explorer/explorer.go, explorer/explorertypes.go, explorer/templates.go, views/address.tmpl, views/block.tmpl, views/home.tmpl, views/mempool.tmpl, views/tx.tmpl
This displays the next expected ticket price alongside the current ticket price 
Fixes #540
=> Add utility that displays next expeted ticket price

README.md, version/version.go
Bump version to 3.1.0.
Address doctoc weirdness.
=> begin 3.1 release cycle

public/css/main.css, views/address.tmpl, views/block.tmpl, views/charts.tmpl, views/explorer.tmpl, views/home.tmpl, views/mempool.tmpl, views/tx.tmpl
@chappjc addresses the footer overlap issue on narrow screens
=> add some bottom padding to main container to prevent footer overlap

explorer/explorermiddleware.go, views/status.tmpl
made changes in file explorermiddleware.go for showing future block.
=> made changes in file explorermiddleware.go for showing future block.

api/insight/apiroutes.go
Typo fix for rawtx broadcast response from Insight API
=> response for tx send:  rawtx -> txid

db/dcrpg/internal/addrstmts.go, db/dcrpg/queries.go
Add `SelectAddressSpentUnspentCountAndValue` query that gets the count and total value for spent and unspent address table rows for a given address.  It uses `GROUP BY (is_funding, matching_tx_hash='')` with aggregate functions to do it efficiently in a single scan on the addresses table.
Scanning the result, `isFunding && noMatchingTx` means unspent, `!isFunding && !noMatchingTx` means spent, while `!isFunding && noMatchingTx` is not expected so an error is logged.
Timings on one machine (project fund):
| query  | timing   |
|---|---|
| new unified query  | 230 ms  |
| old unspent query  | 380 ms  |
| old spent query | 227 ms |
| old spent+unspent queries | 607 ms |
That's a 62% reduction in time (down to 38% of the original query cost) to get both spent and unspent totals for the …
=> dcrpg: combine spent and unspent totals queries into one

.gitignore
Add v3 to gitignore to avoid it being commited to github.
=> Fix: Add v3 to the gitignore file

views/extras.tmpl
=> menu: remove duplicate "Block" item

db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrpg/upgrades.go, db/dcrsqlite/apisource.go, explorer/explorermiddleware.go, explorer/explorerroutes.go, explorer/explorertypes.go, main.go, public/css/main.css, views/address.tmpl, views/tx.tmpl
This PR will implement the same functionality as #665  but without a db upgrade.  It uses a slightly different strategy to leverage the address fill function.
=> Address page tx highlighting - No db upgrade

db/dcrpg/pgblockchain.go
Add ticket hash to error message from `TxnDbID`.
In addition to documentation, this also changes a few warnings to errors where an error is not expected.
Improve readability of `SetSpendingForFundingOP` with named variables.
Move call to `CollectTicketSpendDBInfo` into the `if updateTicketsSpendingInfo` conditional where the outputs are used.
=> dcrpg: document and tweak (*ChainDB).storeTxns

db/dcrsqlite/sync.go
In dcrsqlite/sync.go, `minBlocksToCheck` was computed using the
"start height" of the sync loop, which is normally one past the best block
in the DB.  But it did not include a necessary +1.
This change instead compares node height to DB height in deciding if the
DB is already sync'd or if the chain server is behind.  `startHeight` may
still be `dbHeight` or `dbHeight+1` depending on the state of aux DB
coordination, but the computation of `minBlocksToCheck` is now correct
regardless.
=> dcrsqlite: properly compute blocks to check in sync

api/apiroutes.go, config.go, config_test.go, main.go
This resolves https://github.com/decred/dcrdata/issues/730
=> config: adjust config/log/data paths if appdata is changed

README.md, views/extras.tmpl
Updates API endpoint links that pointed to no longer existent page.
Fixes #753
=> update JSON API link on website and in docs

sample-dcrdata.conf, sample-nginx.conf
nginx.conf: update TLS, ciphers, dhparam, ecdh_curve, etc.
dcrdata.conf: list current logging subsystems and add import-side-chains
=> update sample configs

explorer/explorermiddleware.go, explorer/explorerroutes.go, explorer/explorertypes.go, views/extras.tmpl, views/status.tmpl
This is a resubmission of https://github.com/decred/dcrdata/pull/703 by @McEdward and @SeaLightHouse
=> Show page for blocks in the future

public/css/main.css, views/extras.tmpl
Adds a fixed width wrapper to have a consistent layout for footer items as "connecting to websocket" changes to "connected"
=> prevent footer text from jiggling when connection status changes

CONTRIBUTING.md, README.md
=> Git workflow description in CONTRIBUTING.md

explorer/explorerroutes.go, explorer/explorertypes.go, views/parameters.tmpl
=> Parameters page tweaks.

explorer/explorertypes.go, public/js/controllers/nexthome-blocks-display.js
also corrected vote yes/no tooltip message on /nexthome block display triggered on websocket update
=> fix undefined tx type in home, tx websocket update in /mempool

public/css/main.css, public/css/nexthome.css
This addresses the UI formatting issues in the `3.1-stable` branch that are described in https://github.com/decred/dcrdata/issues/809.
=> [3.1] backport formatting fixes

db/dcrpg/queries.go
=> Correct TimeDef scanning bug

explorer/explorer.go
Do not pre-populate charts data in `explorer.New`. Wait for initial `Store`.
Give `explorer.chartDataCounter` a `Height` and `Update` function. `Height` returns -1 when data has never been assigned.
In `prePopulateChartsData`, return without update if cache is at same height as the `explorerUI` (as determined by `.pageData.BlockInfo.Height` via `(*explorerUI).Height`).
In `(*explorerUI).Store`, only run `prePopulateChartsData` AFTER storing the new `BlockInfo` in `pageData`.
Avoid launching two identical queries by holding the `chartDataCounter` cache locked when performing both the height check and update in `prePopulateChartsData`.
Add thread-unsafe `height` and `update` functions for `chartDataCounter` so that the cache can be locked for both operations manually.
This partially …
=> pre-populate charts data tweaks

notification/ntfnhandlers.go
Add Tracef logging for OnBlockConnected, OnBlockDisconnected, and OnReorganization.
This also adds OnBlockDisconnected, which is not used except for debugging.
Now return on error if a block header from a notification fails to deserialize.
=> notification: Log disconnected and connected blocks

blockdata/chainmonitor.go, db/dcrpg/chainmonitor.go, db/dcrsqlite/apisource.go, db/dcrsqlite/chainmonitor.go, main.go, notification/ntfnchans.go, notification/ntfnhandlers.go, rpcutils/rpcclient.go, rpcutils/rpcclient_online_test.go, stakedb/chainmonitor.go, txhelpers/txhelpers.go
This is a backport of https://github.com/decred/dcrdata/pull/828
=> [3.1] backport for dcrd RPC v5.0.0

db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go
=> UTXOs on /tx matched against mempool

db/dcrsqlite/apisource.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorertypes.go, explorer/mempool.go
=> /tx page Mempool inputs are grabbed from explorer

views/extras.tmpl
Looks like #785 broke the fix for the "JSON API Docs" link.
=> Fixes reversetabnabbing (2)

api/apirouter.go, api/apiroutes.go, db/dbtypes/types.go, explorer/explorer.go, explorer/explorerroutes.go, middleware/apimiddleware.go, public/index.js, public/js/controllers/agenda_controller.js, public/js/controllers/blocklist_controller.js, public/scss/charts.scss, views/address.tmpl, views/agenda.tmpl, views/charts.tmpl, views/explorer.tmpl, views/extras.tmpl, views/ticketpool.tmpl, views/timelisting.tmpl
Removes inline chart data from agenda.tmpl. Data is retrieved via AJAX instead.
#843
=> Agenda chart data: inline -> AJAX

explorer/explorer.go
Set a different lock, not the actual cache lock that can block Store.
=> [3.1] prePopulateChartsData was blocking explorerUI.Store

public/index.js, public/js/controllers/search_controller.js, views/extras.tmpl
Minor refactor to help clean out index.js and continue stimulus standardization
=> refactor search input handler into controller

explorer/explorer.go
Set a different lock, not the actual cache lock that can block Store.
Same as https://github.com/decred/dcrdata/pull/859, but for master
=> prePopulateChartsData was blocking explorerUI.Store

public/css/main.css, public/scss/responsive.scss
=> logo: clip more on small screens

main.go, sample-dcrdata.conf
=> Update to use dynamic database name. #414

public/index.js, public/js/controllers/networkOverview_controller.js, public/js/controllers/visualBlocks_controller.js, public/js/services/desktop_notification_service.js, public/js/services/event_bus_service.js, views/nexthome.tmpl
* create networkOverview controller for /nexthome stats pane
* create visualBlocks controller for /nexthome visual blocks
* add `off` method to EventBus
* use `off` to unbind event handlers when nexthome controllers disconnect from dom
* Use unix timestamp for mempool age date attribute ( it was in micro-seconds instead of the expected seconds and therefor not showing elapsed age correctly )
=> [WIP] move nexthome logic out of index.js and into controllers

README.md
Following up some recent changes, specifically the SCSS webpack integration and v4 bump.
=> A couple README updates.

explorer/explorerroutes.go, explorer/templates.go, public/index.js, public/js/controllers/address_controller.js, public/js/controllers/time_controller.js, public/js/controllers/tx_controller.js, views/extras.tmpl
* fix negative numbers showing instead of age when timezone offfsets misalign 
(Builds upon https://github.com/decred/dcrdata/pull/927)
=> Account for front & backend timezone offsets when computing age

api/insight/apirouter.go
The tollbooth rate limiter checks certain requests headers to determine which requests are coming from the same client.  When using the RealIP middleware, which puts the real IP in `RemoteAddr`, that must be used.  Otherwise it should use `{"X-Forwarded-For", "X-Real-IP", "RemoteAddr"}` in that order.
Also bump the rate lmiit up.  In the future this should be configurable.
=> insight: rate limiter must check headers for client IP

testutil/apiload/profiles.json
This uploads apiload's profiles.json with a new attack for the Insight API.
=> apiload: add insight attack definition

stakedb/stakedb.go, stakedb/ticketpool.go
This is confirmed to be a Windows issue.  Ref: https://github.com/dgraph-io/badger/issues/476#issuecomment-388122680
=> Attempt badger db recovery when the "truncate" error is encountered.

stakedb/ticketpool.go
Define `(*badgerLogger).logf` to filter log messages. It does the following:
- removes trailing newlines
- overrides the log level if the message is recognized in the `logLevelOverrides` map
- and then adds the prefix `"badger: "`
If there are no log level overrides for the message, the provided `defaultLevel` is used.
=> stakedb/badger: override badger's log levels

db/dcrsqlite/apisource.go
The input amounts for mempool transactions are now set correctly by
dcrd, except for side chain votes, so start verifying that the amount
agrees with the amount obtained by getting the prevout transaction.
If we had the prev output's pkScript, from which the input's addresses
are obtained, we would be able to completely skip the previous output
get transaction RPC.
=> dcrsqlite: start verifying input amounts

public/js/controllers/mempool_controller.js, views/mempool.tmpl
=> remove empty tx list message on newtx

public/js/controllers/ticketpool_controller.js, views/ticketpool.tmpl
Set "All Time" as the default Zoom button then ticketpool chart
=> Make ticketpool chart all time zoom button default

dev/build.sh
Remove the old v3 binary to avoid confusion.
Silence gnu parallel.
Remove old views and public folders when installing.
=> build.sh: remove old v3

main.go
`listenAndServeProto` now takes the shutdown `Context` and a `WaitGroup`.
`listenAndServeProto` launches a goroutine that shutsdown the web server
when the shutdown context is cancelled, and another goroutine for the
server's listener, which blocks until the server dies.
The `WaitGroup` now blocks in main until the server shutdown is complete
(along with all of the other goroutines using the `WaitGroup`).
If the server fails to listen, it requests it's own shutdown via `main`'s
shutdown context.
To give `main` a chance to halt startup if the server fails to bind to a
port, a brief delay is added before `listenAndServeProto` returns to `main`.
=> main: graceful web server shutdown

rpcutils/blockgate.go
Handle a cache miss in Block() if the waiter was too slow to retrieve
the block when notified.
Both signalHash and signalHeight require both height and hash inputs
so that they can avoid extra map lookups in blockWithHash and
hashAtHeight, respectively.
Make signalHash and signalHeight lock-free.  They are not thread-
safe -- no longer run them as goroutines. Instead have them
retrieve the wait channel, remove the wait channel from the list,
and launch at goroutine just to send the height/hash to each waiter.
WaitForHeight now checks if the block is cached, in addition to
checking fetchToHeight.
=> rpcutils: fix BlockGate

db/dcrpg/upgrades.go
=> dcrpg: upgrades do not need a blockgate

explorer/explorer.go
While here, remove an unused variable and document some others.
=> reduce syncStatusInterval to 2 seconds

api/apiroutes.go, api/insight/apiroutes.go, blockmemdb.go, cmd/rebuilddb2/rebuilddb2.go, db/dcrpg/chainmonitor.go, db/dcrpg/indexing.go, db/dcrpg/insightapi.go, db/dcrpg/internal/addrstmts.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/internal/indexes.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/internal/txstmts.go, db/dcrpg/internal/vinoutstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_test.go, db/dcrpg/sync.go, db/dcrpg/upgrades.go, explorer/explorer.go, explorer/explorermiddleware.go, explorer/websockethandlers.go, main.go, pubsub/pubsubhub.go
This force table reindexing and addresses spend updates when missing any indexes.
Also make `(*ChainDB).Height` return an `int64` instead of `uint64` since -1
is the special value indicating empty tables.  Note that `HeightDB()`
still returns `uint64` since it's error indicates empty (`sql.ErrNoRows`).
In `(*ChainDB).SyncChainDB` force reindex if `lastBlock == -1`.
dcrpg: add index inventory, missing/exists functions, and tests 
```
[WRN] DATD: Some table indexes not found!
[WRN] DATD:  - Missing Index "uix_tx_hashes": "transactions on block hash and transaction hash"
[WRN] DATD:  - Missing Index "uix_ticket_hashes_index": "tickets table on block hash and transaction hash"
[WRN] DATD:  - Missing Index "uix_ticket_ticket_db_id": "tickets table on transactions table row ID"
[WRN] DATD:  - …
```
=> detect missing indexes and force reindex and addresses update

public/js/controllers/blocklist_controller.js
=> Clear /blocks query parameters on new time period selection

db/dcrpg/pgblockchain.go, main.go
Resolving https://github.com/decred/dcrdata/issues/1058
=> fix lite mode, again

main.go
The profile may be interesting before the chain is in sync.
=> profiler: start immediately

views/home.tmpl
=> explorer: fix vote rejection icon typo

config.go, config_test.go
=> config: normalize addresses and expand paths

api/apiroutes.go, api/insight/apiroutes.go, middleware/apimiddleware.go
Verify input is a valid hash before sending further up the code
chain.
=> api: sanity check tx input

stakedb/ticketpool.go
The only caller is NewStakePool, which only uses the height
for sanity checking.  Move this check to LoadAllPoolDiffs,
to prevent copying all the data again.
This saves some memory churn.
=> stakedb: Make LoadAllPoolDiffs return []PoolDiff

db/dcrsqlite/apisource.go
=> api: empty array for valid address with no txns

main.go
=> shutdown rpcclient before closing notifications channels

db/dcrsqlite/apisource.go
Avoid a panic at https://github.com/decred/dcrdata/blob/e402297f5a80421b4b1308525cf2ef2faf03ce0d/explorer/explorerroutes.go#L1554
=> explorer: create stub when address validates as other network

public/js/controllers/homepage_controller.js, public/scss/table.scss, views/home.tmpl, views/proposals.tmpl
Resolves a few more issues with tables, mostly for mobile views.
=> explorer: more table tweaks

config.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/explorerroutes_test.go, main.go, views/block.tmpl, views/disapproved.tmpl, views/extras.tmpl, views/parameters.tmpl, views/status.tmpl
=> explorer: remove hard-coded links from template files

public/scss/_variables.scss, public/scss/address.scss, public/scss/nexthome.scss, public/scss/themes.scss
Resolves #1006. I'm thinking is just needed these small tweaks. @raedah can you confirm?
=> explorer: improve dark mode for visual blocks

cmd/rebuilddb/rebuilddb.go, db/dcrsqlite/apisource.go, db/dcrsqlite/dcrsqlite_test.go, db/dcrsqlite/sqlite.go, main.go
=> blockdata: shutdown on sqlite database is locked error

public/js/controllers/charts_controller.js
=> explorer: add steps to ticket price chart

txhelpers/txhelpers.go, txhelpers/txhelpers_test.go
The accelerates `txhelpers.UnconfirmedTransactionsForAddress` by making async
getrawtransaction (verbose) RPCs to facilitate greater concurrency.
Also tighten up `MsgTxFromHex`.
=> txhelpers: use async getrawtransaction verbose

db/dcrpg/tables.go, db/dcrpg/upgrades.go
=> Fix db update problems

explorer/explorer.go, views/address.tmpl
Also add the `DownloadLink` field to `explorer.explorerLinks`.
Make the link open in a new tab.
=> change the download link to decred.org/downloads

public/js/controllers/ticketpool_controller.js
=> ticketpool_controller.js: Fix infinity % chart display

explorer/explorer.go, gov/agendas/deployments.go, gov/agendas/deployments_test.go, main.go
Adds the agenda db (storm db version) auto update at intervals of 5 blocks.
=> agenda db(storm): Add auto update

README.md
This adds a Release Status section to README.md.
Also add tinfo API docs.
=> README: add a Release Status section

views/home.tmpl
=> explorer: fix layout of last block data for small screens

version/version.go
Begin the 4.1 release cycle (this will be much much faster than 4.0)
=> bump dcrdata to 4.1.0

run_tests.sh
=> CICD: Update the run_test.sh

api/apiroutes.go, api/insight/apiroutes.go, api/types/apitypes.go, main.go, middleware/apimiddleware.go, middleware/go.mod
Getters and setters implemented. New apitypes.APIStatus type for /status response.
For #1094, #1150.
=> api: unexport apitypes.Status fields

run_tests.sh
This backports d4ec82a02aed5004320dbe18407e50c652467832 and 16bd298631386673aa5bedf59e436fe00ac3a60f for 4.0.
=> [4.0-stable] ci: backport module tests updates

config.go, db/dcrpg/sync.go, db/dcrpg/system.go, db/dcrpg/tables.go, main.go
Good table statistics is important for performance, especially after bulk data imports or table indexing.
Ensuring the `vins` table is analyzed before running `UpdateSpendingInfoInAllAddresses` should also help the performance of these addresses table updates.
=> dcrpg: ANALYZE tables after indexing and bulk import

main.go
FileServer now rejects directory listings.
Resolves https://github.com/decred/dcrdata/issues/1173
=> main: rewrite FileServer

config.go, db/dcrpg/pgblockchain.go, explorer/explorer.go, explorer/explorermiddleware.go, explorer/explorerroutes.go, go.mod, go.sum, gov/agendas/deployments.go, gov/agendas/deployments_test.go, gov/agendas/go.mod, gov/politeia/go.mod, gov/politeia/go.sum, gov/politeia/piclient/piclient.go, gov/politeia/proposals.go, gov/politeia/proposals_test.go, gov/politeia/types/types.go, main.go, public/js/controllers/proposal_controller.js, public/scss/charts.scss, views/extras.tmpl, views/proposal.tmpl, views/proposals.tmpl
It will help in updating past such an error if new data exists.
```
2019-04-15 19:17:13.120 [ERR] DATD: updating proposals db failed: RetrieveProposalByToken failed: retrieving 5d9cfb07aefb338ba1b74f97de16ee651beabc851c7f2b5f790bd88aea23b3cb proposal vote status failed: request (https://proposals.decred.org/api/v1/proposals/5d9cfb07aefb338ba1b74f97de16ee651beabc851c7f2b5f790bd88aea23b3cb/votestatus) failed with status code: 400 Bad Request 
```
=> Proposals CleanUp

db/dcrpg/pgblockchain.go, db/dcrpg/pgblockchain_charts_test.go, db/dcrpg/queries.go, explorer/chartscache.go, package-lock.json, public/js/controllers/charts_controller.js, run_tests_with_chartests.sh
The Predicted coin supply from the start till till the latest time a coin was mined has its data plotted on an axis.
An extra legend entry to show percentage change between the Predicted coin supply and the Actual coin supply was added. To calculate the percentage change, the actual supply is used as the base.
Formula used to generate the inflation axis data is derived from this data https://dcrstats.com/subsidy (`Maximum total DCR subsidy`)
*h* = **Given Block Height**
*TCM<sub>h</sub>* = **Total Coins Mined till height `h`**
*R<sub>0</sub>* = **Block reward at genesis block** = `31.19582664` for mainnet
*rInterval* = **Interval of block subsidy reduction interval** = `math.Floor(h / SubsidyReductionInterval)`
*rSubsidyRate* = **Subsidy reduction rate for every `rInterval`** = …
=> Coin Supply chart: Add Inflation chart axis

db/dbtypes/go.sum, db/dcrpg/go.mod, db/dcrpg/go.sum, go.mod, go.sum
https://github.com/dmigwi/go-piparser/commit/8412e0f44f5560605f0af8993b0fa0ef78e79a87 `time.NewTimer(` has been replaced with `time.NewTicker(`
=> Update piparser dependency version

db/cache/charts.go, db/cache/charts_test.go
Also a few followups to address @dmigwi's orphaned review from #1274.
=>  charts: fix reorg deadlock

db/dcrpg/pgblockchain.go
~~Tested by forcing a panic in `path/to/go/pkg/mod/github.com/dmigwi/go-piparser/proposals@v0.0.0-20190426030541-8412e0f44f55/parser.go` in `UpdateSignal`.~~
Never mind. Don't do that. Use a replace in the `go.mod` and point it to a repo somewhere.
=> pgblockchain: recover from piparser panic

public/js/helpers/chart_helper.js
=> proposals: Drop the red columns that have a value of zero

api/apiroutes.go, api/types/apitypes.go, db/dbtypes/types.go, db/dcrpg/internal/txstmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/websockethandlers.go, public/js/controllers/ticketpool_controller.js, public/scss/charts.scss, views/ticketpool.tmpl
- Remove the solo/pooled description from the ticketpool page.
- Replace `All Time` button with `Blocks`
=> ticketpool: Edit the solo and pooled description

package-lock.json
=> node: update fstream

config.go, main.go
Remove `--dcrd-block-prefetch`/`-P`, and add `--no-dcrd-block-prefetch`.
=> config: <s>make block prefetch the</s> be 1337 by default

explorer/explorer.go, go.mod, gov/agendas/tracker.go, main.go
lite mode is regrettably still available in dcrdata 4.1.  This resolves panics that prevented it from working.
=> [4.1] resolve lite mode panics

explorer/websocket.go
For a very long time we've been ignoring some error messages when `explorer`'s websocket controller shuts down on dcrdata shutdown.
```
[INF] EXPR: Stopping websocket hub.
[ERR] EXPR: close channel already closed. This should not happen.
[ERR] EXPR: Do not send on stopPing channel, only close it.
```
These are bugs that were fixed in the `pubsub` package's version of the websocket controller, and these changes make the fixes in the `explorer` package.
=> explorer: websocket oopsies

db/cache/charts.go, db/cache/charts_test.go, db/dcrpg/internal/blockstmts.go, db/dcrpg/queries.go, public/js/controllers/charts_controller.js, public/js/helpers/chart_helper.js, public/scss/charts.scss, views/charts.tmpl, views/proposal.tmpl
=> chart: Add purchased tickets axis to the ticket price chart

gov/agendas/tracker.go
When dcrd has no deployments, as in simnet, `VoteTracker` registered that as an error, which was wrong.
=> gov: VoteTracker handle no vote info from node

db/cache/charts.go, db/cache/charts_test.go, db/dcrpg/internal/stakestmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, main.go, public/js/controllers/charts_controller.js, views/charts.tmpl
=> chart: Add missed votes chart

explorer/explorer.go, explorer/syncstatus.go, explorer/websocket.go, explorer/websockethandlers.go, go.mod, main.go, mempool/go.mod, mempool/monitor.go, pubsub/democlient/go.mod, pubsub/democlient/main.go, pubsub/go.mod, pubsub/psclient/client.go, pubsub/psclient/client_test.go, pubsub/pubsubhub.go, pubsub/types/go.mod, pubsub/websocket.go, pubsub/websocket_test.go
As per https://github.com/decred/dcrdata/issues/1379
=> prepare for pubsub/types/v2

api/apiroutes.go, api/insight/apimiddleware.go, api/insight/apiroutes.go, api/insight/apiroutes_test.go, api/insight/converter.go, api/types/go.mod, blockdata/blockdata.go, blockdata/go.mod, cmd/scanblocks/scanblocks.go, db/dcrpg/go.mod, db/dcrpg/insightapi.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, db/dcrsqlite/apisource.go, db/dcrsqlite/go.mod, db/dcrsqlite/sqlite.go, db/dcrsqlite/sync.go, explorer/websockethandlers.go, go.mod, mempool/collector.go, mempool/go.mod, mempool/mempoolcache.go, mempool/mptypes.go, middleware/apimiddleware.go, middleware/go.mod, rpcutils/go.mod, rpcutils/rpcclient.go, stakedb/go.mod, stakedb/stakedb.go
As per https://github.com/decred/dcrdata/issues/1379
=> prepare for api/types/v3

db/dcrsqlite/apisource.go, db/dcrsqlite/go.mod, explorer/explorer.go, go.mod, log.go, main.go, mempool/go.mod, pubsub/go.mod, pubsub/pubsubhub.go
To be tagged as `mempool/v3.0.0` as per https://github.com/decred/dcrdata/issues/1379
=> prepare for mempool/v3

run_tests.sh, run_tests_with_chartests.sh
It also did not test several CLI apps.
=> run_tests did not test all packages in a module

public/js/controllers/market_controller.js, views/market.tmpl
=> set default market view to aggregated depth

api/types/apitypes.go
If the DB is at node height, the age of the best block may be fairly
large, corresponding to an extremely low likelihood block interval.
If the DB is not at node height, allow the DB to lag if the age of the
best block in the DB is very recent, suggesting that the network's best
block may still be processing.
=> api/types: API can be happy even when lagging

db/cache/charts.go, public/js/controllers/charts_controller.js, public/js/helpers/zoom_helper.js, public/scss/charts.scss, views/charts.tmpl
New percent staked coin chart and fixes some charts legends.
Resolving https://github.com/decred/dcrdata/issues/996
=> chart: Add a percent staked coins chart

public/js/controllers/charts_controller.js
You can close this if you don't want it.
=> [5.0] charts: fix ticket pool value scale

public/js/controllers/address_controller.js
**Before Adding the step plot**
**After**
=> Add step plot for the address balance chart

db/dcrsqlite/apisource.go, explorer/explorerroutes.go, explorer/types/explorertypes.go, views/tx.tmpl
=> explorer: display maturity for revocations

db/dcrpg/pgblockchain.go, main.go
Below is a syncing log showing when updates for **Piparser Votes data**, **Proposals API data** and **agendas data** updates fetch should run. They should run after the first sync on system startup completes.
```bash
2019-06-29 11:46:11.855 [INF] PSQL: Updating the explorer with information for block 357380
2019-06-29 11:46:12.338 [INF] SQLT: Rescan finished successfully at height 357387.
2019-06-29 11:46:12.338 [INF] SQLT: resyncDBWithPoolValue completed in 5.335726313s
2019-06-29 11:46:12.338 [INF] DATD: SQLite sync ended at height 357387
2019-06-29 11:46:12.369 [INF] PSQL: Avg. speed: 175 tx/s, 585 vout/s
2019-06-29 11:46:12.369 [INF] PSQL: Pre-fetching project fund data at height 357387...
2019-06-29 11:46:14.234 [INF] PSQL: Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx: 87112 spent totalling …
```
=> Run proposals and agendas updates after the first sync is completed

explorer/explorerroutes.go
The following paths can now be used to reference the same page.
1. `/search?search=073694ed82d34b2bfff51e35220e8052ad4060899b23bc25791a9383375cae70`
2. `/search?search=decred-bug-bounty-proposal-phase-2`
3. `/proposal/decred-bug-bounty-proposal-phase-2`
4. `/proposal/073694ed82d34b2bfff51e35220e8052ad4060899b23bc25791a9383375cae70`
=> explorer: Query and search a Proposal by both RefID and token

views/proposals.tmpl
Resolves #1461
I agree with @xaur that it looks much better.
=> explorer: proposals: change table font from mono to sans-serif

config.go, explorer/explorer.go, explorer/explorerroutes.go, explorer/templates.go, main.go
This makes front-end development on Windows faster.
=> explorer: add config option to force template reloads

explorer/explorerroutes.go, gov/politeia/types/types.go, views/proposal.tmpl
Fix the proposal remaining time value on the proposal details page.
=> gov/proposal: Correct proposals remaining time

views/proposals.tmpl
=> proposals: show voter turnout as percentage

explorer/templates.go, views/proposal.tmpl, views/proposals.tmpl
also adds whitespace to voting now display
Resolves #1527
=> proposals: fix percentage completion

explorer/explorer.go
Fix moved links and remove unused btc explorer link.
=> update explorer links

db/dcrpg/pgblockchain.go, db/dcrpg/sync.go
=> dcrpg: signal heightClient channels on new best block

blockdata/go.sum, db/dcrpg/chkdcrpg/go.sum, db/dcrpg/go.sum, go.mod, go.sum, gov/agendas/deployments.go, gov/agendas/deployments_test.go, gov/go.mod, gov/go.sum, gov/politeia/proposals.go, gov/politeia/proposals_test.go, pubsub/democlient/go.sum, pubsub/go.sum, stakedb/go.mod, stakedb/go.sum, stakedb/ticketpool.go
Use storm/v3 now that it has been created in https://github.com/asdine/storm/pull/256
=> use asdine/storm/v3

views/explorer.tmpl, views/timelisting.tmpl, views/windows.tmpl
=> use new page size for disabling blocks dropdown

db/dcrpg/internal/stakestmts.go, db/dcrpg/queries.go, db/dcrpg/upgrades.go
additional pre-insert casting to signed types
=> dcrpg: upgrade to 1.4.0 for INT4 votes.version

go.mod, mempool/monitor.go, public/index.js, public/js/controllers/connection_controller.js, public/js/controllers/homepage_controller.js, public/js/controllers/mempool_controller.js, public/js/helpers/mempool_helper.js, public/js/services/messagesocket_service.js
I'm not sure that this solves all of the issues we've seen. I do know this solves at least some of the problems we were seeing though.
=> explorer: Fix a couple mempool bugs. Add js debug logging

public/js/controllers/charts_controller.js, public/scss/charts.scss, views/charts.tmpl
=> explorer charts: refactor legend formatting

README.md, docs/CONTRIBUTING.md
=> Fixes kubernetes link

views/extras.tmpl
* More privacy on a shared PC
* Suggestions are annoying when you are trying to input and address or tx
=> Disable auto complete on the search bar

db/dcrpg/pgblockchain.go, go.mod
=> dcrpg: fix voting start and end heights

views/agenda.tmpl, views/agendas.tmpl, views/block.tmpl, views/extras.tmpl, views/home.tmpl, views/mempool.tmpl, views/parameters.tmpl, views/tx.tmpl
- wrap <th>'s with <tr></tr>
- remove unneeded role=navigation from <nav>
- close <span>
- remove 'a' from <a>
- remove extra </div>
=> views: use valid html

public/js/controllers/proposal_controller.js
=> proposals: add data padding to bar chart

views/block.tmpl
Display a link to the mempool from latest block
Fixes #1636
=> link to mempool from latest block

views/proposal.tmpl
=> Add proposal name to HTML title

config.go, config_test.go
Testnet at 17778 and simnet at 17779.
=> config: different default ports for testnet and simnet

gov/agendas/tracker.go, public/js/helpers/meters.js, public/scss/charts.scss
Fixes a bug in the calculation of miner upgrade ratio. Adds two decimals of precision to the displayed value on /agendas. Also some minor aesthetic tweaks.
=> gov: fix pow version bug and add precision to meter display

db/dcrpg/chkdcrpg/go.mod, db/dcrpg/chkdcrpg/go.sum, db/dcrpg/pgblockchain.go, explorer/types/explorertypes.go, mempool/collector.go, mempool/go.mod, mempool/monitor.go, public/js/controllers/mempool_controller.js, pubsub/democlient/go.mod, pubsub/go.mod, views/mempool.tmpl
=> Display Fee rate column in mempool tx/tickets tables

views/home.tmpl
=> Total staked DCR terminology clarification

views/block.tmpl
=> Display time ago on block page

dev/build.sh, package-lock.json
npm ci does not update the package-lock.json; it uses it.
=> npm clean-install instead of install

views/home.tmpl
Fix for non-JS mode.  
Solves #1614
=> Time zone display cleanup on non-JS home

views/extras.tmpl
complementing https://github.com/decred/dcrdata/pull/1695
=> [5.2] bump dist app url query params

explorer/explorer.go, pubsub/pubsubhub.go
=> Fix block reward reduction progress off by 1.

explorer/explorerroutes.go
Correctly handle URLs without rows and height parameters.
=> explorer: fix default block height and divide by 0 rows

package-lock.json, package.json
they were at least not affecting us at runtime.
=> npm/webpack: resolve a number of vulns that were not affecting us

public/js/controllers/attackcost_controller.js, views/attackcost.tmpl
Removed default values from url query string on attack cost page
=> Removed default values from url query string on attack cost page

.github/workflows/build.yml, run_tests.sh
Update the checkout and setup-go github actions to v2.
Also update golangci-lint, change out-format, and run
asciicheck linter too.
=> update actions/{checkout,setup-go} to v2

public/js/controllers/market_controller.js, views/extras.tmpl
Whoops. Forgot that empty arrays are truthy.
=> market: fix new agg chart bug

gov/agendas/tracker.go
Currently only the last block version is checked to determine if PoW upgrade is complete.
This PR checks if 95% of the last 1000 blocks are mined with the latest version.
=> gov/agendas: fix pow upgrade

cmd/dcrdata/views/tx.tmpl
This is https://github.com/decred/dcrdata/pull/1758 rebased and tweaked.  Commit still authored by @Ekeh
=> Revocation labelled as vote on an expired transaction correction.

exchanges/exchanges.go, exchanges/exchanges_live_test.go, exchanges/exchanges_test.go, exchanges/go.mod
v1.1 -> v3
Part of #1810
Still running long tests. I saw a couple of sequence errors over the course of a few hours, so I wanna watch for a while longer.
=> exchanges: upgrade bittrex api

cmd/dcrdata/explorer/explorerroutes.go, cmd/dcrdata/public/scss/typography.scss, cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/views/mempool.tmpl, cmd/dcrdata/views/tx.tmpl, db/dbtypes/types.go, db/dcrpg/pgblockchain.go, explorer/types/explorertypes.go, mempool/collector.go, mempool/monitor.go, pubsub/pubsubhub.go
**Treasury txns in mempool:**
**TSpend choices decoded for a vote txn with valid tspend choices in last output:**
**Vote tally for a TSpend txn:**
=> tspend approval, treasury mempool

cmd/dcrdata/explorer/explorer.go, cmd/dcrdata/main.go, cmd/dcrdata/public/js/controllers/homepage_controller.js, cmd/dcrdata/views/home.tmpl, db/cache/charts.go, explorer/types/explorertypes.go
Is "mixed" the right word there?
=> explorer: add mixed percent to homepage

cmd/dcrdata/public/scss/navigation.scss, cmd/dcrdata/views/charts.tmpl
Resolves https://github.com/decred/dcrdata/issues/1679
=> remove inline js from charts page

cmd/dcrdata/explorer/explorerroutes.go, cmd/dcrdata/views/agenda.tmpl
Changed from `RuleChangeActivationInterval` to `RuleChangeActivationQuorum`.
=> Fix agenda quorum threshold

gov/politeia/proposals.go
This changes (*ProposalsDB).proposalsNewUpdate to retrieve all new
proposals, not just one page worth since there may be more than
one page worth of new props depending on how fast they are created
or if dcrdata was stopped for a long period.
Also more logging.
=> gov/politeia: refactor proposalsNewUpdate

gov/politeia/proposals.go
The explorer package is responsible for periodically (every 5th block) triggering updates to Politeia proposals, however cmd/dcrdata does an initial update on startup too.  This modifies `(*ProposalsDB).ProposalsSync` so that it will not start multiple concurrent updaters.  Since the initial fetch can take a couple minutes, fast blocks could even cause this even without cmd/dcrdata starting a startup sync.
=> gov/politeia: prevent multiple concurrent updates

cmd/dcrdata/package-lock.json
Fix some not-a-vulnerabilities. `dedup` while here.
=> npm-audit-fix

cmd/dcrdata/public/scss/_variables.scss, cmd/dcrdata/public/scss/bootstrap_overrides.scss, cmd/dcrdata/public/scss/utils.scss, cmd/dcrdata/views/home.tmpl, cmd/dcrdata/views/market.tmpl, cmd/dcrdata/views/rawtx.tmpl, cmd/dcrdata/views/ticketpool.tmpl
This diff fixes some leftover design issues caused by the bootstrap 5
package upgrade.
=> ui: Bootstrap 5 leftover design fixes

exchanges/exchanges.go
https://api.coindesk.com/v1  -> v2
https://api.binance.com/api/v1 -> v3
Closes #1810
=> upgrade exchange api versions

.github/workflows/build.yml, run_tests.sh
This makes CI test for changes to extras.tmpl that result from `npm run build` as in https://github.com/decred/dcrdata/pull/1899
=> test for extras.tmpl updates

cmd/dcrdata/views/proposal.tmpl
=> Minor UI fix

cmd/dcrdata/views/extras.tmpl
=> views/extras.tmpl: update footer date

cmd/dcrdata/views/proposal.tmpl, cmd/dcrdata/views/proposals.tmpl
Before: 
After: 
Closes #1884 
[View live display  ](http://159.65.95.71:7777/proposals)
=> UI: Fix incorrect vote status display

cmd/dcrdata/public/js/controllers/address_controller.js, cmd/dcrdata/public/js/controllers/blocklist_controller.js, cmd/dcrdata/public/js/controllers/homepage_controller.js, cmd/dcrdata/public/js/controllers/mempool_controller.js, cmd/dcrdata/public/js/controllers/tx_controller.js, cmd/dcrdata/public/js/helpers/mempool_helper.js, cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/views/home.tmpl, cmd/dcrdata/views/mempool.tmpl, cmd/dcrdata/views/tx.tmpl, explorer/types/explorertypes.go
Requires https://github.com/decred/dcrdata/pull/1934
This fixes a variety of mempool bugs on the frontend, mainly relating to treasury spends and adds.
=> frontend: fix treasury tx type handling

cmd/dcrdata/internal/explorer/explorerroutes.go, cmd/dcrdata/internal/explorer/templates.go, cmd/dcrdata/public/js/controllers/tx_controller.js, cmd/dcrdata/views/extras.tmpl, cmd/dcrdata/views/tx.tmpl, db/dbtypes/extraction.go, db/dbtypes/types.go, db/dcrpg/go.mod, db/dcrpg/internal/stakestmts.go, db/dcrpg/pgblockchain.go, db/dcrpg/queries.go, explorer/types/explorertypes.go
- show max possible votes for the voting interval.
- show min required votes(quorum).
- show approx. calendar dates of start and end blocks.
- show quorum pass progress.
- show required yes votes pass progress.
- show which Pi key signed the TSpend.
closes #1835
=> multi: Expose more treasury mechanics on TSpend tx page

cmd/dcrdata/views/extras.tmpl
=> UI: show tx block on address page

cmd/dcrdata/views/extras.tmpl
Closes https://github.com/decred/dcrdata/issues/1770
=> cmd/dcrdata/views: add onion link to html header

cmd/dcrdata/views/extras.tmpl
Closes https://github.com/decred/dcrdata/issues/1746
=> {cmd/dcrdata}: Fix zero fee display

cmd/dcrdata/views/tx.tmpl
=> dcrdata/views: fix tspend vote turnout percentage

cmd/dcrdata/public/js/controllers/charts_controller.js, cmd/dcrdata/views/extras.tmpl
=> {cmd/dcrdata/public/js}: Set chart mode before display on chart view
